import test,{before,beforeEach,after}from'node:test';
import{readFileSync}from'node:fs';
import{initializeTestEnvironment,assertFails,assertSucceeds,RulesTestEnvironment}from'@firebase/rules-unit-testing';
import{collection,doc,getDoc,getDocs,query,serverTimestamp,setDoc,Timestamp,updateDoc,where,writeBatch}from'firebase/firestore';
let env:RulesTestEnvironment;const projectId='demo-securetrack';
before(async()=>{env=await initializeTestEnvironment({projectId,firestore:{host:'127.0.0.1',port:8080,rules:readFileSync('firestore.rules','utf8')}})});after(async()=>env.cleanup());
const user=(uid:string,role:string)=>({uid,email:uid+'@example.test',displayName:uid,photoDataUrl:'',role,status:'active',inventory_count:0,inventory_breakdown:{fmc920:0,fmc130:0,sim_cards:0},created_at:Timestamp.now()});
const shift=(tech='tech-a',job_type='new_installation')=>({technician_id:tech,technician_name:tech,site_name:'Workshop',company_name:'Acme',customer_name:'Acme',contact_person:'Omar',customer_phone:'+971501234567',vehicle_number:'Dubai A 12345',maps_url:'https://maps.app.goo.gl/example',job_type,unit_count:1,radius_m:150,grace_minutes:15,date:'2026-09-15',timezone:'Asia/Dubai',scheduled_at:Timestamp.fromMillis(Date.now()+60000),window_start:Timestamp.fromMillis(Date.now()-60000),window_end:Timestamp.fromMillis(Date.now()+3600000),created_at:Timestamp.now()});
beforeEach(async()=>{await env.clearFirestore();await env.withSecurityRulesDisabled(async c=>{const d=c.firestore();for(const[u,r]of[['tech-a','technician'],['tech-b','technician'],['admin','admin'],['manager','manager'],['accountant','accountant'],['hr','hr'],['it','it'],['master','master_admin']])await setDoc(doc(d,'users',u),user(u,r));for(const uid of ['tech-a','tech-b'])await setDoc(doc(d,'inventory_accounts',uid),{technician_id:uid,opening:{FMC920:5,FMC130:0,FMC125:0,'Jimi VL03':0,GT06:0,Ruptela:0,'SIM Etisalat':0,'SIM du':0,'SIM International':0,SIM:5},timestamp:Timestamp.now()});await setDoc(doc(d,'shifts','job-install'),shift());await setDoc(doc(d,'shifts','job-sim'),shift('tech-a','sim_change'));await setDoc(doc(d,'shifts','job-remove'),shift('tech-a','device_removal'))})});
function db(uid='tech-a'){return env.authenticatedContext(uid,{email:uid+'@example.test'}).firestore()}
const completion=(id:string,type:string,model:string,imeis:string[],sims:string[])=>({technician_id:'tech-a',technician_name:'tech-a',shift_id:id,job_type:type,unit_count:1,device_model:model,device_imeis:imeis,sim_numbers:sims,sim_count:sims.length,...(sims.length?{sim_provider:'Etisalat'}:{}),customer_ref:'Acme',vehicle_ref:'',notes:'',timestamp:serverTimestamp(),captured_at:Timestamp.now()});
const move=(type:'installed'|'sim-used',model:string,quantity:number,sims:number)=>({technician_id:'tech-a',technician_name:'tech-a',type,device_model:model,quantity,sim_count:sims,...(sims?{sim_provider:'Etisalat'}:{}),timestamp:serverTimestamp(),captured_at:Timestamp.now(),notes:''});

test('only master administrator creates accounts and changes roles',async()=>{const created=user('new-user','technician');await assertFails(setDoc(doc(db('new-user'),'users','new-user'),created));await assertFails(setDoc(doc(db('admin'),'users','new-user'),created));await assertSucceeds(setDoc(doc(db('master'),'users','new-user'),{...created,created_at:serverTimestamp()}));await assertFails(updateDoc(doc(db('admin'),'users','tech-a'),{role:'manager'}));await assertSucceeds(updateDoc(doc(db('master'),'users','tech-a'),{role:'manager'}));await assertFails(updateDoc(doc(db('master'),'users','master'),{role:'technician'}))});
test('management and HR can read operations but technician data stays scoped',async()=>{await assertSucceeds(getDocs(collection(db('manager'),'shifts')));await assertSucceeds(getDocs(collection(db('hr'),'installations')));await assertSucceeds(getDocs(collection(db('it'),'users')));await assertFails(getDocs(collection(db(),'users')));await assertFails(getDoc(doc(db('tech-b'),'shifts','job-install')))});
test('technician can load only their inventory account using the dashboard query',async()=>{const own=query(collection(db(),'inventory_accounts'),where('technician_id','==','tech-a'));const other=query(collection(db(),'inventory_accounts'),where('technician_id','==','tech-b'));await assertSucceeds(getDocs(own));await assertFails(getDocs(other))});
test('admin assigns jobs while manager, IT and technician are read only',async()=>{await assertSucceeds(setDoc(doc(db('admin'),'shifts','assigned'),{...shift(),created_at:serverTimestamp()}));await assertFails(setDoc(doc(db('manager'),'shifts','manager-job'),{...shift(),created_at:serverTimestamp()}));await assertFails(setDoc(doc(db('it'),'shifts','it-job'),{...shift(),created_at:serverTimestamp()}));await assertFails(setDoc(doc(db(),'shifts','self-job'),{...shift(),created_at:serverTimestamp()}))});
test('new installation completion requires paired stock deduction',async()=>{const d=db();const batch=writeBatch(d);batch.set(doc(d,'inventory_logs','job-install'),move('installed','FMC920',1,1));batch.set(doc(d,'installations','job-install'),completion('job-install','new_installation','FMC920',['862476051161825'],['8997112212789413817']));await assertSucceeds(batch.commit());await assertFails(setDoc(doc(db(),'installations','unassigned'),completion('unassigned','new_installation','FMC920',['862476051161825'],['8997112212789413817'])))});
test('legacy assigned jobs without job type or unit count can still be completed',async()=>{await env.withSecurityRulesDisabled(async c=>{const d=c.firestore();const legacy=shift();delete (legacy as any).job_type;delete (legacy as any).unit_count;await setDoc(doc(d,'shifts','job-legacy'),legacy)});const d=db();const batch=writeBatch(d);batch.set(doc(d,'inventory_logs','job-legacy'),move('installed','FMC920',1,1));batch.set(doc(d,'installations','job-legacy'),completion('job-legacy','new_installation','FMC920',['862476051161825'],['8997112212789413817']));await assertSucceeds(batch.commit())});
test('SIM change deducts only SIM and removal records no movement',async()=>{let d=db();let batch=writeBatch(d);batch.set(doc(d,'inventory_logs','job-sim'),move('sim-used','',0,1));batch.set(doc(d,'installations','job-sim'),completion('job-sim','sim_change','',[],['8997112212789413817']));await assertSucceeds(batch.commit());await assertSucceeds(setDoc(doc(db(),'installations','job-remove'),completion('job-remove','device_removal','FMC920',['862476051161825'],[])))});
test('only stock administrators and accountants issue stock',async()=>{const receipt={...move('installed','FMC920',2,2),type:'received'};await assertSucceeds(setDoc(doc(db('admin'),'inventory_logs','receipt-a'),receipt));await assertSucceeds(setDoc(doc(db('master'),'inventory_logs','receipt-m'),receipt));await assertSucceeds(setDoc(doc(db('accountant'),'inventory_logs','receipt-c'),receipt));await assertFails(setDoc(doc(db('manager'),'inventory_logs','receipt-x'),receipt));await assertFails(setDoc(doc(db(),'inventory_logs','receipt-t'),receipt))});
test('technician check-in and login GPS remain protected',async()=>{const log={technician_id:'tech-a',latitude:25.2,longitude:55.3,accuracy_m:10,timestamp:serverTimestamp()};await assertSucceeds(setDoc(doc(db(),'attendance_logs','job-install'),log));await assertSucceeds(setDoc(doc(db(),'login_logs','login-a'),log));await assertFails(setDoc(doc(db('tech-b'),'login_logs','spoof'),log));await assertFails(updateDoc(doc(db(),'attendance_logs','job-install'),{latitude:0}))});
