import test,{before,beforeEach,after}from'node:test';
import{readFileSync}from'node:fs';
import{initializeTestEnvironment,assertFails,assertSucceeds,RulesTestEnvironment}from'@firebase/rules-unit-testing';
import{collection,doc,getDoc,getDocs,query,runTransaction,serverTimestamp,setDoc,Timestamp,updateDoc,where,writeBatch}from'firebase/firestore';
let env:RulesTestEnvironment;const projectId='demo-securetrack';
before(async()=>{env=await initializeTestEnvironment({projectId,firestore:{host:'127.0.0.1',port:8080,rules:readFileSync('firestore.rules','utf8')}})});after(async()=>env.cleanup());
const user=(uid:string,role:string)=>({uid,email:uid+'@example.test',displayName:uid,photoDataUrl:'',role,status:'active',inventory_count:0,inventory_breakdown:{fmc920:0,fmc130:0,sim_cards:0},created_at:Timestamp.now()});
const shift=(tech='tech-a',job_type='new_installation')=>({job_reference:'ST00001',technician_id:tech,technician_name:tech,site_name:'Workshop',company_name:'Acme',customer_name:'Acme',contact_person:'Omar',customer_phone:'+971501234567',vehicle_number:'Dubai A 12345',vehicle_numbers:['Dubai A 12345'],unit_jobs:[{vehicle_number:'Dubai A 12345',job_type}],maps_url:'https://maps.app.goo.gl/example',job_type,unit_count:1,radius_m:150,grace_minutes:15,date:'2026-09-15',timezone:'Asia/Dubai',status:'assigned',scheduled_at:Timestamp.fromMillis(Date.now()+60000),window_start:Timestamp.fromMillis(Date.now()-60000),window_end:Timestamp.fromMillis(Date.now()+3600000),assigned_at:Timestamp.now(),created_at:Timestamp.now()});
beforeEach(async()=>{await env.clearFirestore();await env.withSecurityRulesDisabled(async c=>{const d=c.firestore();for(const[u,r]of[['tech-a','technician'],['tech-b','technician'],['admin','admin'],['manager','manager'],['accountant','accountant'],['hr','hr'],['it','it'],['master','master_admin']])await setDoc(doc(d,'users',u),user(u,r));for(const uid of ['tech-a','tech-b'])await setDoc(doc(d,'inventory_accounts',uid),{technician_id:uid,opening:{FMC920:5,FMC130:0,FMC125:0,'Jimi VL03':0,GT06:0,Ruptela:0,'SIM Etisalat':0,'SIM du':0,'SIM International':0,SIM:5},timestamp:Timestamp.now()});await setDoc(doc(d,'shifts','job-install'),shift());await setDoc(doc(d,'shifts','job-e2e'),{...shift(),job_reference:'ST00009',status:'in_progress',arrived_at:Timestamp.now()});await setDoc(doc(d,'shifts','job-sim'),shift('tech-a','sim_change'));await setDoc(doc(d,'shifts','job-remove'),shift('tech-a','device_removal'));await setDoc(doc(d,'shifts','job-mixed'),{...shift('tech-a','mixed'),unit_count:3,vehicle_numbers:['A','B','C'],unit_jobs:[{vehicle_number:'A',job_type:'device_change'},{vehicle_number:'B',job_type:'sim_change'},{vehicle_number:'C',job_type:'inspection'}]})})});
function db(uid='tech-a'){return env.authenticatedContext(uid,{email:uid+'@example.test'}).firestore()}
const completion=(id:string,type:string,model:string,imeis:string[],sims:string[])=>({technician_id:'tech-a',technician_name:'tech-a',shift_id:id,job_type:type,unit_count:1,device_model:model,device_imeis:imeis,sim_numbers:sims,sim_count:sims.length,...(sims.length?{sim_provider:'Etisalat'}:{}),customer_ref:'Acme',vehicle_ref:'',notes:'',timestamp:serverTimestamp(),completed_at:serverTimestamp(),completion_latitude:25.2,completion_longitude:55.3,completion_accuracy_m:8,captured_at:Timestamp.now()});
const move=(type:'installed'|'sim-used',model:string,quantity:number,sims:number)=>({technician_id:'tech-a',technician_name:'tech-a',type,device_model:model,quantity,sim_count:sims,...(sims?{sim_provider:'Etisalat'}:{}),timestamp:serverTimestamp(),captured_at:Timestamp.now(),notes:''});

test('only master administrator creates accounts and changes roles',async()=>{const created=user('new-user','technician');await assertFails(setDoc(doc(db('new-user'),'users','new-user'),created));await assertFails(setDoc(doc(db('admin'),'users','new-user'),created));await assertSucceeds(setDoc(doc(db('master'),'users','new-user'),{...created,created_at:serverTimestamp()}));await assertFails(updateDoc(doc(db('admin'),'users','tech-a'),{role:'manager'}));await assertSucceeds(updateDoc(doc(db('master'),'users','tech-a'),{role:'manager'}));await assertFails(updateDoc(doc(db('master'),'users','master'),{role:'technician'}))});
test('management and HR can read operations but technician data stays scoped',async()=>{await assertSucceeds(getDocs(collection(db('manager'),'shifts')));await assertSucceeds(getDocs(collection(db('hr'),'installations')));await assertSucceeds(getDocs(collection(db('it'),'users')));await assertFails(getDocs(collection(db(),'users')));await assertFails(getDoc(doc(db('tech-b'),'shifts','job-install')))});
test('technician can load only their inventory account using the dashboard query',async()=>{const own=query(collection(db(),'inventory_accounts'),where('technician_id','==','tech-a'));const other=query(collection(db(),'inventory_accounts'),where('technician_id','==','tech-b'));await assertSucceeds(getDocs(own));await assertFails(getDocs(other))});
test('admin assigns jobs while manager, IT and technician are read only',async()=>{await assertSucceeds(setDoc(doc(db('admin'),'shifts','assigned'),{...shift(),job_reference:'ST00002',assigned_at:serverTimestamp(),created_at:serverTimestamp()}));await assertFails(setDoc(doc(db('manager'),'shifts','manager-job'),{...shift(),job_reference:'ST00002',assigned_at:serverTimestamp(),created_at:serverTimestamp()}));await assertFails(setDoc(doc(db('it'),'shifts','it-job'),{...shift(),job_reference:'ST00002',assigned_at:serverTimestamp(),created_at:serverTimestamp()}));await assertFails(setDoc(doc(db(),'shifts','self-job'),{...shift(),job_reference:'ST00002',assigned_at:serverTimestamp(),created_at:serverTimestamp()}))});
test('admin creates a sequential SecureTrack reference in one transaction',async()=>{const d=db('admin');await assertSucceeds(runTransaction(d,async tx=>{const counter=doc(d,'counters','jobs');const current=await tx.get(counter);const next=(current.data()?.value||0)+1;tx.set(counter,{value:next,updated_at:serverTimestamp()});tx.set(doc(d,'shifts','assigned-counter'),{...shift(),job_reference:'ST'+String(next).padStart(5,'0'),assigned_at:serverTimestamp(),created_at:serverTimestamp()})}))});
test('new installation completion requires paired stock deduction',async()=>{const d=db();const batch=writeBatch(d);batch.set(doc(d,'inventory_logs','job-install'),move('installed','FMC920',1,1));batch.set(doc(d,'installations','job-install'),completion('job-install','new_installation','FMC920',['862476051161825'],['8997112212789413817']));await assertSucceeds(batch.commit());await assertFails(setDoc(doc(db(),'installations','unassigned'),completion('unassigned','new_installation','FMC920',['862476051161825'],['8997112212789413817'])))});
test('complete transaction writes inventory, completion and final status atomically',async()=>{const d=db();await assertSucceeds(runTransaction(d,async tx=>{const installRef=doc(d,'installations','job-e2e');const moveRef=doc(d,'inventory_logs','job-e2e');const shiftRef=doc(d,'shifts','job-e2e');await tx.get(installRef);await tx.get(moveRef);await tx.get(shiftRef);tx.set(moveRef,move('installed','FMC920',1,1));tx.set(installRef,completion('job-e2e','new_installation','FMC920',['862476051161826'],['8997112212789413819']));tx.update(shiftRef,{status:'completed',completed_at:serverTimestamp(),completion_latitude:25.2,completion_longitude:55.3,completion_accuracy_m:8})}))});
test('legacy assigned jobs without job type or unit count can still be completed',async()=>{await env.withSecurityRulesDisabled(async c=>{const d=c.firestore();const legacy=shift();delete (legacy as any).job_type;delete (legacy as any).unit_count;await setDoc(doc(d,'shifts','job-legacy'),legacy)});const d=db();const batch=writeBatch(d);batch.set(doc(d,'inventory_logs','job-legacy'),move('installed','FMC920',1,1));batch.set(doc(d,'installations','job-legacy'),completion('job-legacy','new_installation','FMC920',['862476051161825'],['8997112212789413817']));await assertSucceeds(batch.commit())});
test('SIM change deducts only SIM and removal records no movement',async()=>{let d=db();let batch=writeBatch(d);batch.set(doc(d,'inventory_logs','job-sim'),move('sim-used','',0,1));batch.set(doc(d,'installations','job-sim'),completion('job-sim','sim_change','',[],['8997112212789413817']));await assertSucceeds(batch.commit());await assertSucceeds(setDoc(doc(db(),'installations','job-remove'),completion('job-remove','device_removal','',[],[])))});
test('technician may check a missing completion before creating it',async()=>{await assertSucceeds(getDoc(doc(db(),'installations','job-install')))});
test('mixed vehicle work stores only the identifiers required per unit',async()=>{const d=db();const unit_records=[{vehicle_number:'A',job_type:'device_change',device_model:'FMC920',device_imei:'862476051161825'},{vehicle_number:'B',job_type:'sim_change',sim_number:'8997112212789413817'},{vehicle_number:'C',job_type:'inspection',inspection_action:'sim_change',sim_number:'8997112212789413818'}];const batch=writeBatch(d);batch.set(doc(d,'inventory_logs','job-mixed'),move('installed','FMC920',1,2));batch.set(doc(d,'installations','job-mixed'),{...completion('job-mixed','mixed','FMC920',['862476051161825'],['8997112212789413817','8997112212789413818']),unit_count:3,unit_records});await assertSucceeds(batch.commit())});
test('stock administrators may record audited inventory corrections',async()=>{const adjustment={technician_id:'tech-a',technician_name:'Tech A',type:'adjustment',device_model:'FMC920',quantity:0,sim_count:0,quantity_delta:-1,sim_delta:0,timestamp:serverTimestamp(),captured_at:serverTimestamp(),notes:'Physical count'};await assertSucceeds(setDoc(doc(db('accountant'),'inventory_logs','adjust-a'),adjustment));await assertFails(setDoc(doc(db('manager'),'inventory_logs','adjust-b'),adjustment))});
test('technician clock-in is server timed and visible to HR',async()=>{const session={technician_id:'tech-a',technician_name:'Tech A',date:'2026-09-22',timezone:'Asia/Dubai',status:'active',clock_in_at:serverTimestamp(),clock_in_latitude:25.2,clock_in_longitude:55.3,clock_in_accuracy_m:8};await assertSucceeds(setDoc(doc(db(),'work_sessions','tech-a_2026-09-22'),session));await assertSucceeds(getDocs(collection(db('hr'),'work_sessions')));await assertFails(setDoc(doc(db('tech-b'),'work_sessions','tech-a_2026-09-23'),{...session,date:'2026-09-23'}))});
test('only stock administrators and accountants issue stock',async()=>{const receipt={...move('installed','FMC920',2,2),type:'received'};await assertSucceeds(setDoc(doc(db('admin'),'inventory_logs','receipt-a'),receipt));await assertSucceeds(setDoc(doc(db('master'),'inventory_logs','receipt-m'),receipt));await assertSucceeds(setDoc(doc(db('accountant'),'inventory_logs','receipt-c'),receipt));await assertFails(setDoc(doc(db('manager'),'inventory_logs','receipt-x'),receipt));await assertFails(setDoc(doc(db(),'inventory_logs','receipt-t'),receipt))});
test('technician check-in and login GPS remain protected',async()=>{const log={technician_id:'tech-a',latitude:25.2,longitude:55.3,accuracy_m:10,timestamp:serverTimestamp()};await assertSucceeds(setDoc(doc(db(),'attendance_logs','job-install'),log));await assertSucceeds(setDoc(doc(db(),'login_logs','login-a'),log));await assertFails(setDoc(doc(db('tech-b'),'login_logs','spoof'),log));await assertFails(updateDoc(doc(db(),'attendance_logs','job-install'),{latitude:0}))});
