import assert from 'node:assert/strict';
import { confirmJobArrival } from '../src/lib/arrival';
import { carryForwardJobs } from '../src/lib/carryForward';
import test,{before,beforeEach,after}from'node:test';
import{readFileSync}from'node:fs';
import{initializeTestEnvironment,assertFails,assertSucceeds,RulesTestEnvironment}from'@firebase/rules-unit-testing';
import{collection,doc,getDoc,getDocs,query,runTransaction,serverTimestamp,setDoc,Timestamp,updateDoc,where,writeBatch}from'firebase/firestore';
let env:RulesTestEnvironment;const projectId='demo-securetrack';
before(async()=>{env=await initializeTestEnvironment({projectId,firestore:{host:'127.0.0.1',port:8080,rules:readFileSync('firestore.rules','utf8')}})});after(async()=>env.cleanup());
const user=(uid:string,role:string)=>({uid,email:uid+'@example.test',displayName:uid,photoDataUrl:'',role,status:'active',inventory_count:0,inventory_breakdown:{fmc920:0,fmc130:0,sim_cards:0},created_at:Timestamp.now()});
const shift=(tech='tech-a',job_type='new_installation')=>({job_reference:'ST00001',technician_id:tech,technician_name:tech,site_name:'Workshop',company_name:'Acme',customer_name:'Acme',contact_person:'Omar',customer_phone:'+971501234567',vehicle_number:'Dubai A 12345',vehicle_numbers:['Dubai A 12345'],unit_jobs:[{vehicle_number:'Dubai A 12345',job_type}],maps_url:'https://maps.app.goo.gl/example',job_type,unit_count:1,radius_m:150,grace_minutes:15,date:'2026-09-15',timezone:'Asia/Dubai',status:'assigned',scheduled_at:Timestamp.fromMillis(Date.now()+60000),window_start:Timestamp.fromMillis(Date.now()-60000),window_end:Timestamp.fromMillis(Date.now()+3600000),assigned_at:Timestamp.now(),created_at:Timestamp.now()});
beforeEach(async()=>{await env.clearFirestore();await env.withSecurityRulesDisabled(async c=>{const d=c.firestore();for(const[u,r]of[['tech-a','technician'],['tech-b','technician'],['admin','admin'],['manager','manager'],['accountant','accountant'],['hr','hr'],['it','it'],['master','master_admin']])await setDoc(doc(d,'users',u),user(u,r));for(const uid of ['tech-a','tech-b'])await setDoc(doc(d,'inventory_accounts',uid),{technician_id:uid,opening:{FMC920:5,FMC130:0,FMC125:0,'Jimi VL03':0,GT06:0,Ruptela:0,'SIM Etisalat':0,'SIM du':0,'SIM International':0,SIM:5},timestamp:Timestamp.now()});await setDoc(doc(d,'shifts','job-install'),shift());await setDoc(doc(d,'shifts','job-e2e'),{...shift(),job_reference:'ST00009',status:'in_progress',arrived_at:Timestamp.now()});await setDoc(doc(d,'shifts','job-sim'),shift('tech-a','sim_change'));await setDoc(doc(d,'shifts','job-remove'),shift('tech-a','device_removal'));await setDoc(doc(d,'shifts','job-mixed'),{...shift('tech-a','mixed'),unit_count:3,vehicle_numbers:['A','B','C'],unit_jobs:[{vehicle_number:'A',job_type:'device_change'},{vehicle_number:'B',job_type:'sim_change'},{vehicle_number:'C',job_type:'inspection'}]})})});
function db(uid='tech-a'){return env.authenticatedContext(uid,{email:uid+'@example.test'}).firestore()}
const completion=(id:string,type:string,model:string,imeis:string[],sims:string[])=>({technician_id:'tech-a',technician_name:'tech-a',shift_id:id,job_type:type,unit_count:1,unit_index:0,progress_completed:1,progress_total:1,unit_records:[{vehicle_number:'Dubai A 12345',job_type:type,...(model?{device_model:model}:{}),...(imeis[0]?{device_imei:imeis[0]}:{}),...(sims[0]?{sim_number:sims[0]}:{})}],device_model:model,device_imeis:imeis,sim_numbers:sims,sim_count:sims.length,...(sims.length?{sim_provider:'Etisalat'}:{}),customer_ref:'Acme',vehicle_ref:'Dubai A 12345',notes:'',completed_by_uid:'tech-a',completed_by_name:'tech-a',timestamp:serverTimestamp(),completed_at:serverTimestamp(),completion_latitude:25.2,completion_longitude:55.3,completion_accuracy_m:8,captured_at:Timestamp.now()});
const move=(type:'installed'|'sim-used',model:string,quantity:number,sims:number)=>({technician_id:'tech-a',technician_name:'tech-a',type,device_model:model,quantity,sim_count:sims,...(sims?{sim_provider:'Etisalat'}:{}),timestamp:serverTimestamp(),captured_at:Timestamp.now(),notes:''});
const adminCompletion=(id:string,type='new_installation',actor='admin',role='admin')=>({technician_id:'tech-a',technician_name:'tech-a',shift_id:id,job_type:type,unit_count:1,device_model:'',device_imeis:[],sim_numbers:[],sim_count:0,customer_ref:'Acme',vehicle_ref:'Dubai A 12345',notes:'',completion_source:'admin_override',completed_by_uid:actor,completed_by_name:actor,completed_by_role:role,completion_reason:'Technician completed the work but the client form failed.',timestamp:serverTimestamp(),completed_at:serverTimestamp(),captured_at:serverTimestamp()});

test('only master administrator creates accounts and changes roles',async()=>{const created=user('new-user','technician');await assertFails(setDoc(doc(db('new-user'),'users','new-user'),created));await assertFails(setDoc(doc(db('admin'),'users','new-user'),created));await assertSucceeds(setDoc(doc(db('master'),'users','new-user'),{...created,created_at:serverTimestamp()}));await assertFails(updateDoc(doc(db('admin'),'users','tech-a'),{role:'manager'}));await assertSucceeds(updateDoc(doc(db('master'),'users','tech-a'),{role:'manager'}));await assertFails(updateDoc(doc(db('master'),'users','master'),{role:'technician'}))});
test('management and HR can read operations but technician data stays scoped',async()=>{await assertSucceeds(getDocs(collection(db('manager'),'shifts')));await assertSucceeds(getDocs(collection(db('hr'),'installations')));await assertSucceeds(getDocs(collection(db('it'),'users')));await assertFails(getDocs(collection(db(),'users')));await assertFails(getDoc(doc(db('tech-b'),'shifts','job-install')))});
test('technician can load only their inventory account using the dashboard query',async()=>{const own=query(collection(db(),'inventory_accounts'),where('technician_id','==','tech-a'));const other=query(collection(db(),'inventory_accounts'),where('technician_id','==','tech-b'));await assertSucceeds(getDocs(own));await assertFails(getDocs(other))});
test('admin assigns jobs while manager, IT and technician are read only',async()=>{await assertSucceeds(setDoc(doc(db('admin'),'shifts','assigned'),{...shift(),job_reference:'ST00002',assigned_at:serverTimestamp(),created_at:serverTimestamp()}));await assertFails(setDoc(doc(db('manager'),'shifts','manager-job'),{...shift(),job_reference:'ST00002',assigned_at:serverTimestamp(),created_at:serverTimestamp()}));await assertFails(setDoc(doc(db('it'),'shifts','it-job'),{...shift(),job_reference:'ST00002',assigned_at:serverTimestamp(),created_at:serverTimestamp()}));await assertFails(setDoc(doc(db(),'shifts','self-job'),{...shift(),job_reference:'ST00002',assigned_at:serverTimestamp(),created_at:serverTimestamp()}))});
test('admin can save an intentionally incomplete job draft',async()=>{const draft={...shift(),job_reference:'ST00003',status:'draft',technician_id:'',technician_name:'',site_name:'',company_name:'',customer_name:'',contact_person:'',customer_phone:'',vehicle_number:'',vehicle_numbers:[''],unit_jobs:[{vehicle_number:'',job_type:'new_installation'}],maps_url:'',assigned_at:null,created_at:serverTimestamp()};await assertSucceeds(setDoc(doc(db('admin'),'shifts','incomplete-draft'),draft));await assertFails(setDoc(doc(db('manager'),'shifts','manager-draft'),{...draft,created_at:serverTimestamp()}))});
test('admin can correct job details after arrival but not after completion',async()=>{const arrived={...shift(),job_reference:'ST00010',status:'in_progress',arrived_at:Timestamp.now(),version:1};await env.withSecurityRulesDisabled(async c=>setDoc(doc(c.firestore(),'shifts','arrived-edit'),arrived));await assertSucceeds(updateDoc(doc(db('admin'),'shifts','arrived-edit'),{company_name:'Correct Company',customer_name:'Correct Company',version:2,updated_at:serverTimestamp(),updated_by_uid:'admin',updated_by_name:'admin'}));await env.withSecurityRulesDisabled(async c=>updateDoc(doc(c.firestore(),'shifts','arrived-edit'),{status:'completed',completed_at:Timestamp.now()}));await assertFails(updateDoc(doc(db('admin'),'shifts','arrived-edit'),{company_name:'Too Late',customer_name:'Too Late',version:3,updated_at:serverTimestamp(),updated_by_uid:'admin',updated_by_name:'admin'}))});
test('admin creates a sequential SecureTrack reference in one transaction',async()=>{const d=db('admin');await assertSucceeds(runTransaction(d,async tx=>{const counter=doc(d,'counters','jobs');const current=await tx.get(counter);const next=(current.data()?.value||0)+1;tx.set(counter,{value:next,updated_at:serverTimestamp()});tx.set(doc(d,'shifts','assigned-counter'),{...shift(),job_reference:'ST'+String(next).padStart(5,'0'),assigned_at:serverTimestamp(),created_at:serverTimestamp()})}))});
test('new installation completion requires paired stock deduction',async()=>{const d=db();const batch=writeBatch(d);batch.set(doc(d,'inventory_logs','job-install'),move('installed','FMC920',1,1));batch.set(doc(d,'installations','job-install'),completion('job-install','new_installation','FMC920',['862476051161825'],['8997112212789413817']));await assertSucceeds(batch.commit());await assertFails(setDoc(doc(db(),'installations','unassigned'),completion('unassigned','new_installation','FMC920',['862476051161825'],['8997112212789413817'])))});
test('complete transaction writes inventory, completion and final status atomically',async()=>{const d=db();await assertSucceeds(runTransaction(d,async tx=>{const installRef=doc(d,'installations','job-e2e');const moveRef=doc(d,'inventory_logs','job-e2e');const shiftRef=doc(d,'shifts','job-e2e');await tx.get(installRef);await tx.get(moveRef);await tx.get(shiftRef);tx.set(moveRef,move('installed','FMC920',1,1));tx.set(installRef,completion('job-e2e','new_installation','FMC920',['862476051161826'],['8997112212789413819']));tx.update(shiftRef,{status:'completed',completed_units:1,last_vehicle_completed_at:serverTimestamp(),completed_at:serverTimestamp(),completion_latitude:25.2,completion_longitude:55.3,completion_accuracy_m:8})}))});
test('administrator may complete a failed client job without scans or inventory deduction',async()=>{let d=db('admin');let batch=writeBatch(d);batch.set(doc(d,'installations','job-install'),adminCompletion('job-install'));batch.update(doc(d,'shifts','job-install'),{status:'completed',completed_at:serverTimestamp()});await assertSucceeds(batch.commit());d=db('manager');batch=writeBatch(d);batch.set(doc(d,'installations','job-sim'),adminCompletion('job-sim','sim_change','manager','manager'));batch.update(doc(d,'shifts','job-sim'),{status:'completed',completed_at:serverTimestamp()});await assertFails(batch.commit());await assertFails(setDoc(doc(db(),'installations','job-remove'),adminCompletion('job-remove','device_removal','tech-a','technician')))});
test('master administrator can fully remove a completed technician job',async()=>{const d=db('master');const batch=writeBatch(d);batch.set(doc(d,'installations','job-install'),adminCompletion('job-install','new_installation','master','master_admin'));batch.delete(doc(d,'shifts','job-install'));await assertSucceeds(batch.commit())});
test('legacy assigned jobs without job type or unit count can still be completed',async()=>{await env.withSecurityRulesDisabled(async c=>{const d=c.firestore();const legacy=shift();delete (legacy as any).job_type;delete (legacy as any).unit_count;await setDoc(doc(d,'shifts','job-legacy'),legacy)});const d=db();const batch=writeBatch(d);batch.set(doc(d,'inventory_logs','job-legacy'),move('installed','FMC920',1,1));batch.set(doc(d,'installations','job-legacy'),completion('job-legacy','new_installation','FMC920',['862476051161825'],['8997112212789413817']));await assertSucceeds(batch.commit())});
test('SIM change deducts only SIM and removal records no movement',async()=>{let d=db();let batch=writeBatch(d);batch.set(doc(d,'inventory_logs','job-sim'),move('sim-used','',0,1));batch.set(doc(d,'installations','job-sim'),completion('job-sim','sim_change','',[],['8997112212789413817']));await assertSucceeds(batch.commit());await assertSucceeds(setDoc(doc(db(),'installations','job-remove'),completion('job-remove','device_removal','',['862476051161827'],[])))});
test('technician may check a missing completion before creating it',async()=>{await assertSucceeds(getDoc(doc(db(),'installations','job-install')))});
test('mixed vehicle work stores each vehicle completion independently',async()=>{const d=db();const batch=writeBatch(d),record={...completion('job-mixed','device_change','FMC920',['862476051161825'],[]),unit_index:0,progress_completed:1,progress_total:3,vehicle_ref:'A',unit_records:[{vehicle_number:'A',job_type:'device_change',device_model:'FMC920',device_imei:'862476051161825'}]};batch.set(doc(d,'inventory_logs','job-mixed'),move('installed','FMC920',1,0));batch.set(doc(d,'installations','job-mixed'),record);await assertSucceeds(batch.commit())});
test('stock administrators may record audited inventory corrections',async()=>{const adjustment={technician_id:'tech-a',technician_name:'Tech A',type:'adjustment',device_model:'FMC920',quantity:0,sim_count:0,quantity_delta:-1,sim_delta:0,timestamp:serverTimestamp(),captured_at:serverTimestamp(),notes:'Physical count'};await assertSucceeds(setDoc(doc(db('accountant'),'inventory_logs','adjust-a'),adjustment));await assertFails(setDoc(doc(db('manager'),'inventory_logs','adjust-b'),adjustment))});
test('technician clock-in is server timed and visible to HR',async()=>{const session={technician_id:'tech-a',technician_name:'Tech A',date:'2026-09-22',timezone:'Asia/Dubai',status:'active',clock_in_at:serverTimestamp(),clock_in_latitude:25.2,clock_in_longitude:55.3,clock_in_accuracy_m:8};await assertSucceeds(setDoc(doc(db(),'work_sessions','tech-a_2026-09-22'),session));await assertSucceeds(getDocs(collection(db('hr'),'work_sessions')));await assertFails(setDoc(doc(db('tech-b'),'work_sessions','tech-a_2026-09-23'),{...session,date:'2026-09-23'}))});
test('only stock administrators and accountants issue stock',async()=>{const receipt={...move('installed','FMC920',2,2),type:'received'};await assertSucceeds(setDoc(doc(db('admin'),'inventory_logs','receipt-a'),receipt));await assertSucceeds(setDoc(doc(db('master'),'inventory_logs','receipt-m'),receipt));await assertSucceeds(setDoc(doc(db('accountant'),'inventory_logs','receipt-c'),receipt));await assertFails(setDoc(doc(db('manager'),'inventory_logs','receipt-x'),receipt));await assertFails(setDoc(doc(db(),'inventory_logs','receipt-t'),receipt))});
test('technician check-in and login GPS remain protected',async()=>{const log={technician_id:'tech-a',latitude:25.2,longitude:55.3,accuracy_m:10,timestamp:serverTimestamp()};await assertSucceeds(setDoc(doc(db(),'attendance_logs','job-install'),log));await assertSucceeds(setDoc(doc(db(),'login_logs','login-a'),log));await assertFails(setDoc(doc(db('tech-b'),'login_logs','spoof'),log));await assertFails(updateDoc(doc(db(),'attendance_logs','job-install'),{latitude:0}))});
test('technician arrival atomically records GPS and moves the assigned job in progress',async()=>{const d=db(),batch=writeBatch(d);batch.set(doc(d,'attendance_logs','job-install'),{technician_id:'tech-a',latitude:25.2,longitude:55.3,accuracy_m:10,timestamp:serverTimestamp()});batch.update(doc(d,'shifts','job-install'),{status:'in_progress',arrived_at:serverTimestamp()});await assertSucceeds(batch.commit());const [arrival,job]=await Promise.all([getDoc(doc(d,'attendance_logs','job-install')),getDoc(doc(d,'shifts','job-install'))]);if(!arrival.exists()||job.data()?.status!=='in_progress')throw new Error('Arrival did not persist atomically.');await env.withSecurityRulesDisabled(async context=>setDoc(doc(context.firestore(),'shifts','job-second-tech'),{...shift('tech-b'),job_reference:'ST00011'}));const other=db('tech-b'),otherBatch=writeBatch(other);otherBatch.set(doc(other,'attendance_logs','job-second-tech'),{technician_id:'tech-b',latitude:25.3,longitude:55.4,accuracy_m:12,timestamp:serverTimestamp()});otherBatch.update(doc(other,'shifts','job-second-tech'),{status:'in_progress',arrived_at:serverTimestamp()});await assertSucceeds(otherBatch.commit())});
test('frontend error logs are write-only for staff and readable only by administrators',async()=>{const entry={severity:'error',message:'Example failure',stack:'stack',module:'test',user_uid:'tech-a',request_url:'https://example.test/app',context:{job_id:'ST00001'},created_at:serverTimestamp()};await assertSucceeds(setDoc(doc(db(),'error_logs','tech-error'),entry));await assertFails(getDoc(doc(db(),'error_logs','tech-error')));await assertSucceeds(getDoc(doc(db('admin'),'error_logs','tech-error')));await assertFails(setDoc(doc(db('tech-b'),'error_logs','spoofed'),{...entry,user_uid:'tech-a'}));await assertFails(updateDoc(doc(db('admin'),'error_logs','tech-error'),{message:'changed'}))});
test('complete audit is append only and visible only to master administrator',async()=>{const event={actor_uid:'tech-a',actor_name:'Tech A',actor_email:'tech-a@example.test',actor_role:'technician',action:'COMPLETED',module:'Jobs',record_id:'job-install',company:'Acme',vehicle:'Dubai A 12345',chassis:'',imei:'862476051161825',sim:'8997112212789413817',job_id:'ST00001',certificate_number:'',reason:'',changes:{},deleted_record:false,search_tokens:['acme','dubai','st00001'],created_at:serverTimestamp()};await assertSucceeds(setDoc(doc(db(),'audit_events','event-a'),event));await assertFails(getDoc(doc(db('admin'),'audit_events','event-a')));await assertSucceeds(getDoc(doc(db('master'),'audit_events','event-a')));await assertFails(updateDoc(doc(db('master'),'audit_events','event-a'),{reason:'changed'}))});
test('renewal imports upsert one deterministic record and remain read only to managers',async()=>{const record={identity:'CHASSIS:VIN123',company_name:'ABC RENTALS',vehicle_number:'Z/12345',chassis_number:'VIN123',imei:'123',sim_number:'456',start_date:'2026-01-01',expiry_date:'2027-01-01',status:'Active',contact_number:'971500000000',email:'a@example.test',device_type:'FMC920',lifecycle:'Upcoming',is_deleted:false,updated_by_uid:'accountant',updated_by_name:'accountant',updated_at:serverTimestamp(),created_at:serverTimestamp(),created_by_uid:'accountant',created_by_name:'accountant'};await assertSucceeds(setDoc(doc(db('accountant'),'renewals','renewal_fixed'),record));await assertSucceeds(updateDoc(doc(db('accountant'),'renewals','renewal_fixed'),{expiry_date:'2027-02-01',updated_at:serverTimestamp()}));await assertSucceeds(getDoc(doc(db('manager'),'renewals','renewal_fixed')));await assertFails(updateDoc(doc(db('manager'),'renewals','renewal_fixed'),{expiry_date:'2028-01-01'}))});
test('operations notification read state is stored per user',async()=>{const note={type:'vehicle_completed',company:'Acme',vehicle:'Dubai A 12345',job_id:'ST00001',imei:'123',sim:'456',technician_name:'tech-a',actor_uid:'tech-a',message:'Vehicle 1 of 2 completed',progress:'1 of 2',recipient_roles:['master_admin','admin'],target_section:'jobs',read_by:[],created_at:serverTimestamp()};await assertSucceeds(setDoc(doc(db(),'operational_notifications','note-a'),note));await assertSucceeds(updateDoc(doc(db('admin'),'operational_notifications','note-a'),{read_by:['admin']}));const snap=await assertSucceeds(getDoc(doc(db('master'),'operational_notifications','note-a')));if(snap.data()?.read_by.includes('master'))throw new Error('Master notification was incorrectly marked read.')});
test('technician live stock and schedule locks are scoped to authorized users',async()=>{const stock={technician_id:'tech-a',balance:{FMC920:1},updated_at:serverTimestamp()};await assertSucceeds(setDoc(doc(db(),'technician_live_stock','tech-a'),stock));await assertFails(setDoc(doc(db('tech-b'),'technician_live_stock','tech-a'),stock));await assertSucceeds(setDoc(doc(db('admin'),'schedule_locks','tech-a_2026-09-30'),{technician_id:'tech-a',date:'2026-09-30',entries:{},updated_at:serverTimestamp()}));await assertFails(setDoc(doc(db('manager'),'schedule_locks','tech-a_2026-10-01'),{technician_id:'tech-a',date:'2026-10-01',entries:{},updated_at:serverTimestamp()}))});

const gps={latitude:25.2,longitude:55.3,accuracy_m:10};
test('draft must be scheduled before the actual arrival handler can save, and retries preserve GPS/time',async()=>{
 const id='draft-arrival',d=db();
 await env.withSecurityRulesDisabled(async c=>setDoc(doc(c.firestore(),'shifts',id),{...shift(),status:'draft',version:1,duration_minutes:60,expected_end_at:Timestamp.fromMillis(Date.now()+3660000)}));
 await assert.rejects(confirmJobArrival(db() as any,'tech-a',id,gps),/draft/);
 const illegal=writeBatch(d);illegal.set(doc(d,'attendance_logs',id),{technician_id:'tech-a',...gps,timestamp:serverTimestamp()});illegal.update(doc(d,'shifts',id),{status:'in_progress',arrived_at:serverTimestamp()});await assertFails(illegal.commit());
 await assertFails(setDoc(doc(db(),'attendance_logs',id),{technician_id:'tech-a',...gps,timestamp:serverTimestamp()}));
 assert.equal((await getDoc(doc(db(),'attendance_logs',id))).exists(),false);
 await assertSucceeds(updateDoc(doc(db('admin'),'shifts',id),{status:'assigned',assigned_at:serverTimestamp(),version:2,updated_at:serverTimestamp(),updated_by_uid:'admin',updated_by_name:'admin'}));
 await confirmJobArrival(db() as any,'tech-a',id,gps);
 const before=(await getDoc(doc(db(),'attendance_logs',id))).data()!;
 await confirmJobArrival(db() as any,'tech-a',id,{...gps,latitude:26});
 const after=(await getDoc(doc(db(),'attendance_logs',id))).data()!;
 assert.equal(after.timestamp.toMillis(),before.timestamp.toMillis());assert.equal(after.latitude,before.latitude);
 assert.equal((await getDoc(doc(db(),'shifts',id))).data()?.status,'in_progress');
});
test('arrival handler is safe for concurrent retries and the second technician',async()=>{
 const outcomes=await Promise.allSettled([confirmJobArrival(db() as any,'tech-a','job-install',gps),confirmJobArrival(db() as any,'tech-a','job-install',gps)]);for(const result of outcomes){if(result.status==='rejected')throw result.reason;}
 await assertFails(confirmJobArrival(db('tech-b') as any,'tech-b','job-sim',gps));
 await env.withSecurityRulesDisabled(async c=>setDoc(doc(c.firestore(),'shifts','second-arrival'),shift('tech-b')));
 await confirmJobArrival(db('tech-b') as any,'tech-b','second-arrival',gps);
 assert.equal((await getDoc(doc(db('tech-b'),'attendance_logs','second-arrival'))).data()?.technician_id,'tech-b');
});
test('arrival rejects cancelled, completed, deleted and out-of-window jobs',async()=>{
 for(const status of ['cancelled','completed']){
  await env.withSecurityRulesDisabled(async c=>setDoc(doc(c.firestore(),'shifts',status),{...shift(),status}));
  await assert.rejects(confirmJobArrival(db() as any,'tech-a',status,gps),/no longer open/);
  await assertFails(setDoc(doc(db(),'attendance_logs',status),{technician_id:'tech-a',...gps,timestamp:serverTimestamp()}));
 }
 await env.withSecurityRulesDisabled(async c=>{await setDoc(doc(c.firestore(),'shifts','deleted-arrival'),{...shift(),is_deleted:true});await setDoc(doc(c.firestore(),'shifts','future-arrival'),{...shift(),window_start:Timestamp.fromMillis(Date.now()+3600000),window_end:Timestamp.fromMillis(Date.now()+7200000)})});
 await assert.rejects(confirmJobArrival(db() as any,'tech-a','deleted-arrival',gps),/no longer open/);
 await assertFails(confirmJobArrival(db() as any,'tech-a','future-arrival',gps));
});

test('carry-forward ignores a completed job reservation and preserves its recorded work',async()=>{
 const target:any={...shift(),id:'carry-a',date:'2026-09-30',scheduled_at:Timestamp.fromDate(new Date('2026-09-30T05:00:00Z')),duration_minutes:60,job_reference:'ST00070'};
 const completed={...shift(),date:'2026-10-01',status:'completed',completed_units:1,completed_at:Timestamp.fromDate(new Date('2026-10-01T06:00:00Z')),job_reference:'ST00063'};
 await env.withSecurityRulesDisabled(async c=>{const d=c.firestore();await setDoc(doc(d,'shifts','carry-a'),target);await setDoc(doc(d,'shifts','stale'),completed);await setDoc(doc(d,'schedule_locks','tech-a_2026-10-01'),{technician_id:'tech-a',date:'2026-10-01',entries:{stale:{job_reference:'ST00063',start_at:'2026-10-01T05:00:00Z',end_at:'2026-10-01T06:00:00Z'}},updated_at:Timestamp.now()})});
 const result=await carryForwardJobs(db('admin') as any,[target],'2026-10-01',user('admin','admin') as any,()=>{});
 assert.equal(result.moved,1);assert.deepEqual(result.conflicts,[]);
 assert.equal((await getDoc(doc(db('admin'),'shifts','carry-a'))).data()?.date,'2026-10-01');
 assert.equal((await getDoc(doc(db('admin'),'shifts','stale'))).data()?.completed_at.toMillis(),completed.completed_at.toMillis());
 const entries=(await getDoc(doc(db('admin'),'schedule_locks','tech-a_2026-10-01'))).data()?.entries;
 assert.ok(entries['carry-a']);assert.equal(entries.stale,undefined);
 assert.ok((await getDoc(doc(db('admin'),'job_schedule_history','carry-a_2026-10-01'))).exists());
 const retry=await carryForwardJobs(db('admin') as any,[target],'2026-10-01',user('admin','admin') as any,()=>{});assert.equal(retry.moved,0);
});

test('a genuine carry-forward conflict leaves that job pending and continues other jobs',async()=>{
 const first:any={...shift(),id:'blocked',date:'2026-09-30',scheduled_at:Timestamp.fromDate(new Date('2026-09-30T05:00:00Z')),duration_minutes:60,job_reference:'ST00070'};
 const second:any={...first,id:'available',scheduled_at:Timestamp.fromDate(new Date('2026-09-30T07:00:00Z')),job_reference:'ST00071'};
 await env.withSecurityRulesDisabled(async c=>{const d=c.firestore();await setDoc(doc(d,'shifts','blocked'),first);await setDoc(doc(d,'shifts','available'),second);await setDoc(doc(d,'shifts','active'),{...shift(),date:'2026-10-01',job_reference:'ST00063'});await setDoc(doc(d,'schedule_locks','tech-a_2026-10-01'),{technician_id:'tech-a',date:'2026-10-01',entries:{active:{job_reference:'ST00063',start_at:'2026-10-01T05:00:00Z',end_at:'2026-10-01T06:00:00Z'}},updated_at:Timestamp.now()})});
 const result=await carryForwardJobs(db('admin') as any,[first,second],'2026-10-01',user('admin','admin') as any,()=>{});
 assert.equal(result.moved,1);assert.deepEqual(result.conflicts,[{job:'ST00070',conflictingJob:'ST00063',date:'2026-10-01'}]);
 assert.equal((await getDoc(doc(db('admin'),'shifts','blocked'))).data()?.date,'2026-09-30');
 assert.equal((await getDoc(doc(db('admin'),'shifts','available'))).data()?.date,'2026-10-01');
});

test('carry-forward excludes drafts, cancelled/deleted jobs and fresh completion despite stale input',async()=>{
 const inputs:any[]=[];
 await env.withSecurityRulesDisabled(async c=>{for(const status of ['draft','cancelled','completed','deleted','units-finished']){const input:any={...shift(),id:status,date:'2026-09-30',scheduled_at:Timestamp.fromDate(new Date('2026-09-30T05:00:00Z'))};inputs.push(input);await setDoc(doc(c.firestore(),'shifts',status),{...input,status:['deleted','units-finished'].includes(status)?'assigned':status,is_deleted:status==='deleted',completed_units:status==='units-finished'?1:0})}});
 const result=await carryForwardJobs(db('admin') as any,inputs,'2026-10-01',user('admin','admin') as any,()=>{});
 assert.deepEqual(result,{moved:0,conflicts:[]});
});
