import { useEffect } from 'react';
import { Attendance, InventoryAccount, Movement, StockAlertSettings, Technician, WorkSession } from '../types';
import { dayKey, stockAt, TIME_ZONE } from '../lib/domain';
import { notificationSeen, rememberNotification, sendAppNotification } from '../lib/notifications';

function timeMinutes(value:string){const [hour,minute]=value.split(':').map(Number);return hour*60+minute}
function dubaiMinutes(now:number){const parts=new Intl.DateTimeFormat('en-GB',{timeZone:TIME_ZONE,hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(new Date(now));return Number(parts.find(p=>p.type==='hour')?.value||0)*60+Number(parts.find(p=>p.type==='minute')?.value||0)}
export function useOperationsAlerts(profile:Technician|null,technicians:Technician[],accounts:InventoryAccount[],movements:Movement[],sessions:WorkSession[],settings:StockAlertSettings,now:number){useEffect(()=>{if(!profile)return;const role=profile.role;const canSeeAll=['master_admin','owner','admin','accountant','hr'].includes(role);const targets=role==='technician'?[profile]:canSeeAll?technicians.filter(item=>item.role==='technician'):[];for(const tech of targets){const stock=stockAt(accounts.find(item=>item.technician_id===tech.uid),movements.filter(item=>item.technician_id===tech.uid));if(!stock)continue;for(const[key,value]of Object.entries(stock)){if(value>settings.threshold)continue;const id=`low-stock:${tech.uid}:${key}:${settings.threshold}`;if(notificationSeen(profile.uid,id))continue;void sendAppNotification('Low stock alert',`${tech.displayName||tech.email}: ${key} has ${value} remaining (threshold ${settings.threshold}).`,id).then(sent=>{if(sent)rememberNotification(profile.uid,id)})}}
 if(role==='hr'){const today=dayKey(new Date(now));const minutes=dubaiMinutes(now);for(const tech of technicians.filter(item=>item.role==='technician')){const session=sessions.find(item=>item.technician_id===tech.uid&&item.date===today);if(minutes>=timeMinutes(settings.clock_in_time)+settings.late_grace_minutes&&minutes<timeMinutes(settings.clock_out_time)&&!session){const id=`hr-late-in:${tech.uid}:${today}`;if(!notificationSeen(profile.uid,id))void sendAppNotification('Late clock-in',`${tech.displayName||tech.email} has not clocked in for the 09:00 workday.`,id).then(sent=>{if(sent)rememberNotification(profile.uid,id)})}if(minutes>=timeMinutes(settings.clock_out_time)+settings.late_grace_minutes&&session?.status==='active'){const id=`hr-late-out:${tech.uid}:${today}`;if(!notificationSeen(profile.uid,id))void sendAppNotification('Late clock-out',`${tech.displayName||tech.email} has not clocked out after 18:00.`,id).then(sent=>{if(sent)rememberNotification(profile.uid,id)})}}}},[profile,technicians,accounts,movements,sessions,settings,now])}
