import { FormEvent, useState } from 'react';
import { sendPasswordResetEmail } from 'firebase/auth';
import { Camera, Check, KeyRound, Mail, Save, Trash2, UserPlus, Users } from 'lucide-react';
import { changeProfilePhoto, changeRole, createManagedAccount, removeManagedAccount } from '../lib/data';
import { auth } from '../lib/firebase';
import { prepareProfilePhoto } from '../lib/photo';
import { ROLES, Role, Technician, roleLabel } from '../types';

export function AccountManager({users,currentUid}:{users:Technician[];currentUid:string}){
 const [open,setOpen]=useState(false);const [name,setName]=useState('');const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [role,setRole]=useState<Role>('technician');const [drafts,setDrafts]=useState<Record<string,Role>>({});const [working,setWorking]=useState('');const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [notice,setNotice]=useState('');
 async function submit(e:FormEvent){e.preventDefault();setError('');setNotice('');setBusy(true);try{await createManagedAccount({displayName:name,email,password,role});setNotice(`${name} can now sign in as ${roleLabel(role).toLowerCase()}.`);setName('');setEmail('');setPassword('');setRole('technician');setOpen(false)}catch(e:any){setError(e.code==='auth/email-already-in-use'?'That email already has an account.':e.message)}finally{setBusy(false)}}
 async function saveRole(user:Technician){const next=drafts[user.uid]||user.role;if(next===user.role)return;setWorking(user.uid);setError('');try{await changeRole(user.uid,next);setNotice(`${user.displayName||user.email} is now ${roleLabel(next).toLowerCase()}.`)}catch(e:any){setError(e.message)}finally{setWorking('')}}
 async function resetPassword(user:Technician){setWorking(user.uid);setError('');try{await sendPasswordResetEmail(auth,user.email);setNotice(`Password reset link sent to ${user.email}.`)}catch(e:any){setError(e.message)}finally{setWorking('')}}
 async function savePhoto(user:Technician,file?:File){if(!file)return;setWorking(user.uid);setError('');try{const photo=await prepareProfilePhoto(file);await changeProfilePhoto(user.uid,photo);setNotice(`Profile photo updated for ${user.displayName||user.email}.`)}catch(e:any){setError(e.message)}finally{setWorking('')}}
 async function removeUser(user:Technician){if(!window.confirm(`Permanently delete ${user.displayName||user.email} and all SecureTrack data?\n\nThis removes assigned jobs, attendance, login locations, installations and inventory history. This cannot be undone.`))return;setWorking(user.uid);setError('');setNotice('');try{await removeManagedAccount(user.uid);setNotice(`${user.displayName||user.email} and all SecureTrack data were deleted.`)}catch(e:any){setError(e.message)}finally{setWorking('')}}
 return <section className="panel account-manager"><div className="section-label"><div className="section-title compact"><div className="icon-box"><Users/></div><div><h2>People & access</h2><p>Create accounts, edit roles, reset passwords, or remove user access.</p></div></div><button className="primary" onClick={()=>setOpen(!open)}><UserPlus size={17}/>{open?'Close':'Create account'}</button></div>
 {error&&<div className="notice error" role="alert">{error}</div>}{notice&&<div className="notice success"><Check size={16}/>{notice}</div>}
 {open&&<form className="account-form glass-inset" onSubmit={submit}><div className="form-row"><label>Full name<input required maxLength={160} value={name} onChange={e=>setName(e.target.value)} placeholder="Technician or staff name"/></label><label>Work email<input required type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="name@company.com"/></label></div><div className="form-row"><label>Temporary password<input required minLength={8} value={password} onChange={e=>setPassword(e.target.value)} placeholder="Minimum 8 characters"/><small>Share this directly with the team member.</small></label><label>Role<select value={role} onChange={e=>setRole(e.target.value as Role)}>{ROLES.filter(r=>r!=='master_admin').map(r=><option value={r} key={r}>{roleLabel(r)}</option>)}</select></label></div><button className="primary" disabled={busy}><KeyRound size={16}/>{busy?'Creating account…':'Create secure account'}</button></form>}
 <div className="people-list">{users.map(user=><article className="person-row" key={user.uid}><div className="avatar profile-avatar">{user.photoDataUrl?<img src={user.photoDataUrl} alt=""/>:(user.displayName||user.email).slice(0,2).toUpperCase()}</div><div className="grow"><strong>{user.displayName||user.email}</strong><span>{user.email}</span></div><span className={'status-dot '+(user.status==='deactivated'?'off':'')}>{user.status==='deactivated'?'removed':user.status||'active'}</span><div className="person-actions">{user.uid===currentUid?<span className="role-pill">{roleLabel(user.role)}</span>:user.status==='deactivated'?<span className="role-pill">Access removed</span>:<><select aria-label={'Role for '+(user.displayName||user.email)} value={drafts[user.uid]||user.role} onChange={e=>setDrafts(d=>({...d,[user.uid]:e.target.value as Role}))}>{ROLES.filter(r=>r!=='master_admin').map(r=><option value={r} key={r}>{roleLabel(r)}</option>)}</select><button className="secondary" disabled={working===user.uid||(drafts[user.uid]||user.role)===user.role} onClick={()=>saveRole(user)}><Save/>Save role</button><button className="secondary" disabled={working===user.uid} onClick={()=>resetPassword(user)}><Mail/>Reset password</button><button className="secondary danger-button" disabled={working===user.uid} onClick={()=>removeUser(user)}><Trash2/>Delete user</button></>}<label className="secondary photo-button"><Camera/>Profile photo<input type="file" accept="image/*" disabled={working===user.uid||user.status==='deactivated'} onChange={e=>{void savePhoto(user,e.target.files?.[0]);e.target.value=''}}/></label></div></article>)}</div>
 </section>;
}
