import { useEffect, useMemo, useState } from 'react';
import { collection, onSnapshot } from 'firebase/firestore';
import { AlertTriangle, CalendarPlus, CarFront, CheckCircle2, Clock3, Cpu, PackagePlus, Radio, UserRoundCheck, Wrench } from 'lucide-react';
import { db } from '../lib/firebase';
import { dayKey, displayTime, TIME_ZONE } from '../lib/domain';
import { notificationSeen, rememberNotification, sendAppNotification } from '../lib/notifications';
import type { AdminSection } from './AdminDashboard';
import { Installation, Role, Shift, SIM_STOCK_KEYS, Stock, StockAlertSettings, WorkSession, jobReference } from '../types';

const validTime=(value?:string)=>value&&Number.isFinite(Date.parse(value))?Date.parse(value):0;
const certLife=(row:any,today:string,soon=30)=>!row.expiry_date?'Active':row.expiry_date<today?'Expired':row.expiry_date<=new Date(Date.parse(today+'T12:00:00Z')+soon*86400000).toISOString().slice(0,10)?'Expiring Soon':'Active';
export function AdminHome({role,currentUid,shifts,installations,sessions,stock,settings,now,onNavigate}:{role:Role;currentUid:string;shifts:Shift[];installations:Installation[];sessions:WorkSession[];stock:Stock;settings:StockAlertSettings;now:number;onNavigate:(section:AdminSection)=>void}){
 const [certificates,setCertificates]=useState<any[]>([]);useEffect(()=>onSnapshot(collection(db,'certificates'),snapshot=>setCertificates(snapshot.docs.map(item=>({id:item.id,...item.data()}))),()=>setCertificates([])),[]);
 const today=dayKey(new Date(now)),todayJobs=shifts.filter(item=>item.date===today),completedShift=(shift:Shift)=>shift.status==='completed'||(shift.completed_units||0)>=shift.unit_count;
 const completedJobs=todayJobs.filter(completedShift),pendingJobs=todayJobs.filter(item=>!completedShift(item)),carried=todayJobs.filter(item=>item.carried_forward&&!completedShift(item));
 const todayCompletions=installations.filter(item=>dayKey(item.completed_at||item.timestamp||'1970-01-01')===today),installCount=todayCompletions.filter(item=>['new_installation','device_change','sim_device_change'].includes(item.job_type||'')).length,removalCount=todayCompletions.filter(item=>item.job_type==='device_removal').length;
 const totalVehicles=todayJobs.reduce((sum,item)=>sum+item.unit_count,0),completedVehicles=todayJobs.reduce((sum,item)=>sum+Math.min(item.unit_count,item.status==='completed'?item.unit_count:item.completed_units||installations.filter(done=>done.shift_id===item.id&&done.unit_index!==undefined).length),0);
 const vehicles=new Set([...shifts.flatMap(item=>item.vehicle_numbers?.length?item.vehicle_numbers:[item.vehicle_number||'']),...certificates.map(item=>String(item.vehicle_number||''))].filter(Boolean));
 const deviceStock=Object.entries(stock).filter(([key])=>!key.startsWith('SIM')).reduce((sum,[,value])=>sum+value,0),simStock=SIM_STOCK_KEYS.reduce((sum,key)=>sum+(stock[key]||0),0),working=new Set(sessions.filter(item=>item.date===today).map(item=>item.technician_id)).size;
 const low=Object.entries(stock).filter(([key,value])=>{const minimum=key.startsWith('SIM')?(settings.sim_minimums?.[key]??settings.threshold):(settings.device_minimums?.[key]??settings.threshold);return value<=minimum}).map(([key,value])=>({key,value,minimum:key.startsWith('SIM')?(settings.sim_minimums?.[key]??settings.threshold):(settings.device_minimums?.[key]??settings.threshold)}));
 const expiring=certificates.filter(item=>certLife(item,today)==='Expiring Soon'),expired=certificates.filter(item=>certLife(item,today)==='Expired');
 const recent=useMemo(()=>{const rows:{id:string;label:string;detail:string;time:string;section:AdminSection}[]=[];const latest=(predicate:(item:Installation)=>boolean)=>[...installations].filter(predicate).sort((a,b)=>validTime(b.completed_at||b.timestamp)-validTime(a.completed_at||a.timestamp))[0];const installed=latest(item=>['new_installation','device_change','sim_device_change'].includes(item.job_type||'')),removed=latest(item=>item.job_type==='device_removal'),assigned=latest(item=>!!item.device_imeis?.length||!!item.sim_numbers?.length),job=[...shifts].sort((a,b)=>validTime(b.assigned_at||b.scheduled_at)-validTime(a.assigned_at||a.scheduled_at))[0],certificate=[...certificates].sort((a,b)=>String(b.issue_date||'').localeCompare(String(a.issue_date||'')))[0];if(installed)rows.push({id:'installation',label:'Latest installation completed',detail:`${installed.customer_ref} · ${installed.vehicle_ref}`,time:installed.completed_at||installed.timestamp,section:'completed'});if(removed)rows.push({id:'removal',label:'Latest removal completed',detail:`${removed.customer_ref} · ${removed.vehicle_ref}`,time:removed.completed_at||removed.timestamp,section:'completed'});if(assigned)rows.push({id:'assignment',label:'Latest IMEI / SIM assignment',detail:[assigned.device_imeis?.[0],assigned.sim_numbers?.[0]].filter(Boolean).join(' · '),time:assigned.completed_at||assigned.timestamp,section:'vehicle-search'});if(job)rows.push({id:'job',label:'Latest job created',detail:`${jobReference(job)} · ${job.company_name||job.site_name}`,time:job.assigned_at||job.scheduled_at,section:'jobs'});if(certificate)rows.push({id:'certificate',label:'Latest certificate issued',detail:`${certificate.vehicle_number||'Vehicle'} · ${certificate.company_name||'Company'}`,time:certificate.issue_date,section:'certificates'});return rows},[shifts,installations,certificates]);
 useEffect(()=>{if(!['master_admin','owner','admin'].includes(role))return;const notices=[...(carried.length?[{title:'Jobs carried forward',body:`${carried.length} unfinished job${carried.length===1?' was':'s were'} carried forward to today.`,tag:`carry-forward:${today}`}]:[]),...(low.length?[{title:'Low stock warning',body:low.map(item=>`${item.key}: ${item.value}`).join(' · '),tag:`office-low-stock:${today}:${low.map(item=>item.key).join('|')}`}]:[]),...((expiring.length||expired.length)?[{title:'Certificate expiry attention',body:`${expiring.length} expiring soon · ${expired.length} expired`,tag:`certificate-expiry:${today}`}]:[])];for(const notice of notices){if(notificationSeen(currentUid,notice.tag))continue;void sendAppNotification(notice.title,notice.body,notice.tag).then(sent=>{if(sent)rememberNotification(currentUid,notice.tag)})}},[role,currentUid,today,carried.length,low.length,expiring.length,expired.length]);
 const cards=[['Jobs scheduled today',todayJobs.length,CalendarPlus],['Jobs completed today',completedJobs.length,CheckCircle2],['Jobs pending today',pendingJobs.length,Clock3],['Jobs carried forward',carried.length,AlertTriangle],['Installations today',installCount,Wrench],['Removals today',removalCount,PackagePlus],['Vehicles / assets',vehicles.size,CarFront],['Available GPS stock',deviceStock,Cpu],['Available SIM stock',simStock,Radio],['Technicians working',working,UserRoundCheck]] as const;
 return <div className="stack admin-home"><section className="dashboard-heading"><div><span className="eyebrow">OPERATIONS OVERVIEW</span><h1>Dashboard<span className="accent">.</span></h1><p>{new Date(now).toLocaleDateString('en-GB',{timeZone:TIME_ZONE,weekday:'long',day:'numeric',month:'long',year:'numeric'})}</p></div></section><section className="dashboard-metrics">{cards.map(([label,value,Icon])=><article key={label}><Icon/><span>{label}</span><strong>{value}</strong></article>)}</section><section className="dashboard-progress panel"><div className="section-label"><div><h2>Today’s job progress</h2><p>Live job and vehicle completion status.</p></div></div><div className="progress-pair"><div><span>Completed jobs</span><strong>{completedJobs.length} / {todayJobs.length}</strong><progress max={Math.max(1,todayJobs.length)} value={completedJobs.length}/></div><div><span>Completed vehicles</span><strong>{completedVehicles} / {totalVehicles}</strong><progress max={Math.max(1,totalVehicles)} value={completedVehicles}/></div></div></section><div className="dashboard-columns"><section className="panel"><div className="section-label"><div><h2>Recent activity</h2><p>Latest operational records.</p></div></div><div className="dashboard-list">{recent.map(item=><button key={item.id} onClick={()=>onNavigate(item.section)}><CheckCircle2/><span><strong>{item.label}</strong><small>{item.detail}</small></span><time>{validTime(item.time)?displayTime(item.time,TIME_ZONE):'Date not recorded'}</time></button>)}{!recent.length&&<div className="empty">No activity recorded yet.</div>}</div></section><section className="panel"><div className="section-label"><div><h2>Attention required</h2><p>Items that need action.</p></div></div><div className="attention-list"><button onClick={()=>onNavigate('jobs')}><span>Pending jobs</span><strong>{pendingJobs.length}</strong></button><button onClick={()=>onNavigate('jobs')}><span>Carried forward</span><strong>{carried.length}</strong></button><button onClick={()=>onNavigate('inventory')}><span>Low device stock</span><strong>{low.filter(item=>!item.key.startsWith('SIM')).length}</strong></button><button onClick={()=>onNavigate('inventory')}><span>Low SIM stock</span><strong>{low.filter(item=>item.key.startsWith('SIM')).length}</strong></button><button onClick={()=>onNavigate('certificates')}><span>Certificates expiring soon</span><strong>{expiring.length}</strong></button><button onClick={()=>onNavigate('certificates')}><span>Expired certificates</span><strong>{expired.length}</strong></button></div>{!!low.length&&<div className="low-stock-lines">{low.map(item=><span key={item.key}><AlertTriangle/>{item.key}: {item.value} available · minimum {item.minimum}</span>)}</div>}</section></div></div>;
}
