import { FormEvent, useState } from 'react';
import { FilePenLine } from 'lucide-react';

export function AgreementSimpleForm({vat,services,paymentTerms,terms,onSubmit,initial,onCancel}:{vat:number;services:string;paymentTerms:string;terms:string;onSubmit:(event:FormEvent<HTMLFormElement>)=>void;initial?:any;onCancel?:()=>void}){
 const editing=!!initial;
 const calculate=(values:any)=>{const quantity=Math.max(1,Number(values.quantity)||1),unitPrice=Number(values.unit_price)||0,subtotal=quantity*unitPrice+(Number(values.device)||0)+(Number(values.sim)||0)+(Number(values.installation)||0)+(Number(values.certificate)||0)+(Number(values.other)||0)-(Number(values.discount)||0),rate=Number(values.vat??vat)||0,vatAmount=subtotal*rate/100;return{subtotal,rate,vatAmount,total:subtotal+vatAmount}};
 const [summary,setSummary]=useState(()=>calculate(initial||{}));
 const money=(amount:number)=>new Intl.NumberFormat('en-AE',{style:'currency',currency:'AED',minimumFractionDigits:2}).format(amount||0);
 return <form className="panel agreement-form" onSubmit={onSubmit} onInput={e=>{const fd=new FormData(e.currentTarget),values=Object.fromEntries(fd.entries());setSummary(calculate(values))}}><div className="section-title"><FilePenLine/><div><h2>{editing?'Edit agreement':'Create agreement'}</h2><p>{editing?'Update the agreement details and shared customer copy.':'Enter the customer, service, pricing and contract details.'}</p></div></div>
  <div className="form-row"><label>Service name<input name="package_name" required placeholder="Vehicle tracking service" defaultValue={initial?.package_name||''}/></label><label>Contract start<input name="start_date" type="date" required defaultValue={initial?.start_date||new Date().toISOString().slice(0,10)}/></label><label>Duration (months)<input name="duration" type="number" min="1" required defaultValue={initial?.duration||12}/></label></div>
  <div className="form-row"><label>Company / client name<input name="client" required defaultValue={initial?.client||''}/></label><label>Contact person<input name="contact" required defaultValue={initial?.contact||''}/></label></div><div className="form-row"><label>Mobile number<input name="mobile" required defaultValue={initial?.mobile||''}/></label><label>Email address<input name="email" type="email" required defaultValue={initial?.email||''}/></label></div><label>Customer address <span className="optional">optional</span><input name="address" defaultValue={initial?.address||''}/></label>
  <div className="pricing-grid"><label>Units / vehicles<input name="quantity" type="number" min="1" required defaultValue={initial?.quantity||1}/></label><label>Price per unit<input name="unit_price" type="number" min="0" step="0.01" required defaultValue={initial?.unit_price||0}/></label><label>Device charge<input name="device" type="number" min="0" step="0.01" defaultValue={initial?.device||0}/></label><label>SIM charge<input name="sim" type="number" min="0" step="0.01" defaultValue={initial?.sim||0}/></label><label>Installation charge<input name="installation" type="number" min="0" step="0.01" defaultValue={initial?.installation||0}/></label><label>Certificate charge<input name="certificate" type="number" min="0" step="0.01" defaultValue={initial?.certificate||0}/></label><label>Other charges<input name="other" type="number" min="0" step="0.01" defaultValue={initial?.other||0}/></label><label>Discount<input name="discount" type="number" min="0" step="0.01" defaultValue={initial?.discount||0}/></label><label>VAT %<input name="vat" type="number" min="0" step="0.01" defaultValue={initial?.vat??vat}/></label></div>
  <section className="agreement-renewal"><label className="check-row"><input name="renewal_enabled" type="checkbox" defaultChecked={!!initial?.renewal_enabled}/>Include a renewal line in this agreement</label><label>Renewal price per unit (AED)<input name="renewal_price" type="number" min="0" step="0.01" defaultValue={initial?.renewal_price||0}/></label></section>
  <section className="agreement-live-total" aria-live="polite"><div><span>Subtotal</span><strong>{money(summary.subtotal)}</strong></div><div><span>VAT ({summary.rate}%)</span><strong>{money(summary.vatAmount)}</strong></div><div className="grand-total"><span>Grand total</span><strong>{money(summary.total)}</strong></div></section>
  <label>Services included<textarea name="services" rows={5} defaultValue={initial?.services||services}/></label><label>Terms &amp; Conditions<textarea name="terms" rows={12} defaultValue={initial?.terms||terms}/></label><label>Payment terms<textarea name="payment_terms" rows={3} defaultValue={initial?.payment_terms||paymentTerms}/></label><div className="form-footer">{editing&&<button type="button" className="secondary" onClick={onCancel}>Cancel</button>}<button className="primary">{editing?'Save agreement changes':'Generate secure agreement'}</button></div>
 </form>
}
