import { FormEvent, useState } from 'react';
import { Check, FilePenLine } from 'lucide-react';

type Template={id:string;name:string;description?:string;duration?:number;unit_price?:number;device?:number;sim?:number;installation?:number;certificate?:number;other?:number;vat?:number;renewal_enabled?:boolean;renewal_price?:number;renewal_vat_mode?:'inclusive'|'exclusive';services?:string;terms?:string;payment_terms?:string};

export function AgreementSimpleForm({vat,services,paymentTerms,terms,onSubmit,initial,onCancel,templates=[]}:{vat:number;services:string;paymentTerms:string;terms:string;onSubmit:(event:FormEvent<HTMLFormElement>)=>void;initial?:any;onCancel?:()=>void;templates?:Template[]}){
 const editing=!!initial;
 const [template,setTemplate]=useState<Template|null>(null);
 const renewalCalc=(amount:number,mode:'inclusive'|'exclusive')=>{const cents=Math.round(amount*100);if(mode==='inclusive'){const before=Math.round(cents/1.05);return{before:before/100,vat:(cents-before)/100,total:cents/100}}const tax=Math.round(cents*.05);return{before:cents/100,vat:tax/100,total:(cents+tax)/100}};
 const calculate=(values:any)=>{const round=(amount:number)=>Math.round((amount+Number.EPSILON)*100)/100,quantity=Math.max(1,Number(values.quantity)||1),unitPrice=Number(values.unit_price)||0,subtotal=round(quantity*unitPrice+(Number(values.device)||0)+(Number(values.sim)||0)+(Number(values.installation)||0)+(Number(values.certificate)||0)+(Number(values.other)||0)-(Number(values.discount)||0)),rate=Number(values.vat??vat)||0,vatAmount=round(subtotal*rate/100),renewalRate=Number(values.renewal_price)||0;return{subtotal,rate,vatAmount,total:round(subtotal+vatAmount),renewal:renewalCalc(renewalRate,values.renewal_vat_mode==='inclusive'?'inclusive':'exclusive')}};
 const templateValues=(item:Template|null)=>item?{quantity:1,unit_price:item.unit_price,device:item.device,sim:item.sim,installation:item.installation,certificate:item.certificate,other:item.other,vat:item.vat??vat,renewal_price:item.renewal_price??0,renewal_vat_mode:item.renewal_vat_mode??'exclusive'}:{};
 const [summary,setSummary]=useState(()=>calculate(initial||{}));
 const money=(amount:number)=>new Intl.NumberFormat('en-AE',{style:'currency',currency:'AED',minimumFractionDigits:2}).format(amount||0);
 function chooseTemplate(item:Template|null){setTemplate(item);setSummary(calculate({...templateValues(item),renewal_enabled:item?.renewal_enabled}))}
 const key=template?.id||'custom';
 return <form className="panel agreement-form" onSubmit={onSubmit} onInput={e=>{const fd=new FormData(e.currentTarget),values=Object.fromEntries(fd.entries());setSummary(calculate(values))}} onChange={e=>{const fd=new FormData(e.currentTarget),values=Object.fromEntries(fd.entries());setSummary(calculate(values))}}><div className="section-title"><FilePenLine/><div><h2>{editing?'Edit agreement':'Create agreement'}</h2><p>{editing?'Update the agreement details and shared customer copy.':'Choose a template, then enter the customer details.'}</p></div></div>
  {!editing&&<section className="agreement-template-picker"><div><span className="eyebrow">AGREEMENT TEMPLATE</span><h3>Choose the device or service</h3><p>The selected template fills its pricing, services and terms automatically.</p></div><div className="agreement-template-options"><button type="button" className={!template?'active':''} onClick={()=>chooseTemplate(null)}>{!template&&<Check/>}<strong>Custom</strong><small>Enter details manually</small></button>{templates.map(item=><button type="button" className={template?.id===item.id?'active':''} key={item.id} onClick={()=>chooseTemplate(item)}>{template?.id===item.id&&<Check/>}<strong>{item.name}</strong><small>{item.description||`${item.duration||12} months`}</small></button>)}</div>{!templates.length&&<div className="notice info">No saved templates yet. HR or Admin can create GT06, FMC920 and other templates from Agreement templates.</div>}</section>}
  <div className="form-row"><label>Service name<input key={'name-'+key} name="package_name" required placeholder="Vehicle tracking service" defaultValue={initial?.package_name||template?.name||''}/></label><label>Contract start<input name="start_date" type="date" required defaultValue={initial?.start_date||new Date().toISOString().slice(0,10)}/></label><label>Duration (months)<input key={'duration-'+key} name="duration" type="number" min="1" required defaultValue={initial?.duration||template?.duration||12}/></label></div>
  <div className="form-row"><label>Company / client name<input name="client" required defaultValue={initial?.client||''}/></label><label>Contact person<input name="contact" required defaultValue={initial?.contact||''}/></label></div><div className="form-row"><label>Mobile number<input name="mobile" required defaultValue={initial?.mobile||''}/></label><label>Email address<input name="email" type="email" required defaultValue={initial?.email||''}/></label></div><label>Customer address <span className="optional">optional</span><input name="address" defaultValue={initial?.address||''}/></label>
  <div className="pricing-grid"><label>Units / vehicles<input name="quantity" type="number" min="1" required defaultValue={initial?.quantity||1}/></label><label>Price per unit<input key={'price-'+key} name="unit_price" type="number" min="0" step="0.01" required defaultValue={initial?.unit_price??template?.unit_price??0}/></label><label>Device charge<input key={'device-'+key} name="device" type="number" min="0" step="0.01" defaultValue={initial?.device??template?.device??0}/></label><label>SIM charge<input key={'sim-'+key} name="sim" type="number" min="0" step="0.01" defaultValue={initial?.sim??template?.sim??0}/></label><label>Installation charge<input key={'install-'+key} name="installation" type="number" min="0" step="0.01" defaultValue={initial?.installation??template?.installation??0}/></label><label>Certificate charge<input key={'certificate-'+key} name="certificate" type="number" min="0" step="0.01" defaultValue={initial?.certificate??template?.certificate??0}/></label><label>Other charges<input key={'other-'+key} name="other" type="number" min="0" step="0.01" defaultValue={initial?.other??template?.other??0}/></label><label>Discount<input name="discount" type="number" min="0" step="0.01" defaultValue={initial?.discount||0}/></label><label>VAT %<input key={'vat-'+key} name="vat" type="number" min="0" step="0.01" defaultValue={initial?.vat??template?.vat??vat}/></label></div>
  <section className="agreement-renewal pricing-card"><div className="renewal-card-heading"><span className="eyebrow">RENEWAL RATE</span><label className="check-row"><input key={'renewal-'+key} name="renewal_enabled" type="checkbox" defaultChecked={initial?.renewal_enabled??template?.renewal_enabled??false}/>Include on agreement</label></div><label>Renewal Rate (AED)<input key={'renewal-price-'+key} name="renewal_price" type="number" min="0" step="0.01" defaultValue={initial?.renewal_price??template?.renewal_price??0}/></label><fieldset className="renewal-vat-options"><legend>VAT Calculation · 5%</legend><label><input key={'renewal-vat-in-'+key} type="radio" name="renewal_vat_mode" value="inclusive" defaultChecked={(initial?.renewal_vat_mode??template?.renewal_vat_mode)==='inclusive'}/>Price includes 5% VAT</label><label><input key={'renewal-vat-out-'+key} type="radio" name="renewal_vat_mode" value="exclusive" defaultChecked={(initial?.renewal_vat_mode??template?.renewal_vat_mode)!=='inclusive'}/>Add 5% VAT to price</label></fieldset>{summary.renewal&&<div className="renewal-price-summary"><div><span>Amount Before VAT</span><strong>{money(summary.renewal.before)}</strong></div><div><span>VAT (5%)</span><strong>{money(summary.renewal.vat)}</strong></div><div className="renewal-price-total"><span>Total Including VAT</span><strong>{money(summary.renewal.total)}</strong></div></div>}</section>
  <section className="agreement-live-total" aria-live="polite"><div><span>Subtotal</span><strong>{money(summary.subtotal)}</strong></div><div><span>VAT ({summary.rate}%)</span><strong>{money(summary.vatAmount)}</strong></div><div className="grand-total"><span>Grand total</span><strong>{money(summary.total)}</strong></div></section>
  <label>Services included<textarea key={'services-'+key} name="services" rows={5} defaultValue={initial?.services||template?.services||services}/></label><label>Terms &amp; Conditions<textarea key={'terms-'+key} name="terms" rows={12} defaultValue={initial?.terms||template?.terms||terms}/></label><label>Payment terms<textarea key={'payment-'+key} name="payment_terms" rows={3} defaultValue={initial?.payment_terms||template?.payment_terms||paymentTerms}/></label><div className="form-footer">{editing&&<button type="button" className="secondary" onClick={onCancel}>Cancel</button>}<button className="primary">{editing?'Save agreement changes':'Generate secure agreement'}</button></div>
 </form>
}

