import { ReactNode, useState } from 'react';
import { AlertCircle, BriefcaseBusiness, CheckCircle2, ChevronDown, Clock3, MapPin, MessageCircle, Navigation, Pencil, Phone, Trash2, Wrench } from 'lucide-react';
import { Attendance, Installation, PendingOperation, Shift, completionActor, jobLabel, jobReference } from '../types';
import { attendanceStatus, displayTime, isReleasedJob, sortJobsByTime } from '../lib/domain';
import { captureLocation } from '../lib/location';
import { checkIn } from '../lib/data';
import { safeMaps } from './ScheduleForm';
import { JobCompletion } from './JobCompletion';
import { JobDetailModal } from './JobDetailModal';
function appointmentWhatsAppUrl(s:Shift){
 const phone=(s.customer_phone||'').replace(/\D/g,'');
 const vehicles=s.unit_jobs?.length?s.unit_jobs.map((unit,index)=>`Vehicle ${index+1}: ${unit.vehicle_number||'Plate not recorded'} — ${jobLabel(unit.job_type)}`).join('\n'):(s.vehicle_numbers?.length?s.vehicle_numbers:[s.vehicle_number].filter(Boolean)).map((vehicle,index)=>`Vehicle ${index+1}: ${vehicle}`).join('\n');
 const map=safeMaps(s.maps_url||'');
 const message=`Dear ${s.contact_person||'Customer'},\n\nYour SecureTrack appointment is scheduled:\nCompany: ${s.company_name||s.customer_name||s.site_name}\nJob ID: ${jobReference(s)}\n${vehicles?'Vehicles:\n'+vehicles+'\n':''}Scheduled: ${displayTime(s.scheduled_at,s.timezone)}${s.site_name?'\nLocation: '+s.site_name:''}${map?'\nMap: '+map:''}\n\nPlease have the vehicle${s.unit_count===1?'':'s'} ready at the scheduled time.\nSecureTrack GPS Trading L.L.C.`;
 return `https://wa.me/${phone}?text=${encodeURIComponent(message)}`;
}

function completionWhatsAppUrl(s:Shift,unitCompletions:Installation[],done:Installation){
 const phone=(s.customer_phone||'').replace(/\D/g,'');
 const vehicleLines=s.unit_jobs?.length?s.unit_jobs.map((unit,index)=>`Vehicle ${index+1}: ${unit.vehicle_number||'Plate not recorded'} — ${jobLabel(unit.job_type)}`).join('\n'):(s.vehicle_numbers?.length?s.vehicle_numbers:[s.vehicle_number].filter(Boolean)).map((vehicle,index)=>`Vehicle ${index+1}: ${vehicle}`).join('\n');
 const timestamps=[...unitCompletions,done].map(item=>item.completed_at||item.timestamp).filter(Boolean).sort((a,b)=>Date.parse(a)-Date.parse(b));
 const completedAt=timestamps[timestamps.length-1]||done.completed_at||done.timestamp;
 const message=`Dear ${s.contact_person||'Customer'},\n\nThe scheduled SecureTrack work is complete.\nCompany: ${s.company_name||s.customer_name||s.site_name}\nJob ID: ${jobReference(s)}\n${vehicleLines?'Completed vehicle(s):\n'+vehicleLines+'\n':''}Completed at: ${displayTime(completedAt,s.timezone)}\nTechnician: ${s.technician_name||completionActor(done)}\n\nThank you for choosing SecureTrack GPS Trading L.L.C.`;
 return `https://wa.me/${phone}?text=${encodeURIComponent(message)}`;
}
export function AttendancePanel({shifts,attendance,installations=[],save,onEdit,onDelete,onAdminComplete,filters,admin=false,now}:{shifts:Shift[];attendance:Attendance[];installations?:Installation[];save?:(op:Omit<PendingOperation,'uid'|'captured_at'>)=>Promise<void>;onEdit?:(shift:Shift)=>void;onDelete?:(shift:Shift)=>void;onAdminComplete?:(shift:Shift,reason:string)=>Promise<void>;filters?:ReactNode;admin?:boolean;now:number}){
 const [busy,setBusy]=useState('');const [error,setError]=useState('');const [notice,setNotice]=useState('');const [actionError,setActionError]=useState<{shiftId:string;message:string}|null>(null);const [completing,setCompleting]=useState('');const [adminCompleting,setAdminCompleting]=useState('');const [adminReason,setAdminReason]=useState('');const [details,setDetails]=useState('');const [selected,setSelected]=useState<Shift|null>(null);
 async function arrive(shift:Shift){setBusy(shift.id);setError('');setActionError(null);setNotice('');try{const coords=await captureLocation();await checkIn(shift,coords);setNotice('Arrival confirmed with current time and location.')}catch(e:any){const detail=String(e?.code||'')+' '+String(e?.message||''),message=/resource-exhausted|quota exceeded/i.test(detail)?'SecureTrack cloud usage is temporarily at its limit. Your location was found, but arrival cannot be saved until the cloud limit resets or the Firebase plan is upgraded.':e?.message||'Arrival could not be confirmed. Check your connection and try again.';setError(message);setActionError({shiftId:shift.id,message})}finally{setBusy('')}}
 async function completeAsAdmin(shift:Shift){if(!onAdminComplete)return;setBusy(shift.id);setError('');setActionError(null);setNotice('');try{await onAdminComplete(shift,adminReason);setAdminCompleting('');setAdminReason('');setNotice('Job marked completed by administrator. No IMEI, SIM or inventory deduction was recorded.')}catch(e:any){const message=e?.message||'The job could not be completed. Try again.';setError(message);setActionError({shiftId:shift.id,message})}finally{setBusy('')}}
 const ordered=[...shifts].sort(sortJobsByTime);
 const visible=admin?ordered:ordered.filter(s=>isReleasedJob(s)&&s.status!=='completed'&&!installations.some(item=>(item.shift_id===s.id||item.id===s.id)&&item.unit_index===undefined));
 return <section className="panel schedule-panel"><div className="section-title"><div className="icon-box"><BriefcaseBusiness/></div><div><h2>{admin?'Assigned jobs & attendance':'Your field schedule'}</h2><p>{admin?'Monitor assignments, arrivals and completed work.':'Everything you need for each assigned customer visit.'}</p></div></div>{filters&&<div className="schedule-filter-bar">{filters}</div>}{error&&<div className="notice error">{error}</div>}{notice&&<div className="notice success">{notice}</div>}{!visible.length&&<div className="empty"><MapPin/><h3>{!admin&&shifts.length?'All jobs completed':'No jobs scheduled'}</h3><p>{admin?'Create an assignment to get started.':shifts.length?'Completed work is available in the Completed section.':'Your administrator will assign jobs here.'}</p></div>}
 <div className="schedule-list">{visible.map(s=>{const a=attendance.find(x=>x.id===s.id);const unitCompletions=installations.filter(x=>x.shift_id===s.id&&x.unit_index!==undefined);const legacyDone=installations.find(x=>(x.shift_id===s.id||x.id===s.id)&&x.unit_index===undefined);const done=s.status==='completed'?(legacyDone||unitCompletions[unitCompletions.length-1]):legacyDone;const completedUnits=legacyDone?s.unit_count:Math.max(s.completed_units||0,unitCompletions.length);const status=attendanceStatus(s,a,now);const inWindow=now>=Date.parse(s.window_start)&&now<Date.parse(s.window_end);return <article className={'schedule-card '+(done?'completed':'')} key={s.id}><div className="schedule-head"><div><small>{jobReference(s)} · {new Date(s.date+'T12:00:00Z').toLocaleDateString('en-GB',{weekday:'long',day:'numeric',month:'short',year:'numeric',timeZone:'UTC'})}{admin&&' · '+s.technician_name}</small><h3>{s.company_name||s.customer_name||s.site_name}</h3></div><span className={'badge '+(done?'good':completedUnits?'warning':status.timing==='On time'?'good':['Late','Missing'].includes(status.timing)?'warning':'')}>{s.status==='draft'?'Draft':s.status==='cancelled'?'Cancelled':done?'Completed':completedUnits?`${completedUnits}/${s.unit_count} Completed`:status.timing}</span></div>
 {admin&&s.status==='draft'&&<div className="notice warning">Draft — not sent to the technician. Choose Schedule job to finish the details and issue it.</div>}<div className="job-summary"><span><Wrench/>{jobLabel(s.job_type)}</span><span><strong>{completedUnits}/{s.unit_count}</strong> Completed</span></div>{s.carried_forward&&<div className="carried-forward-note"><Clock3/><span><strong>Carried forward</strong>Original date: {s.original_scheduled_date||s.last_carried_forward_from||'Not recorded'} · Job ID preserved</span></div>}{s.unit_count>1&&<div className="unit-summary-list">{(s.unit_jobs?.length?s.unit_jobs:(s.vehicle_numbers?.length?s.vehicle_numbers:[s.vehicle_number]).filter(Boolean).map(vehicle_number=>({vehicle_number,job_type:s.job_type==='mixed'?'inspection':s.job_type}))).map((unit,index)=>{const unitDone=!!legacyDone||unitCompletions.some(item=>item.unit_index===index);return <div className={'unit-summary '+(unitDone?'done':'')} key={`${unit.vehicle_number}-${index}`}><span>Vehicle {index+1}</span><strong>{unit.vehicle_number||'No plate'}</strong><small>{unitDone?'Completed':jobLabel(unit.job_type)}</small></div>})}</div>}{s.unit_count===1&&s.vehicle_number&&<div className="unit-summary-list"><div className="unit-summary"><span>Vehicle</span><strong>{s.vehicle_number}</strong></div></div>}{s.payment_collection_required&&<div className="job-instructions payment-collection"><AlertCircle/><div><strong>Payment collection required{typeof s.payment_amount==='number'&&s.payment_amount>0?` · AED ${s.payment_amount.toFixed(2)}`:''}</strong><p>Collect payment from the customer before completing this job.</p></div></div>}{s.job_notes&&<div className="job-instructions"><AlertCircle/><div><strong>Important job instructions</strong><p>{s.job_notes}</p></div></div>}<div className="contact-card"><div><span>CONTACT PERSON</span><strong>{s.contact_person||'Site contact'}</strong><small>{s.customer_phone||'No phone supplied'}</small></div><div className="quick-actions">{s.customer_phone&&<><a href={'tel:'+s.customer_phone} aria-label="Call contact"><Phone/></a><a href={'https://wa.me/'+s.customer_phone.replace(/\D/g,'')} target="_blank" rel="noreferrer" aria-label="WhatsApp contact"><MessageCircle/></a></>}<a href={safeMaps(s.maps_url||'')||'https://maps.google.com'} target="_blank" rel="noreferrer" aria-label="Open location"><Navigation/></a></div></div>{admin&&!done&&s.status!=='draft'&&s.status!=='cancelled'&&s.status!=='completed'&&s.customer_phone&&<a className="primary" style={{width:"100%",justifyContent:"flex-start",marginTop:9}} href={appointmentWhatsAppUrl(s)} target="_blank" rel="noreferrer"><MessageCircle/>Prepare appointment message in WhatsApp</a>}<div className="job-meta"><span><Clock3/>{displayTime(s.scheduled_at,s.timezone)}</span><span><MapPin/>{s.site_name}</span></div>
 {a&&<div className="arrival"><strong>{status.location}{status.distance!==null&&` · ${status.distance} m from site`}</strong><span>Arrived {displayTime(a.timestamp,s.timezone)} · GPS ±{Math.round(a.accuracy_m)} m</span></div>}{done&&<><div className="completion-summary"><CheckCircle2/><div><strong>Work recorded {displayTime(done.timestamp,s.timezone)}</strong><span>{done.completion_source==='admin_override'?`Manually completed by ${completionActor(done)}`:`${done.device_imeis?.length||0} device IDs · ${done.sim_numbers?.length||done.sim_count||0} SIM IDs${done.sim_count?` · ${done.sim_provider||'Legacy / unassigned'}`:''}`}</span></div></div>{admin&&done&&s.customer_phone&&<a className="primary" style={{width:"100%",justifyContent:"flex-start",marginTop:9}} href={completionWhatsAppUrl(s,unitCompletions,legacyDone||done)} target="_blank" rel="noreferrer"><MessageCircle/>Prepare completion update in WhatsApp</a>}<button className={'completion-details-toggle '+(details===s.id?'open':'')} type="button" aria-expanded={details===s.id} onClick={()=>setDetails(details===s.id?'':s.id)}>View completion details <ChevronDown/></button>{details===s.id&&<div className="completion-details"><div><span>Customer</span><strong>{s.company_name||s.customer_name||s.site_name}</strong></div><div><span>Job</span><strong>{jobLabel(s.job_type)} · {done.unit_count||s.unit_count} unit{(done.unit_count||s.unit_count)===1?'':'s'}</strong></div><div><span>Vehicle plate</span><strong>{done.vehicle_ref||s.vehicle_number||'—'}</strong></div><div><span>Completed by</span><strong>{completionActor(done)}</strong></div><div><span>Device model</span><strong>{done.device_model||'—'}</strong></div><div className="detail-wide"><span>Device IMEI{(done.device_imeis?.length||0)===1?'':'s'}</span><strong>{done.device_imeis?.join(' · ')||'—'}</strong></div><div><span>SIM network</span><strong>{done.sim_count?done.sim_provider||'Legacy / unassigned':'—'}</strong></div><div className="detail-wide"><span>SIM number{(done.sim_numbers?.length||0)===1?'':'s'}</span><strong>{done.sim_numbers?.join(' · ')||'—'}</strong></div><div className="detail-wide"><span>{done.completion_source==='admin_override'?'Administrative reason':'Completion notes'}</span><strong>{done.completion_reason||done.notes||'No completion notes'}</strong></div></div>}</>}
 <button type="button" className="text-button job-detail-button" onClick={()=>setSelected(s)}>View full job details ↗</button>{actionError?.shiftId===s.id&&<div className="notice error action-feedback" role="alert">{actionError.message}</div>}{admin&&!done&&(onEdit||onDelete||onAdminComplete)&&<div className="admin-job-actions">{onEdit&&<button className="secondary" onClick={()=>onEdit(s)}><Pencil/>{s.status==='draft'?'Schedule job':'Edit job'}</button>}{onAdminComplete&&isReleasedJob(s)&&<button className="secondary" onClick={()=>{setAdminCompleting(adminCompleting===s.id?'':s.id);setAdminReason('');setActionError(null)}}><CheckCircle2/>Mark completed</button>}{onDelete&&<button className="secondary danger-button" onClick={()=>onDelete(s)}><Trash2/>Delete job</button>}</div>}{admin&&!done&&onAdminComplete&&adminCompleting===s.id&&<div className="admin-completion-form"><div className="notice warning"><strong>Administrative completion</strong><span>This records no IMEI or SIM and does not deduct technician inventory.</span></div><label>Reason<textarea value={adminReason} onChange={e=>setAdminReason(e.target.value)} maxLength={1000} placeholder="Example: Technician completed the work, but the client-side form failed." required/></label><div className="job-buttons"><button className="secondary" type="button" onClick={()=>{setAdminCompleting('');setAdminReason('');setActionError(null)}}>Cancel</button><button className="primary" type="button" disabled={busy===s.id} onClick={()=>completeAsAdmin(s)}>{busy===s.id?'Completing job…':'Confirm completed'}</button></div></div>}{!admin&&!done&&<div className="job-buttons">{!a&&<button className="secondary" disabled={!!busy||!inWindow} onClick={()=>arrive(s)}><MapPin/>{busy===s.id?'Confirming arrival…':inWindow?'Confirm arrival':'Available on job date'}</button>}<button className="primary" disabled={!save||!inWindow||!a} onClick={()=>setCompleting(completing===s.id?'':s.id)}><Wrench/>{!a?'Confirm arrival first':completing===s.id?'Close completion':'Complete job'}</button></div>}
 {!admin&&!done&&completing===s.id&&save&&<JobCompletion shift={s} completedUnits={unitCompletions} save={save} onDone={finished=>{if(finished)setCompleting('');setNotice(finished?'All vehicles completed. The main job is now complete.':'Vehicle completed and stock updated. Waiting for office online verification.')}}/>}</article>})}</div>{selected&&<JobDetailModal shift={selected} installation={installations.find(i=>i.shift_id===selected.id||i.id===selected.id)} attendance={attendance.find(a=>a.id===selected.id)} onClose={()=>setSelected(null)}/>}</section>}


