import { useState } from 'react';
import { AlertCircle, BriefcaseBusiness, CheckCircle2, ChevronDown, Clock3, MapPin, MessageCircle, Navigation, Pencil, Phone, Trash2, Wrench } from 'lucide-react';
import { Attendance, Installation, PendingOperation, Shift, jobLabel, jobReference } from '../types';
import { attendanceStatus, displayTime } from '../lib/domain';
import { captureLocation } from '../lib/location';
import { checkIn } from '../lib/data';
import { safeMaps } from './ScheduleForm';
import { JobCompletion } from './JobCompletion';
import { JobDetailModal } from './JobDetailModal';

export function AttendancePanel({shifts,attendance,installations=[],save,onEdit,onDelete,admin=false,now}:{shifts:Shift[];attendance:Attendance[];installations?:Installation[];save?:(op:Omit<PendingOperation,'uid'|'captured_at'>)=>Promise<void>;onEdit?:(shift:Shift)=>void;onDelete?:(shift:Shift)=>void;admin?:boolean;now:number}){
 const [busy,setBusy]=useState('');const [error,setError]=useState('');const [notice,setNotice]=useState('');const [completing,setCompleting]=useState('');const [details,setDetails]=useState('');const [selected,setSelected]=useState<Shift|null>(null);
 async function arrive(shift:Shift){setBusy(shift.id);setError('');setNotice('');try{const coords=await captureLocation();await checkIn(shift,coords);setNotice('Arrival confirmed with current time and location.')}catch(e:any){setError(e.message)}finally{setBusy('')}}
 const visible=admin?shifts:shifts.filter(s=>!installations.some(item=>item.shift_id===s.id||item.id===s.id));
 return <section className="panel schedule-panel"><div className="section-title"><div className="icon-box"><BriefcaseBusiness/></div><div><h2>{admin?'Assigned jobs & attendance':'Your field schedule'}</h2><p>{admin?'Monitor assignments, arrivals and completed work.':'Everything you need for each assigned customer visit.'}</p></div></div>{error&&<div className="notice error">{error}</div>}{notice&&<div className="notice success">{notice}</div>}{!visible.length&&<div className="empty"><MapPin/><h3>{!admin&&shifts.length?'All jobs completed':'No jobs scheduled'}</h3><p>{admin?'Create an assignment to get started.':shifts.length?'Completed work is available in the Completed section.':'Your administrator will assign jobs here.'}</p></div>}
 <div className="schedule-list">{visible.map(s=>{const a=attendance.find(x=>x.id===s.id);const done=installations.find(x=>x.shift_id===s.id||x.id===s.id);const status=attendanceStatus(s,a,now);const inWindow=now>=Date.parse(s.window_start)&&now<Date.parse(s.window_end);return <article className={'schedule-card '+(done?'completed':'')} key={s.id}><div className="schedule-head"><div><small>{jobReference(s)} · {new Date(s.date+'T12:00:00Z').toLocaleDateString('en-GB',{weekday:'long',day:'numeric',month:'short',year:'numeric',timeZone:'UTC'})}{admin&&' · '+s.technician_name}</small><h3>{s.company_name||s.customer_name||s.site_name}</h3></div><span className={'badge '+(done?'good':status.timing==='On time'?'good':['Late','Missing'].includes(status.timing)?'warning':'')}>{done?'Completed':status.timing}</span></div>
 <div className="job-summary"><span><Wrench/>{jobLabel(s.job_type)}</span><span><strong>{s.unit_count}</strong> unit{s.unit_count===1?'':'s'}</span>{(s.vehicle_numbers?.length?s.vehicle_numbers:[s.vehicle_number]).filter(Boolean).map((plate,index)=><span className="plate-number" key={index}>{s.unit_count>1?`Unit ${index+1} · `:''}{plate}</span>)}</div>{s.job_notes&&<div className="job-instructions"><AlertCircle/><div><strong>Important job instructions</strong><p>{s.job_notes}</p></div></div>}<div className="contact-card"><div><span>CONTACT PERSON</span><strong>{s.contact_person||'Site contact'}</strong><small>{s.customer_phone||'No phone supplied'}</small></div><div className="quick-actions">{s.customer_phone&&<><a href={'tel:'+s.customer_phone} aria-label="Call contact"><Phone/></a><a href={'https://wa.me/'+s.customer_phone.replace(/\D/g,'')} target="_blank" rel="noreferrer" aria-label="WhatsApp contact"><MessageCircle/></a></>}<a href={safeMaps(s.maps_url||'')||'https://maps.google.com'} target="_blank" rel="noreferrer" aria-label="Open location"><Navigation/></a></div></div><div className="job-meta"><span><Clock3/>{displayTime(s.scheduled_at,s.timezone)}</span><span><MapPin/>{s.site_name}</span></div>
 {a&&<div className="arrival"><strong>{status.location}{status.distance!==null&&` · ${status.distance} m from site`}</strong><span>Arrived {displayTime(a.timestamp,s.timezone)} · GPS ±{Math.round(a.accuracy_m)} m</span></div>}{done&&<><div className="completion-summary"><CheckCircle2/><div><strong>Work recorded {displayTime(done.timestamp,s.timezone)}</strong><span>{done.device_imeis?.length||0} device IDs · {done.sim_numbers?.length||done.sim_count||0} SIM IDs{done.sim_count?` · ${done.sim_provider||'Legacy / unassigned'}`:''}</span></div></div><button className={'completion-details-toggle '+(details===s.id?'open':'')} type="button" aria-expanded={details===s.id} onClick={()=>setDetails(details===s.id?'':s.id)}>View completion details <ChevronDown/></button>{details===s.id&&<div className="completion-details"><div><span>Customer</span><strong>{s.company_name||s.customer_name||s.site_name}</strong></div><div><span>Job</span><strong>{jobLabel(s.job_type)} · {done.unit_count||s.unit_count} unit{(done.unit_count||s.unit_count)===1?'':'s'}</strong></div><div><span>Vehicle plate</span><strong>{done.vehicle_ref||s.vehicle_number||'—'}</strong></div><div><span>Device model</span><strong>{done.device_model||'—'}</strong></div><div className="detail-wide"><span>Device IMEI{(done.device_imeis?.length||0)===1?'':'s'}</span><strong>{done.device_imeis?.join(' · ')||'—'}</strong></div><div><span>SIM network</span><strong>{done.sim_count?done.sim_provider||'Legacy / unassigned':'—'}</strong></div><div className="detail-wide"><span>SIM number{(done.sim_numbers?.length||0)===1?'':'s'}</span><strong>{done.sim_numbers?.join(' · ')||'—'}</strong></div><div className="detail-wide"><span>Completion notes</span><strong>{done.notes||'No completion notes'}</strong></div></div>}</>}
 <button type="button" className="text-button job-detail-button" onClick={()=>setSelected(s)}>View full job details ↗</button>{admin&&!done&&(onEdit||onDelete)&&<div className="admin-job-actions">{onEdit&&<button className="secondary" onClick={()=>onEdit(s)}><Pencil/>Edit job</button>}{onDelete&&<button className="secondary danger-button" onClick={()=>onDelete(s)}><Trash2/>Delete job</button>}</div>}{!admin&&!done&&<div className="job-buttons">{!a&&<button className="secondary" disabled={!!busy||!inWindow} onClick={()=>arrive(s)}><MapPin/>{busy===s.id?'Getting location…':inWindow?'Confirm arrival':'Available on job date'}</button>}<button className="primary" disabled={!save||!inWindow||!a} onClick={()=>setCompleting(completing===s.id?'':s.id)}><Wrench/>{!a?'Confirm arrival first':completing===s.id?'Close completion':'Complete job'}</button></div>}
 {!admin&&!done&&completing===s.id&&save&&<JobCompletion shift={s} save={save} onDone={()=>{setCompleting('');setNotice('Job completed and inventory updated.')}}/>}</article>})}</div>{selected&&<JobDetailModal shift={selected} installation={installations.find(i=>i.shift_id===selected.id||i.id===selected.id)} attendance={attendance.find(a=>a.id===selected.id)} onClose={()=>setSelected(null)}/>}</section>}
