import { FormEvent, useEffect, useMemo, useState } from 'react';
import { addDoc, collection, doc, onSnapshot, orderBy, query, runTransaction, serverTimestamp } from '../lib/cloud/store';
import { Download, FileCheck2, MessageCircle, Plus } from 'lucide-react';
import { db } from '../lib/aws';
import { Role } from '../types';
import { saveDownload } from '../lib/download';

export type Certificate={id:string;tracker_id?:number;company_name:string;vehicle_number:string;chassis_number:string;device_type?:string;contact_person?:string;whatsapp_number?:string;email?:string;remarks?:string;service_type?:string;issue_date:string;active_date:string;expiry_date:string;issued_by?:string;status:'Draft'|'Issued'|'Expired'|'Void'|'Reissued';source:string;created_at?:any;issued_at?:any};
const plusYear=(d:string)=>{const x=new Date(d+'T12:00:00Z');x.setUTCFullYear(x.getUTCFullYear()+1);return x.toISOString().slice(0,10)};
const pretty=(d:string)=>new Intl.DateTimeFormat('en-GB',{day:'numeric',month:'long',year:'numeric'}).format(new Date(d+'T12:00:00Z'));
const certificateTime=(c:Certificate)=>{const raw=c.issued_at?.toDate?.()||c.created_at?.toDate?.()||new Date(`${c.issue_date}T12:00:00+04:00`);return new Intl.DateTimeFormat('en-GB',{timeZone:'Asia/Dubai',day:'2-digit',month:'short',year:'2-digit',hour:'2-digit',minute:'2-digit',hour12:true}).format(raw).replace(',','')};
const phone=(raw='')=>{let n=raw.replace(/\D/g,'');if(n.startsWith('00'))n=n.slice(2);if(n.startsWith('0'))n='971'+n.slice(1);return n};

export function CertificatesWorkspace({role,userName,userId}:{role:Role;userName:string;userId:string}){
 const [rows,setRows]=useState<Certificate[]>([]),[view,setView]=useState<'list'|'create'>('list'),[preview,setPreview]=useState<Certificate|null>(null),[notice,setNotice]=useState('');
 useEffect(()=>onSnapshot(query(collection(db,'certificates'),orderBy('created_at','desc')),s=>setRows(s.docs.map(d=>({id:d.id,...d.data()} as Certificate)))),[]);
 const counts=useMemo(()=>({total:rows.length,issued:rows.filter(x=>x.status==='Issued').length,draft:rows.filter(x=>x.status==='Draft').length,void:rows.filter(x=>x.status==='Void').length}),[rows]);
 const data=(f:HTMLFormElement)=>{const fd=new FormData(f),today=String(fd.get('issue_date'));return {company_name:String(fd.get('company_name')).trim(),vehicle_number:String(fd.get('vehicle_number')).trim(),chassis_number:String(fd.get('chassis_number')).trim(),device_type:String(fd.get('device_type')).trim(),contact_person:String(fd.get('contact_person')).trim(),whatsapp_number:phone(String(fd.get('whatsapp_number'))),email:String(fd.get('email')).trim(),remarks:String(fd.get('remarks')).trim(),service_type:String(fd.get('service_type')).trim(),issue_date:today,active_date:String(fd.get('active_date')),expiry_date:String(fd.get('expiry_date'))||plusYear(String(fd.get('active_date'))),source:'SecureTrack System'}};
 async function saveDraft(e:FormEvent<HTMLFormElement>){e.preventDefault();const value=data(e.currentTarget);await addDoc(collection(db,'certificates'),{...value,status:'Draft',created_by:userName,created_by_uid:userId,created_at:serverTimestamp()});setNotice('Certificate draft saved.');setView('list')}
 async function issue(e:FormEvent<HTMLFormElement>){e.preventDefault();const value=data(e.currentTarget);let issued:Certificate|null=null,issuedNumber=0;await runTransaction(db,async tx=>{const counter=doc(db,'counters','certificates'),snap=await tx.get(counter),next=Math.max(Number(snap.data()?.value||151129),151129)+1,ref=doc(collection(db,'certificates'));tx.set(counter,{value:next,updated_at:serverTimestamp()},{merge:true});const record={...value,tracker_id:next,status:'Issued',created_by:userName,created_by_uid:userId,issued_by:userName,issued_by_uid:userId,created_at:serverTimestamp(),issued_at:serverTimestamp()};tx.set(ref,record);issuedNumber=next;issued={id:ref.id,...record} as Certificate});setPreview(issued);setNotice(`Certificate ${issuedNumber} issued.`);setView('list')}
 const send=(c:Certificate)=>{if(!c.whatsapp_number){setNotice('WhatsApp number is not available for this customer.');return}const msg=`Dear ${c.contact_person||c.company_name},\nPlease find your SecureTrack Certificate of Installation for:\nVehicle: ${c.vehicle_number}\nCertificate / Tracker ID: ${c.tracker_id}\nRegards,\nSecureTrack GPS Trading L.L.C.`;window.open(`https://wa.me/${c.whatsapp_number}?text=${encodeURIComponent(msg)}`,'_blank')};
 const canIssue=['master_admin','admin','manager'].includes(role);
 return <div className="stack certificates-page"><section className="panel agreement-hero"><div><span className="eyebrow">CERTIFICATES</span><h1>Installation certificates<span className="accent">.</span></h1><p>Create, issue and retain controlled certificate records.</p></div>{canIssue&&<button className="primary" onClick={()=>setView(view==='create'?'list':'create')}><Plus/>{view==='create'?'Issued certificates':'Create certificate'}</button>}</section>{notice&&<div className="notice success">{notice}</div>}
 <div className="metrics"><div className="metric"><span>TOTAL</span><strong>{counts.total}</strong></div><div className="metric"><span>ISSUED</span><strong>{counts.issued}</strong></div><div className="metric"><span>DRAFTS</span><strong>{counts.draft}</strong></div><div className="metric"><span>VOID</span><strong>{counts.void}</strong></div></div>
 {view==='create'?<CertificateForm onDraft={saveDraft} onIssue={issue}/>:<section className="panel"><div className="section-label"><div><h2>Certificate inventory</h2><p>New tracker IDs begin at 151130 and are allocated atomically.</p></div></div><div className="table-wrap"><table><thead><tr><th>Tracker ID</th><th>Company</th><th>Vehicle</th><th>Chassis</th><th>Issue date</th><th>Issued by</th><th>Status</th><th/></tr></thead><tbody>{rows.map(c=><tr key={c.id}><td>{c.tracker_id||'Draft'}</td><td>{c.company_name}</td><td>{c.vehicle_number}</td><td>{c.chassis_number}</td><td>{c.issue_date}</td><td>{c.issued_by||'—'}</td><td><span className={'badge '+(c.status==='Issued'?'good':c.status==='Void'?'danger':'warning')}>{c.status}</span></td><td><button className="text-button" onClick={()=>setPreview(c)}>View</button>{c.status==='Issued'&&<button className="text-button" onClick={()=>send(c)}><MessageCircle/>WhatsApp</button>}</td></tr>)}</tbody></table>{!rows.length&&<div className="empty">No certificates yet.</div>}</div></section>}
 {preview&&<div className="modal-backdrop"><section className="job-detail-modal certificate-modal"><header><h2>Certificate {preview.tracker_id||'draft'}</h2><button className="icon-button" onClick={()=>setPreview(null)}>×</button></header><CertificatePage certificate={preview}/><div className="form-footer"><button className="secondary" onClick={()=>downloadCertificatePdf(preview)}><Download/>Download PDF</button>{preview.status==='Issued'&&<button className="primary" onClick={()=>send(preview)}><MessageCircle/>Send via WhatsApp</button>}</div></section></div>}</div>
}

function CertificateForm({onDraft,onIssue}:{onDraft:(e:any)=>void;onIssue:(e:any)=>void}){const today=new Date().toISOString().slice(0,10);return <form className="panel agreement-form"><h2>Create certificate</h2><div className="form-row"><label>Customer / company<input name="company_name" required/></label><label>Vehicle number<input name="vehicle_number" required placeholder="Z/55827"/></label><label>Chassis number<input name="chassis_number" required/></label></div><div className="form-row"><label>Device type<input name="device_type" placeholder="FMC150"/></label><label>Service type<select name="service_type"><option>NEW</option><option>RENEW</option></select></label><label>Contact person<input name="contact_person"/></label></div><div className="form-row"><label>WhatsApp number<input name="whatsapp_number"/></label><label>Email<input name="email" type="email"/></label></div><div className="form-row"><label>Issue date<input name="issue_date" type="date" defaultValue={today} required/></label><label>Active date<input name="active_date" type="date" defaultValue={today} required/></label><label>Expiry date<input name="expiry_date" type="date" defaultValue={plusYear(today)} required/></label></div><label>Remarks<textarea name="remarks"/></label><div className="form-footer"><button type="button" className="secondary" onClick={e=>{const form=e.currentTarget.form!;if(form.reportValidity())onDraft({preventDefault(){},currentTarget:form})}}><FileCheck2/>Save draft</button><button type="button" className="primary" onClick={e=>{const form=e.currentTarget.form!;if(form.reportValidity())onIssue({preventDefault(){},currentTarget:form})}}><FileCheck2/>Issue certificate</button></div></form>}
export function CertificatePage({certificate:c}:{certificate:Certificate}){return <article className="certificate-page"><svg viewBox="0 0 1684 1191" role="img" aria-label={`Certificate for vehicle ${c.vehicle_number}`}><defs><clipPath id="certificate-detail-window"><rect x="545" y="590" width="650" height="150"/></clipPath></defs><image href="/certificate-assets/certificate-canva-template.png?v=canva" width="1684" height="1191"/><rect x="96" y="72" width="1490" height="27" fill="#fff"/><rect x="545" y="590" width="650" height="150" fill="#fff"/><image href="/certificate-assets/securetrack-watermark.png?v=exact" x="195" y="350" width="1210" height="415" opacity=".145" preserveAspectRatio="xMidYMid meet" clipPath="url(#certificate-detail-window)"/><rect x="105" y="936" width="570" height="155" fill="#fff"/><text x="125" y="91" className="certificate-running-head">{certificateTime(c)}</text><text x="842" y="91" textAnchor="middle" className="certificate-running-head">Vehicle: {c.vehicle_number||'—'}/Certificate</text><g className="certificate-details"><text x="835" y="632" textAnchor="end">TRACKER ID:</text><text x="855" y="632">{c.tracker_id||'PREVIEW'}</text><text x="835" y="677" textAnchor="end">CHASSIS NO:</text><text x="855" y="677">{c.chassis_number||'—'}</text><text x="835" y="722" textAnchor="end">VEHICLE NO:</text><text x="855" y="722">{c.vehicle_number||'—'}</text></g><g className="certificate-dates"><text x="160" y="982">ACTIVE:</text><text x="305" y="982">{pretty(c.active_date)}</text><text x="160" y="1027">EXPIRY:</text><text x="305" y="1027">{pretty(c.expiry_date)}</text><text x="110" y="1072">ISSUE DATE:</text><text x="305" y="1072">{pretty(c.issue_date)}</text></g></svg></article>}

const loadImage=(src:string)=>new Promise<HTMLImageElement>((resolve,reject)=>{const image=new Image();image.onload=()=>resolve(image);image.onerror=reject;image.src=src});
async function certificateJpeg(c:Certificate){const canvas=document.createElement('canvas');canvas.width=1684;canvas.height=1191;const x=canvas.getContext('2d')!,[template,watermark]=await Promise.all(['/certificate-assets/certificate-canva-template.png?v=canva','/certificate-assets/securetrack-watermark.png?v=exact'].map(loadImage));x.drawImage(template,0,0,1684,1191);x.fillStyle='#fff';x.fillRect(96,72,1490,27);x.fillRect(545,590,650,150);x.save();x.beginPath();x.rect(545,590,650,150);x.clip();x.globalAlpha=.145;x.drawImage(watermark,195,350,1210,415);x.restore();x.fillStyle='#fff';x.fillRect(105,936,570,155);x.fillStyle='#090909';x.font='700 11px Arial, sans-serif';x.textAlign='left';x.fillText(certificateTime(c),125,91);x.textAlign='center';x.fillText(`Vehicle: ${c.vehicle_number||'—'}/Certificate`,842,91);x.font='700 34px Arial, sans-serif';x.textAlign='right';x.fillText('TRACKER ID:',835,632);x.fillText('CHASSIS NO:',835,677);x.fillText('VEHICLE NO:',835,722);x.textAlign='left';x.fillText(String(c.tracker_id||'PREVIEW'),855,632);x.fillText(c.chassis_number||'—',855,677);x.fillText(c.vehicle_number||'—',855,722);x.font='700 31px Arial, sans-serif';x.fillText('ACTIVE:',160,982);x.fillText(pretty(c.active_date),305,982);x.fillText('EXPIRY:',160,1027);x.fillText(pretty(c.expiry_date),305,1027);x.fillText('ISSUE DATE:',110,1072);x.fillText(pretty(c.issue_date),305,1072);return canvas.toDataURL('image/jpeg',.98)}
function jpegPdf(dataUrl:string,width:number,height:number){const binary=atob(dataUrl.split(',')[1]),image=new Uint8Array(binary.length);for(let i=0;i<binary.length;i++)image[i]=binary.charCodeAt(i);const enc=new TextEncoder(),parts:Uint8Array[]=[enc.encode('%PDF-1.4\n%PDFDATA\n')],offsets:number[]=[0];let size=parts[0].length;const add=(id:number,head:string,body?:Uint8Array,tail='\nendobj\n')=>{offsets[id]=size;const a=enc.encode(`${id} 0 obj\n${head}`);parts.push(a);size+=a.length;if(body){parts.push(body);size+=body.length}const z=enc.encode(tail);parts.push(z);size+=z.length};add(1,'<< /Type /Catalog /Pages 2 0 R >>');add(2,'<< /Type /Pages /Kids [3 0 R] /Count 1 >>');add(3,'<< /Type /Page /Parent 2 0 R /MediaBox [0 0 842 595.5] /Resources << /XObject << /Im0 4 0 R >> >> /Contents 5 0 R >>');add(4,`<< /Type /XObject /Subtype /Image /Width ${width} /Height ${height} /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /DCTDecode /Length ${image.length} >>\nstream\n`,image,'\nendstream\nendobj\n');const content=enc.encode('q\n842 0 0 595.5 0 0 cm\n/Im0 Do\nQ\n');add(5,`<< /Length ${content.length} >>\nstream\n`,content,'endstream\nendobj\n');const xref=size;let table='xref\n0 6\n0000000000 65535 f \n';for(let i=1;i<=5;i++)table+=String(offsets[i]).padStart(10,'0')+' 00000 n \n';const end=enc.encode(table+`trailer\n<< /Size 6 /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`);parts.push(end);return new Blob(parts,{type:'application/pdf'})}
export async function downloadCertificatePdf(c:Certificate){const jpeg=await certificateJpeg(c),blob=jpegPdf(jpeg,1684,1191);await saveDownload(blob,`SecureTrack-Certificate-${c.tracker_id||'Draft'}-${(c.vehicle_number||'Vehicle').replace(/[^a-z0-9]+/gi,'-')}.pdf`,'SecureTrack certificate')}









