import { useMemo, useState } from 'react';
import { Attendance, Installation, JOB_TYPES, JobType, Shift, Technician, completionActor, jobLabel, jobReference } from '../types';
import { dayKey, displayTime } from '../lib/domain';
import { JobDetailModal } from './JobDetailModal';

export function CompletedJobsPanel({shifts,installations,attendance,technicians}:{shifts:Shift[];installations:Installation[];attendance:Attendance[];technicians:Technician[]}){
 const today=dayKey(new Date());const month=today.slice(0,7)+'-01';
 const [from,setFrom]=useState(month);const [to,setTo]=useState(today);const [tech,setTech]=useState('all');const [type,setType]=useState<'all'|JobType>('all');const [search,setSearch]=useState('');const [page,setPage]=useState(1);const [selected,setSelected]=useState<Shift|null>(null);const pageSize=20;
 const rows=useMemo(()=>shifts.map(shift=>({shift,installation:installations.find(i=>i.shift_id===shift.id||i.id===shift.id)})).filter((row):row is {shift:Shift;installation:Installation}=>!!row.installation).filter(({shift,installation})=>{const date=dayKey(installation.completed_at||installation.timestamp);const text=[jobReference(shift),shift.id,shift.company_name,shift.customer_name,shift.vehicle_number,...(shift.vehicle_numbers||[]),...(installation.device_imeis||[]),...(installation.sim_numbers||[])].join(' ').toLowerCase();return date>=from&&date<=to&&(tech==='all'||shift.technician_id===tech)&&(type==='all'||shift.job_type===type)&&text.includes(search.trim().toLowerCase())}).sort((a,b)=>(b.installation.completed_at||b.installation.timestamp).localeCompare(a.installation.completed_at||a.installation.timestamp)),[shifts,installations,from,to,tech,type,search]);
 const pages=Math.max(1,Math.ceil(rows.length/pageSize));const visible=rows.slice((Math.min(page,pages)-1)*pageSize,Math.min(page,pages)*pageSize);
 function changed(){setPage(1)}
 return <><section className="panel filter-strip"><div className="section-label"><div><h2>Completed jobs</h2><p>Search every completed assignment and open its full record.</p></div><span>{rows.length} jobs</span></div><div className="filter-grid"><label>From<input type="date" value={from} onChange={e=>{setFrom(e.target.value);changed()}}/></label><label>To<input type="date" value={to} onChange={e=>{setTo(e.target.value);changed()}}/></label><label>Technician<select value={tech} onChange={e=>{setTech(e.target.value);changed()}}><option value="all">All technicians</option>{technicians.map(t=><option key={t.uid} value={t.uid}>{t.displayName||t.email}</option>)}</select></label><label>Job type<select value={type} onChange={e=>{setType(e.target.value as 'all'|JobType);changed()}}><option value="all">All job types</option>{JOB_TYPES.map(t=><option key={t} value={t}>{jobLabel(t)}</option>)}</select></label><label className="detail-wide">Search<input value={search} onChange={e=>{setSearch(e.target.value);changed()}} placeholder="Job ID, IMEI, SIM, customer or vehicle"/></label></div></section><section className="panel"><div className="table-wrap"><table className="clickable-table"><thead><tr><th>Job ID</th><th>Job type</th><th>Customer</th><th>Technician</th><th>Assigned at</th><th>Arrived at</th><th>Completed at</th><th>Completed by</th><th>IMEI</th><th>SIM</th><th>Status</th></tr></thead><tbody>{visible.map(({shift,installation})=>{const arrived=attendance.find(a=>a.id===shift.id);return <tr key={shift.id} tabIndex={0} onClick={()=>setSelected(shift)} onKeyDown={e=>{if(e.key==='Enter')setSelected(shift)}}><td>{jobReference(shift)}</td><td>{jobLabel(shift.job_type)}</td><td>{shift.company_name||shift.site_name}</td><td>{shift.technician_name}</td><td>{displayTime(shift.assigned_at||shift.scheduled_at,shift.timezone)}</td><td>{arrived?displayTime(arrived.timestamp,shift.timezone):'—'}</td><td>{displayTime(installation.completed_at||installation.timestamp,shift.timezone)}</td><td>{completionActor(installation)}</td><td>{installation.device_imeis?.join(' · ')||'—'}</td><td>{installation.sim_numbers?.join(' · ')||'—'}</td><td><span className="badge good">Completed</span></td></tr>})}</tbody></table>{!visible.length&&<div className="empty">No completed jobs match these filters.</div>}</div><div className="pagination"><button className="secondary" disabled={page<=1} onClick={()=>setPage(p=>p-1)}>Previous</button><span>Page {Math.min(page,pages)} of {pages}</span><button className="secondary" disabled={page>=pages} onClick={()=>setPage(p=>p+1)}>Next</button></div></section>{selected&&<JobDetailModal shift={selected} installation={installations.find(i=>i.shift_id===selected.id||i.id===selected.id)} attendance={attendance.find(a=>a.id===selected.id)} onClose={()=>setSelected(null)}/>}</>;
}
