import { FormEvent, useEffect, useState } from 'react';
import { addDoc, collection, doc, onSnapshot, orderBy, query, runTransaction, serverTimestamp, updateDoc } from 'firebase/firestore';
import { Archive, Cpu, Pencil, Plus, Power } from 'lucide-react';
import { db } from '../lib/firebase';

export type DeviceModelRecord={id:string;name:string;status:'active'|'inactive'|'archived';created_at?:unknown;updated_at?:unknown};
export function useDeviceModels(includeInactive=false){const[models,setModels]=useState<DeviceModelRecord[]>([]);useEffect(()=>onSnapshot(query(collection(db,'device_models'),orderBy('name')),snap=>setModels(snap.docs.map(d=>({id:d.id,...d.data()} as DeviceModelRecord)))),[]);return includeInactive?models:models.filter(m=>m.status==='active')}

export function DeviceManagement({userId,userName}:{userId:string;userName:string}){
 const models=useDeviceModels(true),[editing,setEditing]=useState<DeviceModelRecord|null>(null),[adding,setAdding]=useState(false),[notice,setNotice]=useState(''),[error,setError]=useState('');
 async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();setError('');const fd=new FormData(e.currentTarget),name=String(fd.get('name')||'').trim(),status=String(fd.get('status')||'active') as DeviceModelRecord['status'];if(!name)return;try{if(editing)await updateDoc(doc(db,'device_models',editing.id),{name,status,updated_at:serverTimestamp(),updated_by:userName,updated_by_uid:userId});else{await addDoc(collection(db,'device_models'),{name,status,created_at:serverTimestamp(),created_by:userName,created_by_uid:userId,updated_at:serverTimestamp(),updated_by:userName,updated_by_uid:userId});await runTransaction(db,async tx=>{const stockRef=doc(db,'company_inventory','global'),stock=await tx.get(stockRef);if(stock.exists()){const balance={...(stock.data().balance||{})};if(balance[name]===undefined)balance[name]=0;tx.update(stockRef,{balance,updated_at:serverTimestamp(),updated_by:userName,updated_by_uid:userId})}})}setNotice(editing?'Device model updated.':'Device model added to the catalogue and office stock.');setEditing(null);setAdding(false)}catch(err:any){setError(err.message)}}
 async function change(model:DeviceModelRecord,status:DeviceModelRecord['status']){setError('');try{await updateDoc(doc(db,'device_models',model.id),{status,updated_at:serverTimestamp(),updated_by:userName,updated_by_uid:userId});setNotice(status==='archived'?'Device archived. Historical references remain unchanged.':`Device marked ${status}.`)}catch(err:any){setError(err.message)}}
 return <div className="stack"><section className="panel agreement-hero"><div><span className="eyebrow">ADMINISTRATION</span><h1>Device management<span className="accent">.</span></h1><p>Control which GPS models are available for new records without changing historical data.</p></div><button className="primary" onClick={()=>{setEditing(null);setAdding(true)}}><Plus/>Add Device</button></section>{notice&&<div className="notice success">{notice}</div>}{error&&<div className="notice error">{error}</div>}
 <section className="panel"><div className="section-label"><div><h2>Device catalogue</h2><p>Inactive and archived models stay attached to existing certificates and jobs.</p></div><span>{models.filter(m=>m.status==='active').length} active</span></div><div className="device-catalogue">{models.map(model=><article key={model.id} className="device-model-card"><div className="icon-box"><Cpu/></div><div className="grow"><h3>{model.name}</h3><span className={'badge '+(model.status==='active'?'good':model.status==='inactive'?'warning':'')}>{model.status}</span></div><button className="record-action edit" onClick={()=>{setEditing(model);setAdding(true)}}><Pencil/>Edit</button>{model.status==='active'?<button className="secondary" onClick={()=>change(model,'inactive')}><Power/>Deactivate</button>:model.status==='inactive'?<button className="secondary" onClick={()=>change(model,'active')}><Power/>Activate</button>:null}{model.status!=='archived'&&<button className="text-button danger-text" onClick={()=>change(model,'archived')}><Archive/>Archive</button>}</article>)}{!models.length&&<div className="empty">No device models yet. Use Add Device to create the first model.</div>}</div></section>
 {adding&&<div className="modal-backdrop"><form className="job-detail-modal" onSubmit={save}><header><div><span className="eyebrow">DEVICE MODEL</span><h2>{editing?'Edit device':'Add device'}</h2></div><button type="button" className="icon-button" onClick={()=>setAdding(false)}>×</button></header><label>Device model name<input name="name" required defaultValue={editing?.name||''} placeholder="FMC150"/></label><label>Status<select name="status" defaultValue={editing?.status||'active'}><option value="active">Active</option><option value="inactive">Inactive</option><option value="archived">Archived</option></select></label><div className="form-footer"><button type="button" className="secondary" onClick={()=>setAdding(false)}>Cancel</button><button className="primary">Save device</button></div></form></div>}</div>
}
