import { useEffect, useMemo, useState } from 'react';
import { collection, endAt, getDocs, limit, orderBy, query as firestoreQuery, startAt, where } from 'firebase/firestore';
import { FileCheck2, Search, Wrench } from 'lucide-react';
import { db } from '../lib/firebase';
import { Installation, Shift, jobReference } from '../types';

const normalized=(value:any)=>String(value??'').trim().toLowerCase();
type Result={id:string;term:string;title:string;meta:string;kind:'job'|'certificate'};
export function GlobalSearch({shifts,installations,onOpen}:{shifts:Shift[];installations:Installation[];onOpen:(term:string)=>void}){
 const [query,setQuery]=useState(''),[focused,setFocused]=useState(false),[certificates,setCertificates]=useState<any[]>([]);
 useEffect(()=>{const term=query.trim();if(term.length<2){setCertificates([]);return}let active=true;const timer=window.setTimeout(async()=>{try{const candidates=[term,term.toUpperCase()],requests:any[]=[];for(const value of candidates){requests.push(getDocs(firestoreQuery(collection(db,'certificates'),where('vehicle_number','==',value),limit(5))),getDocs(firestoreQuery(collection(db,'certificates'),where('chassis_number','==',value),limit(5))),getDocs(firestoreQuery(collection(db,'certificates'),orderBy('company_name'),startAt(value),endAt(value+'\uf8ff'),limit(5))))}if(/^\d+$/.test(term))requests.push(getDocs(firestoreQuery(collection(db,'certificates'),where('tracker_id','==',Number(term)),limit(5))));const snapshots=await Promise.all(requests),found=new Map<string,any>();snapshots.forEach(snapshot=>snapshot.docs.forEach((item:any)=>found.set(item.id,{id:item.id,...item.data()})));if(active)setCertificates([...found.values()].filter(row=>!row.is_deleted))}catch{if(active)setCertificates([])}},250);return()=>{active=false;window.clearTimeout(timer)}},[query]);
 const results=useMemo(()=>{const needle=normalized(query);if(needle.length<2)return[];const rows:Result[]=[];
  for(const shift of shifts){const completions=installations.filter(item=>item.shift_id===shift.id||item.id===shift.id),values=[jobReference(shift),shift.id,shift.company_name,shift.customer_name,shift.vehicle_number,...(shift.vehicle_numbers||[]),...completions.flatMap(item=>[item.vehicle_ref,...(item.device_imeis||[]),...(item.sim_numbers||[])])];if(!values.some(value=>normalized(value).includes(needle)))continue;const vehicle=(shift.vehicle_numbers?.length?shift.vehicle_numbers:[shift.vehicle_number]).filter(Boolean).join(' · ');rows.push({id:`job-${shift.id}`,term:jobReference(shift),title:`${jobReference(shift)} · ${shift.company_name||shift.customer_name||shift.site_name}`,meta:`${vehicle||'No vehicle'} · ${shift.technician_name}`,kind:'job'})}
  for(const certificate of certificates){const values=[certificate.company_name,certificate.vehicle_number,certificate.chassis_number,certificate.tracker_id,certificate.device_imei,certificate.sim_number];if(!values.some(value=>normalized(value).includes(needle)))continue;rows.push({id:`certificate-${certificate.id}`,term:String(certificate.vehicle_number||certificate.tracker_id||certificate.company_name||query),title:`${certificate.vehicle_number||'Certificate'} · ${certificate.company_name||'Unknown company'}`,meta:`Chassis ${certificate.chassis_number||'—'} · Tracker ${certificate.tracker_id||'—'}`,kind:'certificate'})}
  return rows.slice(0,8)},[query,shifts,installations,certificates]);
 function open(result?:Result){const term=result?.term||query.trim();if(!term)return;sessionStorage.setItem('securetrack:vehicle-search',term);window.dispatchEvent(new CustomEvent('securetrack:vehicle-search',{detail:term}));setFocused(false);onOpen(term)}
 return <div className="global-search"><Search/><input aria-label="Global search" value={query} onFocus={()=>setFocused(true)} onBlur={()=>window.setTimeout(()=>setFocused(false),160)} onChange={event=>setQuery(event.target.value)} onKeyDown={event=>{if(event.key==='Enter'){event.preventDefault();open(results[0])}}} placeholder="Search vehicle, company, IMEI, SIM, Job ID or chassis"/>{focused&&query.trim().length>=2&&<div className="global-search-results">{results.map(result=><button key={result.id} onMouseDown={event=>event.preventDefault()} onClick={()=>open(result)}><span className={`global-search-kind ${result.kind}`}>{result.kind==='certificate'?<FileCheck2/>:<Wrench/>}</span><span><strong>{result.title}</strong><small>{result.meta}</small></span></button>)}{!results.length&&<div className="empty">No matching records</div>}</div>}</div>;
}
