import { ChangeEvent, useState } from 'react';
import ExcelJS from 'exceljs';
import { DEVICE_MODELS, emptyStock, Stock, Technician } from '../types';
import { adjustInventory } from '../lib/data';
import { saveDownload } from '../lib/download';

const columns=['Technician name','Technician email',...DEVICE_MODELS,'SIM Etisalat','SIM du','SIM International','SIM'];
export function InventoryImport({technicians,balances,onDone}:{technicians:Technician[];balances:{tech:Technician;stock:Stock|null}[];onDone:()=>void}){
 const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');
 async function template(){const b=new ExcelJS.Workbook();const s=b.addWorksheet('Inventory import');s.addRow(columns);s.addRow(['Example Technician','technician@example.com',0,0,0,0,0,0,0,0,0,0,0,0]);s.getRow(1).font={bold:true,color:{argb:'FFFFFFFF'}};s.getRow(1).fill={type:'pattern',pattern:'solid',fgColor:{argb:'FF146B50'}};s.columns=columns.map(key=>({width:Math.max(16,key.length+2)}));await saveDownload(new Blob([await b.xlsx.writeBuffer()],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'}),'SecureTrack_Inventory_Import_Template.xlsx','SecureTrack inventory template')}
 async function upload(e:ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0];if(!file)return;setBusy(true);setMessage('');try{const b=new ExcelJS.Workbook();await b.xlsx.load(await file.arrayBuffer());const sheet=b.worksheets[0];const headers=(sheet.getRow(1).values as any[]).map(v=>String(v||'').trim());let changed=0;for(let n=2;n<=sheet.rowCount;n++){const row=sheet.getRow(n);const name=String(row.getCell(headers.indexOf('Technician name')+1).value||'').trim();const email=String(row.getCell(headers.indexOf('Technician email')+1).value||'').trim().toLowerCase();if(!name&&!email)continue;const tech=technicians.find(t=>(email&&t.email.toLowerCase()===email)||(!email&&(t.displayName||'').toLowerCase()===name.toLowerCase()));if(!tech)throw new Error(`Row ${n}: technician not found.`);const current=balances.find(x=>x.tech.uid===tech.uid)?.stock||emptyStock();const target={...current};for(const key of Object.keys(target)){const col=headers.indexOf(key);if(col>=0){const value=Number(row.getCell(col+1).value);if(!Number.isFinite(value)||value<0)throw new Error(`Row ${n}: ${key} must be zero or more.`);target[key as keyof Stock]=value}}await adjustInventory(tech,current,target,'Excel inventory import');changed++}setMessage(`${changed} technician inventory record${changed===1?'':'s'} updated.`);onDone()}catch(err:any){setMessage(err.message||'Import failed.')}finally{setBusy(false);e.target.value=''}}
 return <section className="panel inventory-import"><div><h2>Import inventory from Excel</h2><p>Download the sample, fill quantities by technician, then upload it. Every change is recorded as an inventory adjustment.</p></div><div className="form-footer"><button type="button" className="secondary" onClick={template}>Download Excel sample</button><label className="primary upload-button">{busy?'Importing…':'Upload inventory Excel'}<input disabled={busy} type="file" accept=".xlsx" onChange={upload}/></label></div>{message&&<div className="notice info">{message}</div>}</section>
}
