import { FormEvent, useEffect, useState } from 'react';
import { Bell, Camera, Check, KeyRound, LogOut, Settings } from 'lucide-react';
import { EmailAuthProvider, reauthenticateWithCredential, signOut, updatePassword } from 'firebase/auth';
import { Technician } from '../types';
import { auth } from '../lib/firebase';
import { changeProfilePhoto } from '../lib/data';
import { prepareProfilePhoto } from '../lib/photo';
import { Capacitor } from '@capacitor/core';
import { notificationState, notificationsMuted, readNotificationState, requestNotifications, setNotificationsMuted } from '../lib/notifications';

export function ProfileSettings({ profile, compact = false }: { profile: Technician; compact?: boolean }) {
  const [current, setCurrent] = useState(''); const [next, setNext] = useState(''); const [confirm, setConfirm] = useState('');
  const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [notice, setNotice] = useState('');
  const [notifications, setNotifications] = useState(notificationState()); const [muted, setMuted] = useState(notificationsMuted());
  const [passwordOpen, setPasswordOpen] = useState(false);
  const enabled = notifications === 'granted' && !muted; const nativeAndroid = Capacitor.getPlatform() === 'android';
  const notificationTitle = enabled ? 'Notifications are on' : notifications === 'denied' ? 'Permission is blocked' : notifications === 'unsupported' ? 'Not available on this device' : 'Turn on notifications';
  const notificationCopy = enabled ? 'You will receive SecureTrack job, stock and workday alerts.' : notifications === 'denied' ? 'Allow notifications in your device settings, then return here.' : 'Allow SecureTrack to send important job and stock alerts.';

  useEffect(()=>{void readNotificationState().then(setNotifications)},[]);

  async function photo(file?: File) { if (!file) return; setBusy(true); setError(''); setNotice(''); try { await changeProfilePhoto(profile.uid, await prepareProfilePhoto(file)); setNotice('Profile picture updated.'); } catch (e: any) { setError(e.message); } finally { setBusy(false); } }
  async function password(e: FormEvent) { e.preventDefault(); setError(''); setNotice(''); if (next.length < 8) { setError('The new password must contain at least 8 characters.'); return; } if (next !== confirm) { setError('The new passwords do not match.'); return; } const user = auth.currentUser; if (!user?.email) { setError('Please sign in again.'); return; } setBusy(true); try { await reauthenticateWithCredential(user, EmailAuthProvider.credential(user.email, current)); await updatePassword(user, next); setCurrent(''); setNext(''); setConfirm(''); setNotice('Password changed successfully.'); } catch (e: any) { setError(e.code === 'auth/invalid-credential' ? 'The current password is incorrect.' : e.message); } finally { setBusy(false); } }
  async function toggleNotifications() { setError(''); setNotice(''); if (enabled) { setNotificationsMuted(true); setMuted(true); setNotice('App notifications paused.'); return; } const state = await requestNotifications(); setNotifications(state); if (state === 'granted') { setNotificationsMuted(false); setMuted(false); setNotice('App notifications enabled.'); } else if (state === 'denied') setError('Notifications are blocked in the device settings for SecureTrack.'); else if (state === 'unsupported') setError('Install SecureTrack as an app to enable notifications on this device.'); }

  return <div className="stack settings-stack">
    {!compact && <div className="page-heading"><div><span className="eyebrow">MY ACCOUNT</span><h1>Settings<span className="accent">.</span></h1><p>Manage your SecureTrack profile, notifications and password.</p></div></div>}
    {error && <div className="notice error">{error}</div>}{notice && <div className="notice success"><Check />{notice}</div>}
    <section className="panel settings-profile"><div className="section-title"><div className="icon-box"><Settings /></div><div><h2>Profile</h2><p>Your photo and account details.</p></div></div><div className="settings-photo-row"><div className="avatar settings-avatar">{profile.photoDataUrl ? <img src={profile.photoDataUrl} alt="Profile" /> : (profile.displayName || profile.email).slice(0, 2).toUpperCase()}</div><div><strong>{profile.displayName || profile.email}</strong><span>{profile.email}</span></div><label className="secondary photo-button"><Camera />Update photo<input type="file" accept="image/*" disabled={busy} onChange={e => { void photo(e.target.files?.[0]); e.target.value = ''; }} /></label></div></section>
    <section className="panel settings-notification-panel"><div className="settings-card-heading"><div className="icon-box"><Bell /></div><div><span className="eyebrow">PREFERENCES</span><h2>Stay informed</h2><p>Control how SecureTrack keeps you updated during the workday.</p></div></div><div className="settings-notification-row"><div className="notification-symbol"><Bell /></div><div className="notification-copy"><div className="notification-line"><strong>App notifications</strong><span className={enabled ? 'notification-status on' : 'notification-status'}>{enabled ? 'Enabled' : 'Off'}</span></div><span>{enabled ? 'Jobs, stock movements and workday alerts are enabled.' : notificationCopy}</span></div>{nativeAndroid ? <button type="button" role="switch" aria-label="Toggle SecureTrack notifications" aria-checked={enabled} className="ios-switch" disabled={notifications === 'unsupported'} onClick={toggleNotifications}><span /></button> : <button type="button" className="secondary notification-desktop-action" disabled={notifications === 'unsupported'} onClick={toggleNotifications}>{enabled ? 'Turn off' : 'Turn on'}</button>}</div></section>
    <section className={'panel password-panel '+(passwordOpen?'open':'')}><div className="section-title"><div className="icon-box"><KeyRound /></div><div><h2>Password & security</h2><p>Update your password whenever you need to.</p></div><button type="button" className="secondary password-toggle" onClick={()=>setPasswordOpen(open=>!open)}>{passwordOpen?'Close':'Change password'}</button></div>{passwordOpen&&<form onSubmit={password}><label>Current password<input required type="password" autoComplete="current-password" value={current} onChange={e => setCurrent(e.target.value)} /></label><div className="form-row"><label>New password<input required minLength={8} type="password" autoComplete="new-password" value={next} onChange={e => setNext(e.target.value)} /></label><label>Confirm new password<input required minLength={8} type="password" autoComplete="new-password" value={confirm} onChange={e => setConfirm(e.target.value)} /></label></div><button className="primary" disabled={busy}><KeyRound />{busy ? 'Saving…' : 'Update password'}</button></form>}<button type="button" className="settings-signout" onClick={()=>signOut(auth)}><LogOut />Sign out</button></section>
  </div>;
}

