import { FormEvent, useState } from 'react';
import { Bell, Camera, Check, KeyRound, Settings } from 'lucide-react';
import { EmailAuthProvider, reauthenticateWithCredential, updatePassword } from 'firebase/auth';
import { Technician } from '../types';
import { auth } from '../lib/firebase';
import { changeProfilePhoto } from '../lib/data';
import { prepareProfilePhoto } from '../lib/photo';
import { notificationState, requestNotifications } from '../lib/notifications';

export function ProfileSettings({profile,compact=false}:{profile:Technician;compact?:boolean}){
 const [current,setCurrent]=useState('');const [next,setNext]=useState('');const [confirm,setConfirm]=useState('');const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [notice,setNotice]=useState('');const [notifications,setNotifications]=useState(notificationState());
 async function photo(file?:File){if(!file)return;setBusy(true);setError('');setNotice('');try{const value=await prepareProfilePhoto(file);await changeProfilePhoto(profile.uid,value);setNotice('Profile picture updated.')}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 async function password(e:FormEvent){e.preventDefault();setError('');setNotice('');if(next.length<8){setError('The new password must contain at least 8 characters.');return}if(next!==confirm){setError('The new passwords do not match.');return}const user=auth.currentUser;if(!user?.email){setError('Please sign in again.');return}setBusy(true);try{await reauthenticateWithCredential(user,EmailAuthProvider.credential(user.email,current));await updatePassword(user,next);setCurrent('');setNext('');setConfirm('');setNotice('Password changed successfully.')}catch(e:any){setError(e.code==='auth/invalid-credential'?'The current password is incorrect.':e.message)}finally{setBusy(false)}}
 async function enableNotifications(){setError('');const state=await requestNotifications();setNotifications(state);if(state==='granted')setNotice('App notifications enabled.');else if(state==='denied')setError('Notifications are blocked in the device settings for SecureTrack.');else if(state==='unsupported')setError('Install SecureTrack as an app to enable notifications on this device.')}
 return <div className="stack">{!compact&&<div className="page-heading"><div><span className="eyebrow">MY ACCOUNT</span><h1>Settings<span className="accent">.</span></h1><p>Manage your SecureTrack profile, notifications and password.</p></div></div>}{error&&<div className="notice error">{error}</div>}{notice&&<div className="notice success"><Check/>{notice}</div>}<section className="panel settings-profile"><div className="section-title"><div className="icon-box"><Settings/></div><div><h2>Profile picture</h2><p>This picture appears beside your SecureTrack account.</p></div></div><div className="settings-photo-row"><div className="avatar settings-avatar">{profile.photoDataUrl?<img src={profile.photoDataUrl} alt="Profile"/>:(profile.displayName||profile.email).slice(0,2).toUpperCase()}</div><div><strong>{profile.displayName||profile.email}</strong><span>{profile.email}</span></div><label className="secondary photo-button"><Camera/>Choose picture<input type="file" accept="image/*" disabled={busy} onChange={e=>{void photo(e.target.files?.[0]);e.target.value=''}}/></label></div></section><section className="panel"><div className="section-title"><div className="icon-box"><Bell/></div><div><h2>App notifications</h2><p>New jobs, issued inventory, late clock-in, long breaks and late clock-out.</p></div></div><div className="settings-notification-row"><div><strong>{notifications==='granted'?'Notifications enabled':notifications==='denied'?'Notifications blocked':notifications==='unsupported'?'Not supported in this browser':'Permission required'}</strong><span>Alerts use your device’s SecureTrack notification permission.</span></div><button type="button" className="secondary" disabled={notifications==='granted'||notifications==='unsupported'} onClick={enableNotifications}><Bell/>{notifications==='granted'?'Enabled':'Enable notifications'}</button></div></section><section className="panel"><div className="section-title"><div className="icon-box"><KeyRound/></div><div><h2>Change password</h2><p>Confirm your current password before choosing a new one.</p></div></div><form onSubmit={password}><label>Current password<input required type="password" autoComplete="current-password" value={current} onChange={e=>setCurrent(e.target.value)}/></label><div className="form-row"><label>New password<input required minLength={8} type="password" autoComplete="new-password" value={next} onChange={e=>setNext(e.target.value)}/></label><label>Confirm new password<input required minLength={8} type="password" autoComplete="new-password" value={confirm} onChange={e=>setConfirm(e.target.value)}/></label></div><button className="primary" disabled={busy}><KeyRound/>{busy?'Saving…':'Change password'}</button></form></section></div>;
}
