import { useEffect, useMemo, useState } from 'react';
import { collection, limit, onSnapshot, orderBy, query } from 'firebase/firestore';
import { Building2, CarFront, FileCheck2, Mail, MessageCircle, Search, X } from 'lucide-react';
import { db } from '../lib/firebase';
import type { AdminSection } from './AdminDashboard';

type Life='Active'|'Expiring Soon'|'Expired'|'Requires Review'|'Not Recorded';
type Row={id:string;company:string;vehicle:string;chassis:string;imei:string;sim:string;phone:string;email:string;gpsStart:string;gpsExpiry:string;gpsStatus:Life;certificateId:string;certificateNo:string;certificateType:string;certificateIssue:string;certificateExpiry:string;certificateStatus:Life;overall:string;renewalStatus:string};
const norm=(value:any)=>String(value??'').trim().replace(/[^A-Z0-9]/gi,'').toUpperCase();
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Dubai',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const life=(date:any):Life=>{const value=String(date||'').slice(0,10);if(!/^\d{4}-\d{2}-\d{2}$/.test(value))return'Requires Review';const now=today(),soon=new Date(Date.parse(now+'T12:00:00Z')+30*86400000).toISOString().slice(0,10);return value<now?'Expired':value<=soon?'Expiring Soon':'Active'};
const identity=(row:any)=>norm(row.chassis_number)?`C:${norm(row.chassis_number)}`:`V:${norm(row.company_name)}:${norm(row.vehicle_number)}`;
const overall=(gps:Life,cert:Life)=>gps==='Requires Review'||cert==='Requires Review'?'Requires Review':gps==='Expired'&&cert==='Expired'?'GPS & Certificate Expired':gps==='Expired'?'GPS Subscription Expired':cert==='Expired'?'Certificate Expired':gps==='Expiring Soon'&&cert==='Expiring Soon'?'GPS & Certificate Expiring Soon':gps==='Expiring Soon'?'GPS Subscription Expiring Soon':cert==='Expiring Soon'?'Certificate Expiring Soon':gps==='Not Recorded'?'Requires Review':'Active';
const phone=(value:string)=>{let n=String(value||'').replace(/\D/g,'');if(n.startsWith('00'))n=n.slice(2);if(n.startsWith('0'))n='971'+n.slice(1);return n};

export function RenewalControlCenter({onNavigate}:{onNavigate:(section:AdminSection)=>void}){
 const [certificates,setCertificates]=useState<any[]>([]),[renewals,setRenewals]=useState<any[]>([]),[error,setError]=useState(''),[search,setSearch]=useState(''),[gpsFilter,setGpsFilter]=useState(''),[certFilter,setCertFilter]=useState(''),[overallFilter,setOverallFilter]=useState(''),[quickFilter,setQuickFilter]=useState(''),[company,setCompany]=useState(''),[type,setType]=useState(''),[renewalFilter,setRenewalFilter]=useState(''),[includeDeleted,setIncludeDeleted]=useState(false),[from,setFrom]=useState(''),[to,setTo]=useState(''),[sort,setSort]=useState<'company'|'vehicle'|'gps'|'certificate'|'overall'>('company'),[selected,setSelected]=useState<Row|null>(null);
 useEffect(()=>onSnapshot(query(collection(db,'certificates'),orderBy('created_at','desc'),limit(2000)),snapshot=>setCertificates(snapshot.docs.map(item=>({id:item.id,...item.data()}))),e=>setError(e.message)),[]);
 useEffect(()=>onSnapshot(query(collection(db,'renewals'),orderBy('updated_at','desc'),limit(2000)),snapshot=>setRenewals(snapshot.docs.map(item=>({id:item.id,...item.data()}))),e=>setError(e.message)),[]);
 const rows=useMemo(()=>{const certMap=new Map<string,any>();for(const cert of certificates){if(cert.is_deleted&&!includeDeleted)continue;const key=identity(cert),current=certMap.get(key);if(!current||String(cert.expiry_date||'')>String(current.expiry_date||''))certMap.set(key,cert)}const renewalMap=new Map<string,any>();for(const renewal of renewals){if(renewal.is_deleted&&!includeDeleted)continue;const key=identity(renewal),current=renewalMap.get(key);if(!current||String(renewal.expiry_date||'')>String(current.expiry_date||''))renewalMap.set(key,renewal)}const keys=new Set([...certMap.keys(),...renewalMap.keys()]);return[...keys].map(key=>{const c=certMap.get(key)||{},r=renewalMap.get(key)||{},gpsStatus=(r.id?life(r.expiry_date):'Requires Review') as Life,certificateStatus=(c.id?life(c.expiry_date):'Not Recorded') as Life;return{id:key,company:r.company_name||c.company_name||'',vehicle:r.vehicle_number||c.vehicle_number||'',chassis:r.chassis_number||c.chassis_number||'',imei:r.imei||c.software_tracker_id||'',sim:r.sim_number||'',phone:phone(r.contact_number||c.whatsapp_number||''),email:r.email||c.email||'',gpsStart:r.start_date||'',gpsExpiry:r.expiry_date||'',gpsStatus,certificateId:c.id||'',certificateNo:String(c.tracker_id||''),certificateType:c.service_type||c.certificate_type||'',certificateIssue:c.issue_date||'',certificateExpiry:c.expiry_date||'',certificateStatus,overall:overall(gpsStatus,certificateStatus),renewalStatus:r.status||r.lifecycle||''} as Row}).sort((a,b)=>{const value=(row:Row)=>sort==='company'?row.company:sort==='vehicle'?row.vehicle:sort==='gps'?row.gpsExpiry:sort==='certificate'?row.certificateExpiry:row.overall;return value(a).localeCompare(value(b))})},[certificates,renewals,sort,includeDeleted]);
 const visible=useMemo(()=>rows.filter(row=>{const token=norm(search);return(!token||[row.company,row.vehicle,row.chassis,row.imei,row.sim,row.certificateNo,row.phone,row.email].some(value=>norm(value).includes(token)))&&(!gpsFilter||row.gpsStatus===gpsFilter)&&(!certFilter||row.certificateStatus===certFilter)&&(!overallFilter||row.overall===overallFilter)&&(!quickFilter||(quickFilter==='soon'&&(row.gpsStatus==='Expiring Soon'||row.certificateStatus==='Expiring Soon'))||(quickFilter==='renewed'&&norm(row.renewalStatus).includes('RENEW')))&&(!company||row.company===company)&&(!type||row.certificateType===type)&&(!renewalFilter||row.renewalStatus===renewalFilter)&&(!from||[row.gpsExpiry,row.certificateExpiry].some(value=>value>=from))&&(!to||[row.gpsExpiry,row.certificateExpiry].some(value=>value&&value<=to))}),[rows,search,gpsFilter,certFilter,overallFilter,quickFilter,company,type,renewalFilter,from,to]);
 const counts=useMemo(()=>({total:rows.length,active:rows.filter(r=>r.overall==='Active').length,gpsExpired:rows.filter(r=>r.gpsStatus==='Expired').length,certExpired:rows.filter(r=>r.certificateStatus==='Expired').length,bothExpired:rows.filter(r=>r.gpsStatus==='Expired'&&r.certificateStatus==='Expired').length,soon:rows.filter(r=>r.gpsStatus==='Expiring Soon'||r.certificateStatus==='Expiring Soon').length,renewed:rows.filter(r=>norm(r.renewalStatus).includes('RENEW')).length,review:rows.filter(r=>r.overall==='Requires Review').length}),[rows]);
 const clear=()=>{setSearch('');setGpsFilter('');setCertFilter('');setOverallFilter('');setQuickFilter('');setCompany('');setType('');setRenewalFilter('');setIncludeDeleted(false);setFrom('');setTo('')};
 const applyCard=(kind:string)=>{setQuickFilter(kind==='soon'||kind==='renewed'?kind:'');setGpsFilter(kind==='gps-expired'||kind==='both-expired'?'Expired':'');setCertFilter(kind==='cert-expired'||kind==='both-expired'?'Expired':'');setOverallFilter(kind==='active'?'Active':kind==='review'?'Requires Review':'')};
 const card=(label:string,value:number,kind:string)=><button className="metric control-metric" onClick={()=>applyCard(kind)}><span>{label}</span><strong>{value}</strong></button>;
 return <div className="stack control-center">{error&&<div className="notice error">{error}</div>}<section className="panel control-hero"><div><span className="eyebrow">CUSTOMERS · VEHICLES · EXPIRY</span><h1>Renewal & certificate control center<span className="accent">.</span></h1><p>GPS subscription and certificate expiry remain separate, with one operational view for action.</p></div><div className="control-source-actions"><button className="secondary" onClick={()=>onNavigate('renewals')}>Sales import</button><button className="secondary" onClick={()=>onNavigate('certificates')}>Certificates</button></div></section>
 <div className="metrics control-summary">{card('TOTAL VEHICLES',counts.total,'all')}{card('ACTIVE',counts.active,'active')}{card('GPS SUBSCRIPTION EXPIRED',counts.gpsExpired,'gps-expired')}{card('CERTIFICATE EXPIRED',counts.certExpired,'cert-expired')}{card('GPS & CERTIFICATE EXPIRED',counts.bothExpired,'both-expired')}{card('EXPIRING SOON',counts.soon,'soon')}{card('RENEWED',counts.renewed,'renewed')}{card('REQUIRES ATTENTION',counts.review,'review')}</div>
 <section className="panel control-filters"><div className="control-search"><Search/><input aria-label="Search control center" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Company, vehicle, chassis, IMEI, SIM, certificate, phone or email"/></div><div className="filter-grid"><label>GPS subscription<select value={gpsFilter} onChange={e=>{setQuickFilter('');setGpsFilter(e.target.value)}}><option value="">All statuses</option><option>Active</option><option>Expiring Soon</option><option>Expired</option><option>Requires Review</option></select></label><label>Certificate<select value={certFilter} onChange={e=>{setQuickFilter('');setCertFilter(e.target.value)}}><option value="">All statuses</option><option>Active</option><option>Expiring Soon</option><option>Expired</option><option>Requires Review</option></select></label><label>Overall status<select value={overallFilter} onChange={e=>{setQuickFilter('');setOverallFilter(e.target.value)}}><option value="">All statuses</option>{[...new Set(rows.map(r=>r.overall))].sort().map(value=><option key={value}>{value}</option>)}</select></label><label>Company<select value={company} onChange={e=>setCompany(e.target.value)}><option value="">All companies</option>{[...new Set(rows.map(r=>r.company).filter(Boolean))].sort().map(value=><option key={value}>{value}</option>)}</select></label><label>Certificate type<select value={type} onChange={e=>setType(e.target.value)}><option value="">All types</option>{[...new Set(rows.map(r=>r.certificateType).filter(Boolean))].sort().map(value=><option key={value}>{value}</option>)}</select></label><label>Renewal status<select value={renewalFilter} onChange={e=>setRenewalFilter(e.target.value)}><option value="">All statuses</option>{[...new Set(rows.map(r=>r.renewalStatus).filter(Boolean))].sort().map(value=><option key={value}>{value}</option>)}</select></label><label>Expiry from<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>Expiry to<input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label><label>Sort by<select value={sort} onChange={e=>setSort(e.target.value as any)}><option value="company">Company</option><option value="vehicle">Vehicle</option><option value="gps">GPS subscription expiry</option><option value="certificate">Certificate expiry</option><option value="overall">Overall status</option></select></label><label className="control-checkbox"><input type="checkbox" checked={includeDeleted} onChange={e=>setIncludeDeleted(e.target.checked)}/>Include deleted <small>Deleted items remain in their source module.</small></label></div><div className="form-footer"><span>{visible.length} of {rows.length} vehicles{quickFilter?` · ${quickFilter==='soon'?'Expiring soon':'Renewed'}`:''}</span><button className="secondary" onClick={clear}><X/>Clear all</button></div></section>
 <section className="panel control-table-panel"><div className="table-wrap"><table className="control-table"><thead><tr><th>Company / Vehicle</th><th>GPS subscription</th><th>Certificate</th><th>Overall status</th><th>Contact</th><th>Actions</th></tr></thead><tbody>{visible.slice(0,200).map(row=><tr key={row.id}><td><button className="table-link" onClick={()=>setSelected(row)}>{row.company||'Company not recorded'}</button><button className="table-link vehicle" onClick={()=>setSelected(row)}>{row.vehicle||'Vehicle not recorded'}</button><small>{row.chassis||'Chassis not recorded'}</small></td><td><span>{row.gpsExpiry||'Date requires review'}</span><strong className={'badge '+(row.gpsStatus==='Expired'?'danger':row.gpsStatus==='Expiring Soon'||row.gpsStatus==='Requires Review'?'warning':'good')}>{row.gpsStatus==='Active'?'GPS Subscription Active':`GPS Subscription ${row.gpsStatus}`}</strong></td><td><span>{row.certificateNo||'No certificate'} · {row.certificateExpiry||'Date requires review'}</span><strong className={'badge '+(row.certificateStatus==='Expired'?'danger':row.certificateStatus==='Expiring Soon'||row.certificateStatus==='Requires Review'?'warning':'good')}>{row.certificateStatus==='Active'?'Certificate Valid':`Certificate ${row.certificateStatus}`}</strong></td><td><span className={'badge '+(row.overall.includes('Expired')?'danger':row.overall.includes('Soon')||row.overall==='Requires Review'?'warning':'good')}>{row.overall}</span></td><td><div className="record-actions">{row.phone?<a className="record-action" target="_blank" rel="noreferrer" href={`https://wa.me/${row.phone}`}><MessageCircle/>WhatsApp</a>:<small>No Phone</small>}{row.email?<a className="record-action" href={`mailto:${row.email}`}><Mail/>Email</a>:<small>No Email</small>}</div></td><td><div className="record-actions"><button className="record-action" onClick={()=>setSelected(row)}><CarFront/>View vehicle</button>{row.certificateId&&<button className="record-action" onClick={()=>onNavigate('certificates')}><FileCheck2/>View certificate</button>}<button className="record-action" onClick={()=>onNavigate('renewals')}><Building2/>Update renewal</button></div></td></tr>)}</tbody></table>{!visible.length&&<div className="empty">No vehicle records match these filters.</div>}{visible.length>200&&<p className="fine-print">Showing the first 200 matching records. Narrow the filters to find a specific vehicle.</p>}</div></section>
 {selected&&<div className="modal-backdrop"><section className="job-detail-modal control-detail"><header><div><span className="eyebrow">VEHICLE CONTROL RECORD</span><h2>{selected.vehicle||'Vehicle details'}</h2><p>{selected.company}</p></div><button className="icon-button" onClick={()=>setSelected(null)}><X/></button></header><div className="control-detail-grid"><section><h3>Vehicle</h3><p><strong>Company</strong>{selected.company||'—'}</p><p><strong>Vehicle</strong>{selected.vehicle||'—'}</p><p><strong>Chassis</strong>{selected.chassis||'—'}</p><p><strong>IMEI</strong>{selected.imei||'—'}</p><p><strong>SIM</strong>{selected.sim||'—'}</p></section><section><h3>GPS subscription</h3><p><strong>Start date</strong>{selected.gpsStart||'Requires review'}</p><p><strong>Expiry date</strong>{selected.gpsExpiry||'Requires review'}</p><p><strong>Status</strong>{selected.gpsStatus}</p><p><strong>Renewal status</strong>{selected.renewalStatus||'Not recorded'}</p></section><section><h3>Certificate</h3><p><strong>Certificate number</strong>{selected.certificateNo||'—'}</p><p><strong>Type</strong>{selected.certificateType||'—'}</p><p><strong>Issue date</strong>{selected.certificateIssue||'—'}</p><p><strong>Expiry date</strong>{selected.certificateExpiry||'Requires review'}</p><p><strong>Status</strong>{selected.certificateStatus}</p></section></div><div className="form-footer"><button className="secondary" onClick={()=>onNavigate('renewals')}>Renew subscription</button>{selected.certificateId&&<button className="primary" onClick={()=>onNavigate('certificates')}>Open certificate</button>}</div></section></div>}</div>
}
