import { useMemo, useState } from 'react';
import { Download, Eye } from 'lucide-react';
import { Attendance, Installation, InventoryAccount, JOB_TYPES, JobType, Movement, Shift, Technician, WorkBreak, WorkSession, completionActor, jobLabel, jobReference } from '../types';
import { dayKey, displayTime, displayTimeOnly, periodRange } from '../lib/domain';
import { createCompletedJobsWorkbook, downloadWorkbook } from '../lib/excel';
import { categoryUnitCount, COMPLAINT_JOB_TYPES, jobTypeUnitCount, jobUnits, shiftMatchesServiceCategory } from '../lib/reporting';
import { JobDetailModal } from './JobDetailModal';

type ReportCategory = 'all' | 'new_installation' | 'complaints' | 'removals';

export function ReportsPanel(p:{technicians:Technician[];installations:Installation[];movements:Movement[];accounts:InventoryAccount[];shifts:Shift[];attendance:Attendance[];loginLogs:Attendance[];workSessions:WorkSession[];workBreaks:WorkBreak[]}) {
  const today=dayKey(new Date()), initial=periodRange(today,'monthly'), pageSize=20;
  const [period,setPeriod]=useState<'daily'|'weekly'|'monthly'|'custom'>('monthly');
  const [anchor,setAnchor]=useState(today), [from,setFrom]=useState(initial[0]), [to,setTo]=useState(initial[1]);
  const [tech,setTech]=useState('all'), [category,setCategory]=useState<ReportCategory>('all'), [type,setType]=useState<'all'|JobType>('all');
  const [sortAsc,setSortAsc]=useState(true), [page,setPage]=useState(1), [exporting,setExporting]=useState(false), [error,setError]=useState('');
  const [selected,setSelected]=useState<Shift|null>(null);
  const techs=p.technicians.filter(item=>item.role==='technician'&&(tech==='all'||item.uid===tech));
  const inScope=(shift:Shift,start:string,end:string)=>shift.date>=start&&shift.date<=end&&!shift.is_deleted&&shift.status!=='cancelled'&&(tech==='all'||shift.technician_id===tech);
  const baseRows=useMemo(()=>p.shifts.filter(shift=>inScope(shift,from,to)&&p.installations.some(item=>item.shift_id===shift.id||item.id===shift.id)),[p.shifts,p.installations,from,to,tech]);
  const verificationRows=useMemo(()=>{const ids=new Set(baseRows.map(shift=>shift.id));return p.installations.filter(item=>ids.has(item.shift_id||item.id))},[baseRows,p.installations]);
  const rows=useMemo(()=>baseRows.filter(shift=>shiftMatchesServiceCategory(shift,category)&&(type==='all'||jobTypeUnitCount([shift],type)>0)).sort((a,b)=>(sortAsc?1:-1)*(a.assigned_at||a.scheduled_at).localeCompare(b.assigned_at||b.scheduled_at)),[baseRows,category,type,sortAsc]);
  const todayRows=useMemo(()=>p.shifts.filter(shift=>inScope(shift,today,today)&&shiftMatchesServiceCategory(shift,category)&&(type==='all'||jobTypeUnitCount([shift],type)>0)).sort((a,b)=>a.scheduled_at.localeCompare(b.scheduled_at)),[p.shifts,today,tech,category,type]);
  const pages=Math.max(1,Math.ceil(rows.length/pageSize)), currentPage=Math.min(page,pages), visible=rows.slice((currentPage-1)*pageSize,currentPage*pageSize);
  const totalUnits=baseRows.reduce((sum,shift)=>sum+jobUnits(shift).length,0);

  function range(value:string,next=period){setAnchor(value);if(next!=='custom'){const values=periodRange(value,next);setFrom(values[0]);setTo(values[1])}setPage(1)}
  function chooseCategory(next:ReportCategory){setCategory(next);setType('all');setPage(1);document.getElementById('detailed-jobs-report')?.scrollIntoView({behavior:'smooth',block:'start'})}
  async function exportReport(){setExporting(true);setError('');try{const completed=rows.filter(shift=>p.installations.some(item=>item.shift_id===shift.id||item.id===shift.id));const book=await createCompletedJobsWorkbook(completed,p.installations,p.attendance);const name=category==='all'?'All':category==='new_installation'?'New_Installations':category==='complaints'?'Complaints':'Removals';await downloadWorkbook(book,`SecureTrack_${name}_${from}_${to}.xlsx`)}catch(cause:any){setError(cause.message)}finally{setExporting(false)}}

  return <>
    {error&&<div className="notice error">{error}</div>}
    <section className="panel report-toolbar">
      <div className="section-label"><div><h2>Jobs report</h2><p>New installations are reported separately. Inspections and device or SIM changes are grouped as complaints.</p></div><button className="download-button" disabled={exporting} onClick={exportReport}><span className="docs"><Download/>{exporting?'Preparing…':'Download report Excel'}</span><span className="download"><Download/></span></button></div>
      <div className="filter-grid">
        <label>Period<select value={period} onChange={event=>{const next=event.target.value as typeof period;setPeriod(next);range(anchor,next)}}><option value="daily">Daily</option><option value="weekly">Weekly</option><option value="monthly">Monthly</option><option value="custom">Custom</option></select></label>
        {period!=='custom'&&<label>Reference date<input type="date" value={anchor} onChange={event=>range(event.target.value)}/></label>}
        <label>From<input type="date" value={from} onChange={event=>{setPeriod('custom');setFrom(event.target.value);setPage(1)}}/></label><label>To<input type="date" value={to} onChange={event=>{setPeriod('custom');setTo(event.target.value);setPage(1)}}/></label>
        <label>Technician<select value={tech} onChange={event=>{setTech(event.target.value);setPage(1)}}><option value="all">All technicians</option>{p.technicians.filter(item=>item.role==='technician').map(item=><option key={item.uid} value={item.uid}>{item.displayName||item.email}</option>)}</select></label>
        <label>Service category<select value={category} onChange={event=>{setCategory(event.target.value as ReportCategory);setPage(1)}}><option value="all">All categories</option><option value="new_installation">New installations</option><option value="complaints">Complaints</option><option value="removals">Removals</option></select></label>
        <label>Exact work type<select value={type} onChange={event=>{setType(event.target.value as 'all'|JobType);setPage(1)}}><option value="all">All work types</option>{JOB_TYPES.map(jobType=><option key={jobType} value={jobType}>{jobLabel(jobType)}</option>)}</select></label>
      </div>
    </section>
    <section className="panel"><div className="section-label"><div><h2>Online verification quality</h2><p>Final checks and correction counts are retained for technician performance history.</p></div></div><div className="metrics report-counts"><div className="metric"><span>VERIFIED ONLINE</span><strong>{verificationRows.filter(item=>item.online_status==='showing_online').length}</strong></div><div className="metric"><span>FIRST-CHECK PASSES</span><strong>{verificationRows.filter(item=>item.online_status==='showing_online'&&!Number(item.online_check_failures||0)).length}</strong></div><div className="metric"><span>CORRECTIONS RECORDED</span><strong>{verificationRows.reduce((sum,item)=>sum+Number(item.online_check_failures||0),0)}</strong></div><div className="metric"><span>AWAITING FINAL CHECK</span><strong>{verificationRows.filter(item=>item.online_status!=='showing_online').length}</strong></div></div></section>
    <section className="panel service-category-report">
      <div className="section-label"><div><h2>Service category report</h2><p>Counts are per vehicle or unit, including multi-vehicle jobs.</p></div></div>
      <div className="metrics report-counts report-category-counts">
        <button type="button" className={`metric dashboard-tile ${category==='new_installation'?'active':''}`} onClick={()=>chooseCategory('new_installation')}><span>NEW INSTALLATIONS</span><strong>{categoryUnitCount(baseRows,'new_installation')}</strong></button>
        <button type="button" className={`metric dashboard-tile ${category==='complaints'?'active':''}`} onClick={()=>chooseCategory('complaints')}><span>COMPLAINTS</span><strong>{categoryUnitCount(baseRows,'complaints')}</strong></button>
        <button type="button" className={`metric dashboard-tile ${category==='removals'?'active':''}`} onClick={()=>chooseCategory('removals')}><span>REMOVALS</span><strong>{categoryUnitCount(baseRows,'removals')}</strong></button>
        <button type="button" className={`metric dashboard-tile ${category==='all'?'active':''}`} onClick={()=>chooseCategory('all')}><span>TOTAL UNITS</span><strong>{totalUnits}</strong></button>
      </div>
      <div className="complaint-breakdown">{COMPLAINT_JOB_TYPES.map(jobType=><div key={jobType}><span>{jobLabel(jobType)}</span><strong>{jobTypeUnitCount(baseRows,jobType)}</strong></div>)}</div>
    </section>
    <section className="panel todays-jobs"><div className="section-label"><div><h2>Today’s jobs</h2><p>Click any job to open its complete details.</p></div><span>{todayRows.length} job{todayRows.length===1?'':'s'}</span></div><div className="today-job-grid">{todayRows.map(shift=>{const job=p.installations.find(item=>item.shift_id===shift.id||item.id===shift.id),arrival=p.attendance.find(item=>item.id===shift.id);return <button type="button" className="today-job-card" key={shift.id} onClick={()=>setSelected(shift)}><div><span>{displayTimeOnly(shift.scheduled_at,shift.timezone)} · {jobLabel(shift.job_type)}</span><strong>{shift.company_name||shift.site_name}</strong><small>{shift.technician_name} · {job?'Completed':arrival?'In progress':'Assigned'}</small></div><Eye/></button>})}{!todayRows.length&&<div className="empty">No jobs assigned for today.</div>}</div></section>
    <section className="panel"><h2>Technician breakdown</h2><div className="table-wrap"><table><thead><tr><th>Technician</th><th>New installations</th><th>Complaints</th><th>Removals</th><th>Total units</th><th>Verified online</th><th>First-check passes</th><th>Corrections</th><th>Awaiting check</th></tr></thead><tbody>{techs.map(item=>{const own=rows.filter(shift=>shift.technician_id===item.uid),checks=verificationRows.filter(record=>record.technician_id===item.uid);return <tr key={item.uid}><td>{item.displayName||item.email}</td><td>{categoryUnitCount(own,'new_installation')}</td><td>{categoryUnitCount(own,'complaints')}</td><td>{categoryUnitCount(own,'removals')}</td><td><strong>{own.reduce((sum,shift)=>sum+jobUnits(shift).length,0)}</strong></td><td>{checks.filter(record=>record.online_status==='showing_online').length}</td><td>{checks.filter(record=>record.online_status==='showing_online'&&!Number(record.online_check_failures||0)).length}</td><td>{checks.reduce((sum,record)=>sum+Number(record.online_check_failures||0),0)}</td><td>{checks.filter(record=>record.online_status!=='showing_online').length}</td></tr>})}</tbody></table></div></section>
    <section className="panel" id="detailed-jobs-report"><div className="section-label"><div><h2>Detailed jobs</h2><p>Click a row or View details to open the complete job record.</p></div><button className="text-button" onClick={()=>setSortAsc(value=>!value)}>Assigned At {sortAsc?'↑':'↓'}</button></div><div className="table-wrap"><table className="clickable-table"><thead><tr><th>Job ID</th><th>Job type</th><th>Technician</th><th>Assigned At</th><th>Arrived At</th><th>Completed At</th><th>Completed by</th><th>IMEI</th><th>SIM</th><th>Device model</th><th>Customer</th><th>Status</th><th>Details</th></tr></thead><tbody>{visible.map(shift=>{const job=p.installations.find(item=>item.shift_id===shift.id||item.id===shift.id),arrival=p.attendance.find(item=>item.id===shift.id);return <tr key={shift.id} tabIndex={0} onClick={()=>setSelected(shift)} onKeyDown={event=>{if(event.key==='Enter'||event.key===' ')setSelected(shift)}}><td>{jobReference(shift)}</td><td>{jobLabel(shift.job_type)}</td><td>{shift.technician_name}</td><td>{displayTime(shift.assigned_at||shift.scheduled_at,shift.timezone)}</td><td>{arrival?displayTime(arrival.timestamp,shift.timezone):'—'}</td><td>{job?displayTime(job.completed_at||job.timestamp,shift.timezone):'—'}</td><td>{job?completionActor(job):'—'}</td><td>{job?.device_imeis?.join(' · ')||'—'}</td><td>{job?.sim_numbers?.join(' · ')||'—'}</td><td>{job?.device_model||'—'}</td><td>{shift.company_name||shift.site_name}</td><td>{job?'Completed':arrival?'In progress':'Assigned'}</td><td><button type="button" className="text-button table-detail-action" onClick={event=>{event.stopPropagation();setSelected(shift)}}><Eye/>View details</button></td></tr>})}</tbody></table>{!visible.length&&<div className="empty">No jobs match these filters.</div>}</div><div className="pagination"><button className="secondary" disabled={currentPage<=1} onClick={()=>setPage(value=>value-1)}>Previous</button><span>Page {currentPage} of {pages}</span><button className="secondary" disabled={currentPage>=pages} onClick={()=>setPage(value=>value+1)}>Next</button></div></section>
    {selected&&<JobDetailModal shift={selected} installation={p.installations.find(item=>item.shift_id===selected.id||item.id===selected.id)} attendance={p.attendance.find(item=>item.id===selected.id)} onClose={()=>setSelected(null)}/>}
  </>;
}
