import { FormEvent, useEffect, useState } from 'react';
import { Bell, Check, Package, Pencil, Radio, Save, UsersRound } from 'lucide-react';
import { StockAlertSettings } from '../types';
type AlertArea='device'|'sim'|'technician';
const clock=(value:string)=>{const [hour,minute]=value.split(':').map(Number);const suffix=hour>=12?'PM':'AM';return `${String((hour%12)||12).padStart(2,'0')}:${String(minute).padStart(2,'0')} ${suffix}`};
export function StockAlertSettingsPanel({settings,canEditStock,canEditTechnician,onSave}:{settings:StockAlertSettings;canEditStock:boolean;canEditTechnician:boolean;onSave:(settings:StockAlertSettings)=>Promise<void>}){
 const [draft,setDraft]=useState(settings);const [selected,setSelected]=useState<AlertArea>('device');const [editing,setEditing]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState('');useEffect(()=>setDraft(settings),[settings]);
 const canEdit=selected==='technician'?canEditTechnician:canEditStock;
 const content={device:{title:'Device stock alerts',text:'Alert when a technician’s FMC, FMM, GT06, LV02, Jimi or Ruptela balance is running low.',save:'Save device alert'},sim:{title:'SIM stock alerts',text:'Alert when Etisalat, du or International SIM cards are running low for any technician.',save:'Save SIM alert'},technician:{title:'Technician alerts',text:'Set the working-time thresholds used for technician and HR late-work alerts.',save:'Save technician alerts'}}[selected];
 async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{await onSave(draft);setEditing(false)}catch(err:any){setError(err.message)}finally{setBusy(false)}}
 const card=(area:AlertArea,Icon:any,title:string,description:string)=><button type="button" className={'alert-coverage-card '+(selected===area?'active':'')} onClick={()=>{setSelected(area);setEditing(false)}}><Icon/><div><strong>{title}</strong><span>{description}</span></div></button>;
 const summary=selected==='technician'?`${clock(settings.clock_in_time)} – ${clock(settings.clock_out_time)} · ${settings.late_grace_minutes} min grace · ${settings.max_break_minutes} min break`:`Alert at ${settings.threshold} or below`;
 return <section className="panel alert-settings-panel"><div className="section-title"><div className="icon-box"><Bell/></div><div><h2>Alert settings</h2><p>Choose a category to view its saved settings or make an edit.</p></div></div><div className="alert-coverage-grid">{card('device',Package,'Device stock','FMC, GT06, LV02, Jimi and Ruptela')}{card('sim',Radio,'SIM stock','Etisalat, du and International SIMs')}{card('technician',UsersRound,'Technician alerts','Jobs, stock, late arrival and clock-out')}</div><div className="alert-detail"><span className="eyebrow">{selected==='sim'?'SIM CARDS':selected==='device'?'DEVICES':'TECHNICIANS'}</span><h3>{content.title}</h3><p>{content.text}</p></div>{error&&<div className="notice error">{error}</div>}{!editing&&<div className="saved-alert-setting"><div><Check/><div><strong>Saved setting</strong><span>{summary}</span></div></div>{canEdit&&<button type="button" className="secondary" onClick={()=>setEditing(true)}><Pencil/>Edit</button>}</div>}{editing&&<form onSubmit={submit} className="threshold-form">{selected==='technician'?<div className="form-row technician-alert-fields"><label>Work starts<input type="time" value={draft.clock_in_time} onChange={e=>setDraft(value=>({...value,clock_in_time:e.target.value}))}/></label><label>Work ends<input type="time" value={draft.clock_out_time} onChange={e=>setDraft(value=>({...value,clock_out_time:e.target.value}))}/></label><label>Late grace (minutes)<input type="number" min="0" max="180" value={draft.late_grace_minutes} onChange={e=>setDraft(value=>({...value,late_grace_minutes:Math.max(0,Math.min(180,Number(e.target.value)||0))}))}/></label><label>Maximum break (minutes)<input type="number" min="1" max="240" value={draft.max_break_minutes} onChange={e=>setDraft(value=>({...value,max_break_minutes:Math.max(1,Math.min(240,Number(e.target.value)||1))}))}/></label></div>:<label>{selected==='device'?'Device':'SIM'} low-stock level<input type="number" min="0" max="10000" step="1" value={draft.threshold} onChange={e=>setDraft(value=>({...value,threshold:Math.max(0,Math.min(10000,Number(e.target.value)||0))}))}/><small>One shared low-stock level applies to devices and every SIM network.</small></label>}<div className="settings-edit-actions"><button type="button" className="secondary" onClick={()=>{setDraft(settings);setEditing(false)}}>Cancel</button><button className="primary" disabled={busy}><Save/>{busy?'Saving…':content.save}</button></div></form>}</section>;
}
