import { FormEvent, useState } from 'react';
import { Bell, Check, Package, Radio, Save, UsersRound } from 'lucide-react';
import { StockAlertSettings } from '../types';

type AlertArea='device'|'sim'|'technician';
export function StockAlertSettingsPanel({settings,canEdit,onSave}:{settings:StockAlertSettings;canEdit:boolean;onSave:(threshold:number)=>Promise<void>}){
 const [threshold,setThreshold]=useState(settings.threshold);const [selected,setSelected]=useState<AlertArea>('device');const [busy,setBusy]=useState(false);const [notice,setNotice]=useState('');const [error,setError]=useState('');
 const content={device:{title:'Device stock alerts',text:'Alert when a technician’s FMC, FMM, GT06, LV02, Jimi or Ruptela balance is running low.',label:'Device low-stock level',save:'Save device alert'},sim:{title:'SIM stock alerts',text:'Alert when Etisalat, du or International SIM cards are running low for any technician.',label:'SIM low-stock level',save:'Save SIM alert'},technician:{title:'Technician alerts',text:'Technicians receive notices for new jobs and issued stock. HR receives late clock-in and late clock-out alerts.',label:'Technician stock-alert level',save:'Save technician alert'}}[selected];
 async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError('');setNotice('');try{await onSave(threshold);setNotice(`${content.title} saved.`)}catch(err:any){setError(err.message)}finally{setBusy(false)}}
 const card=(area:AlertArea,Icon:any,title:string,description:string)=><button type="button" className={'alert-coverage-card '+(selected===area?'active':'')} onClick={()=>setSelected(area)}><Icon/><div><strong>{title}</strong><span>{description}</span></div></button>;
 return <section className="panel alert-settings-panel"><div className="section-title"><div className="icon-box"><Bell/></div><div><h2>Alert settings</h2><p>Choose a category to open and manage its alert coverage.</p></div></div><div className="alert-coverage-grid">{card('device',Package,'Device stock','FMC, GT06, LV02, Jimi and Ruptela')}{card('sim',Radio,'SIM stock','Etisalat, du and International SIMs')}{card('technician',UsersRound,'Technician alerts','Jobs, stock and attendance alerts')}</div><div className="alert-detail"><span className="eyebrow">{selected==='sim'?'SIM CARDS':selected==='device'?'DEVICES':'TECHNICIANS'}</span><h3>{content.title}</h3><p>{content.text}</p></div>{error&&<div className="notice error">{error}</div>}{notice&&<div className="notice success"><Check/>{notice}</div>}<form onSubmit={submit} className="threshold-form"><label>{content.label}<input type="number" min="0" max="10000" step="1" disabled={!canEdit} value={threshold} onChange={e=>setThreshold(Math.max(0,Math.min(10000,Number(e.target.value)||0)))} /><small>SecureTrack currently uses one shared low-stock level for devices and every SIM network.</small></label>{canEdit?<button className="primary" disabled={busy}><Save/>{busy?'Saving…':content.save}</button>:<div className="notice info">Only an administrator or Accounts user can change the stock-alert level.</div>}</form></section>;
}