import { useMemo, useState } from 'react';
import { Download, Eye } from 'lucide-react';
import { Attendance, Installation, InventoryAccount, JOB_TYPES, JobType, Movement, Shift, Technician, WorkBreak, WorkSession, completionActor, jobLabel, jobReference } from '../types';
import { dayKey, displayTime } from '../lib/domain';
import { createReportWorkbook, downloadWorkbook } from '../lib/excel';
import { JobDetailModal } from './JobDetailModal';

interface Props { profile:Technician; shifts:Shift[]; installations:Installation[]; attendance:Attendance[]; movements:Movement[]; accounts:InventoryAccount[]; loginLogs:Attendance[]; workSessions:WorkSession[]; workBreaks:WorkBreak[] }

export function TechnicianHistory(p:Props){
 const today=dayKey(new Date());const [from,setFrom]=useState(today.slice(0,7)+'-01');const [to,setTo]=useState(today);const [type,setType]=useState<'all'|JobType>('all');const [selected,setSelected]=useState<Shift|null>(null);const [exporting,setExporting]=useState(false);const [error,setError]=useState('');
 const rows=useMemo(()=>p.shifts.map(shift=>({shift,installation:p.installations.find(item=>item.shift_id===shift.id||item.id===shift.id)})).filter((row):row is {shift:Shift;installation:Installation}=>!!row.installation).filter(({shift,installation})=>{const completed=dayKey(installation.completed_at||installation.timestamp);return completed>=from&&completed<=to&&(type==='all'||shift.job_type===type)}).sort((a,b)=>(b.installation.completed_at||b.installation.timestamp).localeCompare(a.installation.completed_at||a.installation.timestamp)),[p.shifts,p.installations,from,to,type]);
 const unitCount=(kind:JobType)=>rows.reduce((total,{shift})=>total+(shift.unit_jobs?shift.unit_jobs.filter(unit=>unit.job_type===kind).length:shift.job_type===kind?shift.unit_count:0),0);
 async function exportReport(){setExporting(true);setError('');try{await downloadWorkbook(await createReportWorkbook([p.profile],rows.map(row=>row.installation),p.movements,p.accounts,rows.map(row=>row.shift),p.attendance,p.loginLogs,from,to,{jobType:type,period:'custom',workSessions:p.workSessions,workBreaks:p.workBreaks}),`SecureTrack_My_History_${from}_${to}.xlsx`)}catch(e:any){setError(e.message)}finally{setExporting(false)}}
 return <>{error&&<div className="notice error">{error}</div>}<section className="panel report-toolbar"><div className="section-label"><div><h2>My history & report</h2><p>Completed work only. Past unfinished jobs do not appear here.</p></div><button className="secondary" disabled={exporting||!rows.length} onClick={exportReport}><Download/>{exporting?'Preparing…':'Download Excel'}</button></div><div className="filter-grid"><label>From<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>To<input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label><label>Job type<select value={type} onChange={e=>setType(e.target.value as 'all'|JobType)}><option value="all">All job types</option>{JOB_TYPES.map(kind=><option key={kind} value={kind}>{jobLabel(kind)}</option>)}</select></label></div></section><div className="metrics report-counts"><div className="metric"><span>COMPLETED JOBS</span><strong>{rows.length}</strong></div>{(['new_installation','device_change','sim_change','sim_device_change','device_removal','inspection'] as JobType[]).map(kind=><div className="metric" key={kind}><span>{jobLabel(kind).toUpperCase()}</span><strong>{unitCount(kind)}</strong></div>)}</div><section className="panel"><div className="section-label"><div><h2>Completed work</h2><p>Open any row to see the full job record.</p></div><span>{rows.length} job{rows.length===1?'':'s'}</span></div><div className="table-wrap"><table className="clickable-table"><thead><tr><th>Job ID</th><th>Completed</th><th>Customer</th><th>Job</th><th>Units</th><th>Completed by</th><th>IMEI</th><th>SIM</th><th>Details</th></tr></thead><tbody>{rows.map(({shift,installation})=><tr key={shift.id} tabIndex={0} onClick={()=>setSelected(shift)} onKeyDown={e=>{if(e.key==='Enter')setSelected(shift)}}><td>{jobReference(shift)}</td><td>{displayTime(installation.completed_at||installation.timestamp,shift.timezone)}</td><td>{shift.company_name||shift.site_name}</td><td>{jobLabel(shift.job_type)}</td><td>{shift.unit_count}</td><td>{completionActor(installation)}</td><td>{installation.device_imeis?.join(' · ')||'—'}</td><td>{installation.sim_numbers?.join(' · ')||'—'}</td><td><button type="button" className="text-button table-detail-action" onClick={e=>{e.stopPropagation();setSelected(shift)}}><Eye/>View</button></td></tr>)}</tbody></table>{!rows.length&&<div className="empty">No completed jobs match this period.</div>}</div></section>{selected&&<JobDetailModal shift={selected} installation={p.installations.find(i=>i.shift_id===selected.id||i.id===selected.id)} attendance={p.attendance.find(a=>a.id===selected.id)} onClose={()=>setSelected(null)}/>}</>;
}
