import { getIdToken } from './auth';
const API_BASE=(import.meta.env.VITE_API_URL||'/api').replace(/\/$/,''); export const db={kind:'securetrack-aws-store'} as const;
type Constraint={type:string;field?:string;op?:string;value?:any;direction?:'asc'|'desc';count?:number;id?:string}; export type DocumentReference={kind:'doc';collection:string;id:string;path:string}; export type CollectionReference={kind:'collection';collection:string}; export type QueryReference={kind:'query';collection:string;constraints:Constraint[]};
export class DocumentSnapshot<T=any>{readonly metadata={hasPendingWrites:false};constructor(public ref:DocumentReference,private value:T|undefined,readonly version=0){}get id(){return this.ref.id}exists(){return this.value!==undefined}data(){return this.value}}
class QuerySnapshot<T=any>{constructor(public docs:DocumentSnapshot<T>[]){}}
async function request(path:string,init:RequestInit={}){const response=await fetch(API_BASE+path,{...init,headers:{'content-type':'application/json',authorization:`Bearer ${await getIdToken()}`,...(init.headers||{})}});if(!response.ok){const body=await response.json().catch(()=>({}));const error:any=new Error(body.message||`SecureTrack API request failed (${response.status}).`);error.status=response.status;throw error}return response.status===204?null:response.json()}
const randomId=()=>crypto.randomUUID().replace(/-/g,''); export function collection(_db:any,name:string):CollectionReference{return{kind:'collection',collection:name}}
export function doc(parent:any,name?:string,id?:string):DocumentReference{if(parent?.kind==='collection'){const key=name||randomId();return{kind:'doc',collection:parent.collection,id:key,path:`${parent.collection}/${key}`}}if(!name)throw new Error('Document collection is required.');const key=id||randomId();return{kind:'doc',collection:name,id:key,path:`${name}/${key}`}}
export function query(ref:CollectionReference|QueryReference,...constraints:Constraint[]):QueryReference{return{kind:'query',collection:ref.collection,constraints:[...('constraints'in ref?ref.constraints:[]),...constraints]}}
export const where=(field:string,op:string,value:any):Constraint=>({type:'where',field,op,value});export const orderBy=(field:string,direction:'asc'|'desc'='asc'):Constraint=>({type:'orderBy',field,direction});export const limit=(count:number):Constraint=>({type:'limit',count});export const startAt=(value:any):Constraint=>({type:'startAt',value});export const endAt=(value:any):Constraint=>({type:'endAt',value});export const startAfter=(snapshot:DocumentSnapshot):Constraint=>({type:'startAfter',id:snapshot.id,value:snapshot.data()});
export const serverTimestamp=()=>({__securetrackOp:'serverTimestamp'});export const deleteField=()=>({__securetrackOp:'deleteField'});export const arrayUnion=(...values:any[])=>({__securetrackOp:'arrayUnion',values});export const Timestamp={fromDate:(value:Date)=>value.toISOString()};
export async function getDoc<T=any>(ref:DocumentReference){const row=await request(`/documents/${encodeURIComponent(ref.collection)}/${encodeURIComponent(ref.id)}`);return new DocumentSnapshot<T>(ref,row?.exists?row.data:undefined,row?.version||0)}export const getDocFromServer=getDoc;
export async function getDocs<T=any>(ref:CollectionReference|QueryReference){const result=await request('/documents/query',{method:'POST',body:JSON.stringify({collection:ref.collection,constraints:'constraints'in ref?ref.constraints:[]})});return new QuerySnapshot<T>((result.items||[]).map((row:any)=>new DocumentSnapshot<T>(doc(db,ref.collection,row.id),row.data,row.version)))}
export async function getCountFromServer(ref:CollectionReference|QueryReference){const snapshot=await getDocs(ref);return{data:()=>({count:snapshot.docs.length})}}
export async function setDoc(ref:DocumentReference,data:any,options?:{merge?:boolean}){await request(`/documents/${encodeURIComponent(ref.collection)}/${encodeURIComponent(ref.id)}`,{method:'PUT',body:JSON.stringify({data,merge:!!options?.merge})})}export async function updateDoc(ref:DocumentReference,data:any){await request(`/documents/${encodeURIComponent(ref.collection)}/${encodeURIComponent(ref.id)}`,{method:'PATCH',body:JSON.stringify({data})})}export async function deleteDoc(ref:DocumentReference){await request(`/documents/${encodeURIComponent(ref.collection)}/${encodeURIComponent(ref.id)}`,{method:'DELETE'})}export async function addDoc(ref:CollectionReference,data:any){const target=doc(ref);await setDoc(target,data);return target}
type Write={op:'set'|'update'|'delete';ref:DocumentReference;data?:any;merge?:boolean};export class WriteBatch{writes:Write[]=[];set(ref:DocumentReference,data:any,options?:{merge?:boolean}){this.writes.push({op:'set',ref,data,merge:!!options?.merge});return this}update(ref:DocumentReference,data:any){this.writes.push({op:'update',ref,data});return this}delete(ref:DocumentReference){this.writes.push({op:'delete',ref});return this}async commit(){if(this.writes.length)await request('/documents/batch',{method:'POST',body:JSON.stringify({writes:serializeWrites(this.writes)})})}}export function writeBatch(_db:any){return new WriteBatch()}
export class Transaction extends WriteBatch{reads=new Map<string,number>();async get(ref:DocumentReference){const snap=await getDoc(ref);this.reads.set(ref.path,snap.version);return snap}}const serializeWrites=(writes:Write[])=>writes.map(item=>({op:item.op,collection:item.ref.collection,id:item.ref.id,data:item.data,merge:item.merge}));
export async function runTransaction<T>(_db:any,callback:(tx:Transaction)=>Promise<T>){let last:any;for(let attempt=0;attempt<5;attempt++){const tx=new Transaction(),value=await callback(tx);try{await request('/documents/transaction',{method:'POST',body:JSON.stringify({reads:[...tx.reads].map(([path,version])=>({path,version})),writes:serializeWrites(tx.writes)})});return value}catch(error:any){last=error;if(error?.status!==409)throw error}}throw last||new Error('The record changed while you were editing it. Please retry.')}
export function onSnapshot(ref:any,optionsOrNext:any,nextOrError?:any,maybeError?:any){const next=typeof optionsOrNext==='function'?optionsOrNext:nextOrError,error=typeof optionsOrNext==='function'?nextOrError:maybeError;let stopped=false,previous='';const load=async()=>{try{const snapshot=ref.kind==='doc'?await getDoc(ref):await getDocs(ref),current=JSON.stringify(ref.kind==='doc'?[snapshot.exists(),snapshot.data(),snapshot.version]:snapshot.docs.map((d:any)=>[d.id,d.data(),d.version]));if(!stopped&&current!==previous){previous=current;next(snapshot)}}catch(e:any){if(!stopped)error?.(e)}};void load();const timer=window.setInterval(load,5000),wake=()=>{if(!document.hidden)void load()};window.addEventListener('online',wake);document.addEventListener('visibilitychange',wake);return()=>{stopped=true;window.clearInterval(timer);window.removeEventListener('online',wake);document.removeEventListener('visibilitychange',wake)}}