import express from 'express';import pg from 'pg';import{CognitoJwtVerifier}from'aws-jwt-verify';import{AdminCreateUserCommand,AdminDeleteUserCommand,AdminSetUserPasswordCommand,ChangePasswordCommand,CognitoIdentityProviderClient,InitiateAuthCommand,ForgotPasswordCommand,ConfirmForgotPasswordCommand}from'@aws-sdk/client-cognito-identity-provider';import{canRead,canWrite,type Actor}from'./policy.js';import{applyQuery}from'./query.js';import{enqueuePush,getVapidPublicKey,pushReady,registerPushSubscription,removePushSubscription,startPushWorker}from'./push.js';import{afterDocumentWrite}from'./events.js';import{startNotificationRules}from'./rules.js';
const{Pool}=pg,port=Number(process.env.PORT||8080),pool=new Pool({connectionString:process.env.DATABASE_URL||'',ssl:process.env.DB_SSL==='false'?false:{rejectUnauthorized:false},max:Number(process.env.DB_POOL_MAX||10)}),userPoolId=process.env.COGNITO_USER_POOL_ID||'',clientId=process.env.COGNITO_CLIENT_ID||'',region=process.env.AWS_REGION||'me-central-1',verifier=CognitoJwtVerifier.create({userPoolId,tokenUse:'id',clientId}),cognito=new CognitoIdentityProviderClient({region}),app=express();const mobileOrigins=new Set(['https://localhost','capacitor://localhost','http://localhost']);app.disable('x-powered-by');app.use(express.json({limit:'2mb'}));app.use((req,res,next)=>{const origin=req.headers.origin;if(origin&&mobileOrigins.has(origin)){res.setHeader('access-control-allow-origin',origin);res.setHeader('vary','Origin');res.setHeader('access-control-allow-methods','GET,HEAD,POST,PUT,PATCH,DELETE,OPTIONS');res.setHeader('access-control-allow-headers','authorization,content-type')}if(req.method==='OPTIONS')return res.status(204).end();next()});app.use((_,res,next)=>{res.setHeader('cache-control','no-store');res.setHeader('x-content-type-options','nosniff');next()});
type Req=express.Request&{actor?:Actor};const nowIso=()=>new Date().toISOString();function materialize(v:any):any{if(Array.isArray(v))return v.map(materialize);if(v&&typeof v==='object'){if(v.__securetrackOp==='serverTimestamp')return nowIso();if(v.__securetrackOp)return v;return Object.fromEntries(Object.entries(v).map(([k,x])=>[k,materialize(x)]))}return v}function patch(base:any,p:any){const out={...(base||{})};for(const[k,raw]of Object.entries(p||{})){const v:any=materialize(raw);if(v?.__securetrackOp==='deleteField')delete out[k];else if(v?.__securetrackOp==='arrayUnion'){const cur=Array.isArray(out[k])?out[k]:[];out[k]=[...cur,...v.values.filter((x:any)=>!cur.some((y:any)=>JSON.stringify(x)===JSON.stringify(y)))];}else out[k]=v}return out}
async function profile(uid:string){const r=await pool.query('select data from documents where collection=$1 and id=$2',['users',uid]);return r.rows[0]?.data||null}async function auth(req:Req,res:express.Response,next:express.NextFunction){try{const h=req.headers.authorization||'',token=h.startsWith('Bearer ')?h.slice(7):'';if(!token)return res.status(401).json({message:'Sign in required.'});const payload=await verifier.verify(token),p=await profile(String(payload.sub));if(!p||p.status==='deactivated')return res.status(403).json({message:'Account is not active.'});req.actor={uid:String(payload.sub),role:String(p.role||'technician'),status:String(p.status||'active')};next()}catch{return res.status(401).json({message:'Your session is invalid or expired.'})}}async function row(c:string,id:string,client:any=pool){const r=await client.query('select data,version from documents where collection=$1 and id=$2',[c,id]);return r.rows[0]||null}

async function canAuthorizeWrite(client:any,actor:Actor,c:string,id:string,next:any,existing:any,op:'set'|'update'|'delete'){
 if(!canWrite(actor,c,id,next,existing,op))return false;
 if(c!=='shifts'||actor.role!=='technician'||op!=='update')return true;
 if(existing?.status==='assigned'&&next?.status==='in_progress'){const arrival=await row('attendance_logs',id,client);return arrival?.data?.technician_id===actor.uid}
 if(existing?.status!=='in_progress'||!['in_progress','completed'].includes(next?.status))return false;
 const result=await client.query("select count(*)::int as count from documents where collection='installations' and (id=$1 or data->>'shift_id'=$1) and data->>'technician_id'=$2",[id,actor.uid]);
 const count=Number(result.rows[0]?.count||0),total=Math.max(1,Number(existing.unit_count||1)),completed=Number(next.completed_units??(next.status==='completed'?1:0));
 return count>0&&completed===Math.min(total,count)&&completed<=total&&(next.status==='completed'?completed>=total:completed<total);
}
async function write(client:any,actor:Actor,w:any){const c=String(w.collection||''),id=String(w.id||''),cur=await row(c,id,client),existing=cur?.data;let next=existing;if(w.op==='delete'){if(!canWrite(actor,c,id,null,existing,'delete'))throw Object.assign(new Error('Not permitted.'),{status:403});await client.query('delete from documents where collection=$1 and id=$2',[c,id]);await afterDocumentWrite(client,c,id,null,existing,'delete');return}if(w.op==='set')next=w.merge?patch(existing,w.data):materialize(w.data);else if(w.op==='update'){if(!cur)throw Object.assign(new Error('Document not found.'),{status:404});next=patch(existing,w.data)}else throw Object.assign(new Error('Invalid write.'),{status:400});const operation=w.op==='set'?'set':'update';if(!await canAuthorizeWrite(client,actor,c,id,next,existing,operation))throw Object.assign(new Error('Not permitted.'),{status:403});await client.query("insert into documents(collection,id,data,version,created_at,updated_at) values($1,$2,$3,1,now(),now()) on conflict(collection,id) do update set data=excluded.data,version=documents.version+1,updated_at=now()",[c,id,next]);await afterDocumentWrite(client,c,id,next,existing,operation)}
app.post('/v1/auth/login',async(req,res)=>{try{const email=String(req.body.email||'').trim().toLowerCase(),password=String(req.body.password||'');const out=await cognito.send(new InitiateAuthCommand({ClientId:clientId,AuthFlow:'USER_PASSWORD_AUTH',AuthParameters:{USERNAME:email,PASSWORD:password}})),a=out.AuthenticationResult;if(!a?.AccessToken||!a.IdToken)return res.status(401).json({message:'Authentication failed.'});const payload=await verifier.verify(a.IdToken),uid=String(payload.sub),p=await profile(uid);res.json({user:{uid,email:String(payload.email||email),displayName:String(payload.name||p?.displayName||''),metadata:{lastSignInTime:new Date().toISOString()}},accessToken:a.IdToken,refreshToken:a.RefreshToken,expiresIn:a.ExpiresIn||3600})}catch(e:any){res.status(401).json({code:e.name||'NotAuthorizedException',message:'The email or password is incorrect.'})}});
app.post('/v1/auth/refresh',async(req,res)=>{try{const out=await cognito.send(new InitiateAuthCommand({ClientId:clientId,AuthFlow:'REFRESH_TOKEN_AUTH',AuthParameters:{REFRESH_TOKEN:String(req.body.refreshToken||'')}})),a=out.AuthenticationResult;if(!a?.IdToken)return res.status(401).json({message:'Session refresh failed.'});res.json({accessToken:a.IdToken,expiresIn:a.ExpiresIn||3600})}catch{res.status(401).json({message:'Session refresh failed.'})}});
app.post('/v1/auth/logout',(_req,res)=>res.status(204).end());
app.post('/v1/auth/reauthenticate',auth,async(req:Req,res)=>{try{const email=String(req.body.email||'').trim().toLowerCase(),password=String(req.body.password||'');const out=await cognito.send(new InitiateAuthCommand({ClientId:clientId,AuthFlow:'USER_PASSWORD_AUTH',AuthParameters:{USERNAME:email,PASSWORD:password}})),id=out.AuthenticationResult?.IdToken;if(!id)return res.status(401).json({code:'auth/invalid-credential',message:'The current password is incorrect.'});const payload=await verifier.verify(id);if(String(payload.sub)!==req.actor!.uid)return res.status(401).json({code:'auth/invalid-credential',message:'The current password is incorrect.'});res.json({uid:String(payload.sub)})}catch{res.status(401).json({code:'auth/invalid-credential',message:'The current password is incorrect.'})}});
app.put('/v1/auth/password',auth,async(req:Req,res)=>{try{const email=String(req.body.email||'').trim().toLowerCase(),previous=String(req.body.currentPassword||''),proposed=String(req.body.password||'');if(!email||!previous||!proposed)return res.status(400).json({message:'Current and new password are required.'});const login=await cognito.send(new InitiateAuthCommand({ClientId:clientId,AuthFlow:'USER_PASSWORD_AUTH',AuthParameters:{USERNAME:email,PASSWORD:previous}})),access=login.AuthenticationResult?.AccessToken;if(!access)return res.status(401).json({message:'The current password is incorrect.'});await cognito.send(new ChangePasswordCommand({AccessToken:access,PreviousPassword:previous,ProposedPassword:proposed}));res.status(204).end()}catch(e:any){res.status(400).json({message:e.message})}});
app.post('/v1/auth/forgot-password',async(req,res)=>{try{await cognito.send(new ForgotPasswordCommand({ClientId:clientId,Username:String(req.body.email||'').trim().toLowerCase()}))}catch(e:any){console.warn('Cognito ForgotPassword failed',{name:e?.name||'UnknownError',requestId:e?.$metadata?.requestId})}res.status(204).end()});
app.post('/v1/auth/confirm-forgot-password',async(req,res)=>{const email=String(req.body.email||'').trim().toLowerCase(),code=String(req.body.code||'').trim(),password=String(req.body.password||'');if(!email||!code||!password)return res.status(400).json({message:'Email, reset code, and new password are required.'});try{await cognito.send(new ConfirmForgotPasswordCommand({ClientId:clientId,Username:email,ConfirmationCode:code,Password:password}));res.status(204).end()}catch(e:any){const name=String(e?.name||'');console.warn('Cognito ConfirmForgotPassword failed',{name:name||'UnknownError',requestId:e?.$metadata?.requestId});const message=name==='CodeMismatchException'||name==='ExpiredCodeException'?'That reset code is invalid or expired. Request a new code and try again.':name==='InvalidPasswordException'?'The new password does not meet the account password requirements.':'The password could not be reset. Check the code and try again.';res.status(400).json({message})}});
app.get('/health',async(_q,res)=>{try{await pool.query('select 1');res.json({ok:true})}catch{res.status(503).json({ok:false})}});
app.get('/v1/push/config',(_req,res)=>{if(!pushReady())return res.status(503).json({message:'Push delivery is not configured on the AWS server.'});res.json({publicKey:getVapidPublicKey()})});
app.post('/v1/push/subscriptions',auth,async(req:Req,res)=>{try{if(!pushReady())return res.status(503).json({message:'Push delivery is not configured on the AWS server.'});await registerPushSubscription(pool,req.actor!.uid,req.body);res.status(204).end()}catch(e:any){res.status(e.status||500).json({message:e.message||'Could not save push subscription.'})}});
app.delete('/v1/push/subscriptions',auth,async(req:Req,res)=>{try{await removePushSubscription(pool,req.actor!.uid,req.body?.endpoint);res.status(204).end()}catch{res.status(500).json({message:'Could not remove push subscription.'})}});
app.post('/v1/push/test',auth,async(req:Req,res)=>{try{await enqueuePush(pool,req.actor!.uid,`push-test:${Date.now()}`,{title:'SecureTrack test notification',body:'Push delivery from your AWS SecureTrack server is working.'});res.status(202).json({queued:true})}catch(e:any){res.status(503).json({message:e.message||'Could not queue push test.'})}});
app.get('/public/agreements/:token',async(req,res)=>{const t=req.params.token,item=t.length>=60?await row('agreement_links',t):null;if(!item||item.data?.is_deleted)return res.status(404).json({message:'Agreement link is invalid or expired.'});res.json({id:t,...item.data})});
app.post('/public/agreements/:token/view',async(req,res)=>{const t=req.params.token,item=await row('agreement_links',t);if(item?.data?.status==='sent')await pool.query('update documents set data=$3,version=version+1,updated_at=now() where collection=$1 and id=$2',['agreement_links',t,patch(item.data,{status:'viewed',viewed_at:nowIso()})]);res.status(204).end()});
app.post('/public/agreements/:token/sign',async(req,res)=>{const t=req.params.token,d=req.body||{};if(t.length<60||typeof d.signature!=='string'||d.signature.length<=100)return res.status(400).json({message:'Invalid signature submission.'});const client=await pool.connect();try{await client.query('begin');const link=await row('agreement_links',t,client);if(!link||!['sent','viewed'].includes(link.data?.status))throw Object.assign(new Error('Agreement link is invalid or already completed.'),{status:409});const signed={status:'signed',signer_name:String(d.signer_name||'').slice(0,160),signer_designation:String(d.signer_designation||'').slice(0,160),signer_mobile:String(d.signer_mobile||'').slice(0,80),signer_email:String(d.signer_email||'').slice(0,254),signature:d.signature,signed_at:nowIso(),signing_device:String(d.signing_device||'').slice(0,500)},next=patch(link.data,signed);await client.query('update documents set data=$3,version=version+1,updated_at=now() where collection=$1 and id=$2',['agreement_links',t,next]);const aid=String(link.data.agreement_id||link.data.id||'');if(aid){const a=await row('agreements',aid,client);if(a)await client.query('update documents set data=$3,version=version+1,updated_at=now() where collection=$1 and id=$2',['agreements',aid,patch(a.data,signed)])}await client.query('commit');res.json({id:t,...next})}catch(e:any){await client.query('rollback');res.status(e.status||500).json({message:e.message})}finally{client.release()}});
app.use('/documents',auth);app.get('/documents/:collection/:id',async(req:Req,res)=>{const collection=String(req.params.collection),id=String(req.params.id),item=await row(collection,id);if(!item)return res.json({exists:false});if(!canRead(req.actor!,collection,id,item.data))return res.status(403).json({message:'Not permitted.'});res.json({exists:true,data:item.data,version:Number(item.version)})});app.post('/documents/query',async(req:Req,res)=>{const c=String(req.body.collection||''),r=await pool.query('select id,data,version from documents where collection=$1 order by id limit 10000',[c]),visible=r.rows.filter(x=>canRead(req.actor!,c,x.id,x.data));res.json({items:applyQuery(visible,req.body.constraints||[]).map(x=>({id:x.id,data:x.data,version:Number(x.version)}))})});
for(const method of ['put','patch','delete']as const)(app as any)[method]('/documents/:collection/:id',async(req:Req,res:express.Response)=>{try{await write(pool,req.actor!,{op:method==='put'?'set':method==='patch'?'update':'delete',collection:req.params.collection,id:req.params.id,data:req.body?.data,merge:!!req.body?.merge});res.status(204).end()}catch(e:any){res.status(e.status||500).json({message:e.message})}});
app.post('/documents/batch',async(req:Req,res)=>{const client=await pool.connect();try{await client.query('begin');for(const w of req.body.writes||[])await write(client,req.actor!,w);await client.query('commit');res.status(204).end()}catch(e:any){await client.query('rollback');res.status(e.status||500).json({message:e.message})}finally{client.release()}});
app.post('/documents/transaction',async(req:Req,res)=>{const client=await pool.connect();try{await client.query('begin isolation level serializable');for(const x of req.body.reads||[]){const[c,id]=String(x.path||'').split('/'),r=await client.query('select version from documents where collection=$1 and id=$2 for update',[c,id]);if(Number(r.rows[0]?.version||0)!==Number(x.version||0))throw Object.assign(new Error('Document changed.'),{status:409})}for(const w of req.body.writes||[])await write(client,req.actor!,w);await client.query('commit');res.status(204).end()}catch(e:any){await client.query('rollback');res.status(e.status||(e.code==='40001'?409:500)).json({message:e.message})}finally{client.release()}});
app.post('/admin/users',auth,async(req:Req,res)=>{if(!['master_admin','admin'].includes(req.actor!.role))return res.status(403).json({message:'Not permitted.'});const email=String(req.body.email||'').trim().toLowerCase(),displayName=String(req.body.displayName||'').trim();try{const created=await cognito.send(new AdminCreateUserCommand({UserPoolId:userPoolId,Username:email,MessageAction:'SUPPRESS',UserAttributes:[{Name:'email',Value:email},{Name:'email_verified',Value:'true'},{Name:'name',Value:displayName}]}));await cognito.send(new AdminSetUserPasswordCommand({UserPoolId:userPoolId,Username:email,Password:String(req.body.password||''),Permanent:true}));const uid=created.User?.Attributes?.find(a=>a.Name==='sub')?.Value;if(!uid)throw new Error('Cognito did not return a user id.');res.json({uid})}catch(e:any){res.status(400).json({message:e.message})}});
app.delete('/admin/users/:username',auth,async(req:Req,res)=>{if(req.actor!.role!=='master_admin'&&req.actor!.role!=='admin')return res.status(403).json({message:'Not permitted.'});try{await cognito.send(new AdminDeleteUserCommand({UserPoolId:userPoolId,Username:String(req.params.username)}));res.status(204).end()}catch(e:any){res.status(400).json({message:e.message})}});if(pushReady())startPushWorker(pool);startNotificationRules(pool);app.listen(port,'0.0.0.0',()=>console.log(`SecureTrack AWS API listening on ${port}`));
